import type { Vec2 } from "../../cad/CadTypes.ts";
import type { Sketch } from "../Sketch.ts";
import type { SketchConstraint, SketchPointRef } from "../SketchConstraint.ts";
import type { SketchDimension } from "../SketchDimension.ts";
import type { SketchEntity } from "../SketchEntity.ts";
import { compileNurbsCurve2D, type CompiledNurbsCurve2D } from "../../curve/NurbsCurve.ts";
import { nurbsParameterTolerance } from "../../curve/NurbsTolerance.ts";
import { DEFAULT_SKETCH_SOLVER_OPTIONS, type SketchSolveResult, type SketchSolverDiagnostic, type SketchSolverOptions } from "./SolverTypes.ts";

type Variable = { entityId: string; key: string };
type Equation = { id: string; kind: "constraint" | "dimension"; evaluate: (entities: Record<string, SketchEntity>) => number[] };
const clone = <T>(value: T): T => structuredClone(value);
const norm = (values: number[]) => Math.sqrt(values.reduce((sum, value) => sum + value * value, 0));
const externalNurbsCompiledCache = new WeakMap<object, CompiledNurbsCurve2D>();
const compiledExternalNurbs = (entity: Extract<SketchEntity, { type: "external-bspline" }>): CompiledNurbsCurve2D => { let compiled=externalNurbsCompiledCache.get(entity);if(!compiled){compiled=compileNurbsCurve2D(entity);externalNurbsCompiledCache.set(entity,compiled);}return compiled; };
const nurbsReferenceParameter = (entity: Extract<SketchEntity, { type: "external-bspline" }>, ref: SketchPointRef): number | undefined => {
  if (ref.role === "start") return entity.firstParameter;
  if (ref.role === "end") return entity.lastParameter;
  if (ref.role !== "curve" || !Number.isFinite(ref.parameter)) return undefined;
  const parameter = ref.parameter!;
  const tolerance = nurbsParameterTolerance(entity.firstParameter, entity.lastParameter);
  if (parameter < entity.firstParameter - tolerance || parameter > entity.lastParameter + tolerance) return undefined;
  return Math.min(entity.lastParameter, Math.max(entity.firstParameter, parameter));
};
const point = (entities: Record<string, SketchEntity>, ref: SketchPointRef): Vec2 | undefined => { const entity = entities[ref.entityId]; if (!entity) return undefined; if ((entity.type === "line" || entity.type === "external-line") && (ref.role === "start" || ref.role === "end")) return entity[ref.role]; if (entity.type === "external-arc" && (ref.role === "start" || ref.role === "end")) { const angle=ref.role==="start"?entity.startAngle:entity.endAngle;return{x:entity.center.x+Math.cos(angle)*entity.radius,y:entity.center.y+Math.sin(angle)*entity.radius}; } if (entity.type === "external-bspline") { const parameter=nurbsReferenceParameter(entity,ref);return parameter===undefined?undefined:compiledExternalNurbs(entity).evaluate(parameter); } if (entity.type === "bspline" && !entity.closed && (ref.role === "start" || ref.role === "end")) return ref.role === "start" ? entity.fitPoints[0] : entity.fitPoints.at(-1); if ((entity.type === "circle" || entity.type === "arc" || entity.type === "external-circle" || entity.type === "external-arc") && ref.role === "center") return entity.center; if (entity.type === "point" && ref.role === "position") return entity.position; return undefined; };
const line = (entities: Record<string, SketchEntity>, id: string) => { const entity = entities[id]; return entity?.type === "line" || entity?.type === "external-line" ? entity : undefined; };
const circleLike = (entities: Record<string, SketchEntity>, id: string) => { const entity = entities[id]; return entity?.type === "circle" || entity?.type === "arc" || entity?.type === "external-circle" || entity?.type === "external-arc" ? entity : undefined; };
const bspline = (entities: Record<string, SketchEntity>, id: string) => { const entity = entities[id]; return entity?.type === "bspline" ? entity : undefined; };
const direction = (value: { start: Vec2; end: Vec2 }) => ({ x: value.end.x - value.start.x, y: value.end.y - value.start.y });
const length = (value: { x: number; y: number }) => Math.hypot(value.x, value.y);
const cross = (a: { x: number; y: number }, b: { x: number; y: number }) => a.x * b.y - a.y * b.x;
const dot = (a: { x: number; y: number }, b: { x: number; y: number }) => a.x * b.x + a.y * b.y;
const bsplineEndpointDirection = (entity: NonNullable<ReturnType<typeof bspline>>, role: "start" | "end"): Vec2 => { if (role === "start") return entity.startTangent ?? { x: entity.fitPoints[1].x - entity.fitPoints[0].x, y: entity.fitPoints[1].y - entity.fitPoints[0].y }; const last = entity.fitPoints.at(-1)!, previous = entity.fitPoints.at(-2)!; return entity.endTangent ?? { x: last.x - previous.x, y: last.y - previous.y }; };

const variablesFor = (entities: Record<string, SketchEntity>): Variable[] => Object.values(entities).flatMap((entity) => entity.type === "line" ? ["start.x","start.y","end.x","end.y"].map((key) => ({ entityId: entity.id, key })) : entity.type === "circle" || entity.type === "arc" ? ["center.x","center.y","radius"].map((key) => ({ entityId: entity.id, key })) : entity.type === "point" ? ["position.x","position.y"].map((key) => ({ entityId: entity.id, key })) : entity.type === "bspline" ? [...entity.fitPoints.flatMap((_, index) => [`fitPoints.${index}.x`, `fitPoints.${index}.y`]), ...(entity.startTangent && entity.endTangent ? ["startTangent.x","startTangent.y","endTangent.x","endTangent.y"] : [])].map((key) => ({ entityId: entity.id, key })) : []);
const get = (entities: Record<string, SketchEntity>, variable: Variable): number => { const path=variable.key.split("."); let value:unknown=entities[variable.entityId]; for(const key of path)value=(value as Record<string,unknown>)[key]; return value as number; };
const set = (entities: Record<string, SketchEntity>, variable: Variable, value: number): void => { const path=variable.key.split("."); let target:unknown=entities[variable.entityId]; for(const key of path.slice(0,-1))target=(target as Record<string,unknown>)[key]; (target as Record<string,number>)[path.at(-1)!]=value; };
const rank = (matrix: number[][], tolerance = 1e-7): number => { const data = matrix.map((row) => [...row]); let pivotRow = 0; for (let column = 0; column < (data[0]?.length ?? 0) && pivotRow < data.length; column += 1) { let best = pivotRow; for (let row = pivotRow + 1; row < data.length; row += 1) if (Math.abs(data[row][column]) > Math.abs(data[best][column])) best = row; if (Math.abs(data[best][column]) <= tolerance) continue; [data[pivotRow], data[best]] = [data[best], data[pivotRow]]; const pivot = data[pivotRow][column]; for (let j = column; j < data[pivotRow].length; j += 1) data[pivotRow][j] /= pivot; for (let row = 0; row < data.length; row += 1) if (row !== pivotRow) { const scale = data[row][column]; for (let j = column; j < data[row].length; j += 1) data[row][j] -= scale * data[pivotRow][j]; } pivotRow += 1; } return pivotRow; };
const solveLinear = (matrix: number[][], vector: number[]): number[] | undefined => { const size = vector.length; const augmented = matrix.map((row, index) => [...row, vector[index]]); for (let column = 0; column < size; column += 1) { let best = column; for (let row = column + 1; row < size; row += 1) if (Math.abs(augmented[row][column]) > Math.abs(augmented[best][column])) best = row; if (Math.abs(augmented[best][column]) < 1e-12) return undefined; [augmented[column], augmented[best]] = [augmented[best], augmented[column]]; const pivot = augmented[column][column]; for (let j = column; j <= size; j += 1) augmented[column][j] /= pivot; for (let row = 0; row < size; row += 1) if (row !== column) { const factor = augmented[row][column]; for (let j = column; j <= size; j += 1) augmented[row][j] -= factor * augmented[column][j]; } } return augmented.map((row) => row[size]); };
/** A numerically solved coincidence is exact at the CAD profile boundary.
 * This avoids leaking sub-tolerance endpoint gaps into OCCT wire construction. */
const normalizeCoincidentPoints = (sketch: Sketch, entities: Record<string, SketchEntity>): void => Object.values(sketch.constraints).forEach((constraint) => {
  if (!constraint.enabled || constraint.type !== "coincident" || !constraint.pointRefs || constraint.pointRefs.length < 2) return;
  const left = point(entities, constraint.pointRefs[0]); const right = point(entities, constraint.pointRefs[1]);
  if (left && right) { right.x = left.x; right.y = left.y; }
});

const equationsFor = (sketch: Sketch, fixed: Record<string, SketchEntity>, diagnostics: SketchSolverDiagnostic[]): Equation[] => {
  const equations: Equation[] = [];
  const constraint = (entry: SketchConstraint) => { if (!entry.enabled) return; const refs = entry.pointRefs ?? []; const first = entry.entityIds[0]; const second = entry.entityIds[1]; const invalid = () => diagnostics.push({ code: "SKETCH_CONSTRAINT_REFERENCE_MISSING", message: `Constraint ${entry.id} has incompatible references.`, constraintId: entry.id, severity: "error" });
    if (entry.type === "horizontal" || entry.type === "vertical") { if (!line(sketch.entities, first)) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const value = line(entities, first)!; return [entry.type === "horizontal" ? value.end.y - value.start.y : value.end.x - value.start.x]; } }); return; }
    if (entry.type === "coincident") { const a = refs[0], b = refs[1]; if (!a || !b || !point(sketch.entities, a) || !point(sketch.entities, b)) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const left = point(entities, a)!; const right = point(entities, b)!; return [left.x - right.x, left.y - right.y]; } }); return; }
    if (entry.type === "parallel" || entry.type === "perpendicular") { if (!line(sketch.entities, first) || !line(sketch.entities, second)) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const a = direction(line(entities, first)!); const b = direction(line(entities, second)!); if (length(a) < 1e-9 || length(b) < 1e-9) return [1e6]; return [entry.type === "parallel" ? cross(a, b) / (length(a) * length(b)) : dot(a, b) / (length(a) * length(b))]; } }); return; }
    if (entry.type === "concentric") { if (!circleLike(sketch.entities, first) || !circleLike(sketch.entities, second)) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const a = circleLike(entities, first)!; const b = circleLike(entities, second)!; return [a.center.x - b.center.x, a.center.y - b.center.y]; } }); return; }
    if (entry.type === "equal") { const leftLine = line(sketch.entities, first); const rightLine = line(sketch.entities, second); const leftCurve = circleLike(sketch.entities, first); const rightCurve = circleLike(sketch.entities, second); if ((!leftLine || !rightLine) && (!leftCurve || !rightCurve)) { diagnostics.push({ code: "SKETCH_CONSTRAINT_UNSUPPORTED_REFERENCE", message: `Equal constraint ${entry.id} requires two Lines or two Circle/Arc entities.`, constraintId: entry.id, severity: "error" }); return; } equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => leftLine && rightLine ? [length(direction(line(entities, first)!)) - length(direction(line(entities, second)!))] : [circleLike(entities, first)!.radius - circleLike(entities, second)!.radius] }); return; }
    if (entry.type === "tangent") { const l = line(sketch.entities, first) ?? line(sketch.entities, second); const curve = circleLike(sketch.entities, second) ?? circleLike(sketch.entities, first); const spline = bspline(sketch.entities, first) ?? bspline(sketch.entities, second); const externalNurbs = sketch.entities[first]?.type === "external-bspline" ? sketch.entities[first] : sketch.entities[second]?.type === "external-bspline" ? sketch.entities[second] : undefined;
      if (l && spline) { const ref = refs.find((candidate) => candidate.entityId === spline.id && (candidate.role === "start" || candidate.role === "end")); if (!ref || spline.closed) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const currentLine = line(entities, l.id)!; const currentSpline = bspline(entities, spline.id)!; const a = direction(currentLine); const b = bsplineEndpointDirection(currentSpline, ref.role as "start" | "end"); if (length(a) < 1e-9 || length(b) < 1e-9) return [1e6]; return [cross(a,b)/(length(a)*length(b))]; } }); return; }
      if (l && externalNurbs) { const ref=refs.find((candidate)=>candidate.entityId===externalNurbs.id&&(candidate.role==="curve"||candidate.role==="start"||candidate.role==="end"));const parameter=ref&&nurbsReferenceParameter(externalNurbs,ref);if(parameter===undefined)return invalid();const tangent=compiledExternalNurbs(externalNurbs).evaluateTangent(parameter);if(length(tangent)<1e-9)return invalid();equations.push({id:entry.id,kind:"constraint",evaluate:(entities)=>{const a=direction(line(entities,l.id)!);if(length(a)<1e-9)return[1e6];return[cross(a,tangent)/(length(a)*length(tangent))];}});return; }
      if (!l || !curve) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const currentLine = line(entities, l.id)!; const currentCircle = circleLike(entities, curve.id)!; const d = direction(currentLine); const denominator = length(d); if (denominator < 1e-9) return [1e6]; return [Math.abs(cross({ x: currentCircle.center.x - currentLine.start.x, y: currentCircle.center.y - currentLine.start.y }, d)) / denominator - currentCircle.radius]; } }); return; }
    if (entry.type === "midpoint") { const p = refs.find((ref) => sketch.entities[ref.entityId]?.type === "point"); const l = line(sketch.entities, first) ?? line(sketch.entities, second); if (!p || !l) return invalid(); equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const target = point(entities, p)!; const current = line(entities, l.id)!; return [target.x - (current.start.x + current.end.x) / 2, target.y - (current.start.y + current.end.y) / 2]; } }); return; }
    if (entry.type === "fixed") { const entity = fixed[first]; if (!entity || entity.type === "spline" || entity.type === "external-line" || entity.type === "external-circle" || entity.type === "external-arc" || entity.type === "external-bspline") return invalid(); const ref = refs[0];
      if (!ref && entity.type === "bspline") { equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => { const current = entities[first]; if (current?.type !== "bspline") return [1e6]; return current.fitPoints.flatMap((fitPoint, index) => [fitPoint.x - entity.fitPoints[index].x, fitPoint.y - entity.fitPoints[index].y]).concat(current.startTangent && current.endTangent && entity.startTangent && entity.endTangent ? [current.startTangent.x-entity.startTangent.x,current.startTangent.y-entity.startTangent.y,current.endTangent.x-entity.endTangent.x,current.endTangent.y-entity.endTangent.y] : []); } }); return; }
      const targets = ref ? [ref] : entity.type === "line" ? [{ entityId: first, role: "start" as const }, { entityId: first, role: "end" as const }] : entity.type === "circle" || entity.type === "arc" ? [{ entityId: first, role: "center" as const }] : [{ entityId: first, role: "position" as const }]; equations.push({ id: entry.id, kind: "constraint", evaluate: (entities) => targets.flatMap((target) => { const current = point(entities, target)!; const original = point(fixed, target)!; return [current.x - original.x, current.y - original.y]; }).concat((!ref && (entity.type === "circle" || entity.type === "arc")) ? [circleLike(entities, first)!.radius - (entity as typeof entity & { radius: number }).radius] : []) }); return; }
    diagnostics.push({ code: "SKETCH_CONSTRAINT_UNSUPPORTED", message: `Constraint ${entry.type} is not supported by Solver V1.`, constraintId: entry.id, severity: "warning" });
  };
  Object.values(sketch.constraints).forEach(constraint);
  Object.values(sketch.dimensions).forEach((dimension: SketchDimension) => { if (!dimension.driving) return; const refs = dimension.pointRefs ?? []; const first = dimension.entityIds[0]; const second = dimension.entityIds[1]; const invalid = () => diagnostics.push({ code: "SKETCH_DIMENSION_REFERENCE_MISSING", message: `Dimension ${dimension.id} has incompatible references.`, dimensionId: dimension.id, severity: "error" });
    if (["horizontalDistance", "verticalDistance", "distance"].includes(dimension.type)) { const a = refs[0], b = refs[1]; if (!a || !b || !point(sketch.entities, a) || !point(sketch.entities, b)) return invalid(); equations.push({ id: dimension.id, kind: "dimension", evaluate: (entities) => { const left = point(entities, a)!; const right = point(entities, b)!; const actual = dimension.type === "horizontalDistance" ? right.x - left.x : dimension.type === "verticalDistance" ? right.y - left.y : Math.hypot(right.x - left.x, right.y - left.y); return [actual - dimension.value]; } }); return; }
    if (dimension.type === "radius" || dimension.type === "diameter") { if (!circleLike(sketch.entities, first)) return invalid(); equations.push({ id: dimension.id, kind: "dimension", evaluate: (entities) => [circleLike(entities, first)!.radius * (dimension.type === "diameter" ? 2 : 1) - dimension.value] }); return; }
    if (dimension.type === "angle") { if (!line(sketch.entities, first) || !line(sketch.entities, second)) return invalid(); equations.push({ id: dimension.id, kind: "dimension", evaluate: (entities) => { const a = direction(line(entities, first)!); const b = direction(line(entities, second)!); return [Math.atan2(cross(a,b),dot(a,b)) - dimension.value * Math.PI / 180]; } }); return; }
  }); return equations;
};

export const solveSketch = (sketch: Sketch, options: SketchSolverOptions = {}): SketchSolveResult => {
  const settings = { ...DEFAULT_SKETCH_SOLVER_OPTIONS, ...options }; const entities = clone(sketch.entities); const initial = clone(sketch.entities); const diagnostics: SketchSolverDiagnostic[] = []; const variables = variablesFor(entities); const equations = equationsFor(sketch, initial, diagnostics);
  const invalidRadius = Object.values(entities).find((entity) => (entity.type === "circle" || entity.type === "arc") && (!Number.isFinite(entity.radius) || entity.radius <= settings.residualTolerance));
  if (invalidRadius) diagnostics.push({ code: "SKETCH_INVALID_RADIUS", message: `Curve ${invalidRadius.id} has a non-positive or non-finite radius.`, severity: "error" });
  if (diagnostics.some((entry) => entry.severity === "error")) return { status: "failed", entities, degreesOfFreedom: variables.length, residual: Infinity, iterations: 0, diagnostics, conflictingConstraintIds: [], conflictingDimensionIds: [] };
  const residuals = () => equations.flatMap((equation) => equation.evaluate(entities)); let current = residuals(); let iterations = 0;
  for (; iterations < settings.maxIterations; iterations += 1) { if (current.some((value) => !Number.isFinite(value))) { diagnostics.push({ code: "SOLVER_NON_FINITE", message: "Solver produced a non-finite residual.", severity: "error" }); break; } const epsilon = 1e-5; const jacobian = current.map(() => Array(variables.length).fill(0)); for (let column = 0; column < variables.length; column += 1) { const old = get(entities, variables[column]); set(entities, variables[column], old + epsilon); const shifted = residuals(); set(entities, variables[column], old); for (let row = 0; row < current.length; row += 1) jacobian[row][column] = (shifted[row] - current[row]) / epsilon; } const normal = Array.from({ length: variables.length }, () => Array(variables.length).fill(0)); const gradient = Array(variables.length).fill(0); for (let row = 0; row < current.length; row += 1) for (let column = 0; column < variables.length; column += 1) { gradient[column] += jacobian[row][column] * current[row]; for (let other = 0; other < variables.length; other += 1) normal[column][other] += jacobian[row][column] * jacobian[row][other]; } for (let index = 0; index < variables.length; index += 1) normal[index][index] += settings.damping; const delta = solveLinear(normal, gradient.map((value) => -value)); if (!delta) break; delta.forEach((value, index) => set(entities, variables[index], get(entities, variables[index]) + value)); current = residuals(); if (norm(delta) <= settings.parameterTolerance || norm(current) <= settings.residualTolerance) break; }
  const residual = norm(current); const finalJacobian = current.map(() => Array(variables.length).fill(0)); const epsilon = 1e-5; for (let column = 0; column < variables.length; column += 1) { const old = get(entities, variables[column]); set(entities, variables[column], old + epsilon); const shifted = residuals(); set(entities, variables[column], old); for (let row = 0; row < current.length; row += 1) finalJacobian[row][column] = (shifted[row] - current[row]) / epsilon; }
  const degreesOfFreedom = Math.max(0, variables.length - rank(finalJacobian)); const involved = residual > settings.residualTolerance ? equations : []; const conflictingConstraintIds = involved.filter((entry) => entry.kind === "constraint").map((entry) => entry.id); const conflictingDimensionIds = involved.filter((entry) => entry.kind === "dimension").map((entry) => entry.id); const invalidSolvedRadius = Object.values(entities).find((entity) => (entity.type === "circle" || entity.type === "arc") && (!Number.isFinite(entity.radius) || entity.radius <= settings.residualTolerance)); if (!Number.isFinite(residual) || invalidSolvedRadius) return { status: "failed", entities: initial, degreesOfFreedom, residual, iterations, diagnostics: [...diagnostics, { code: invalidSolvedRadius ? "SKETCH_INVALID_RADIUS" : "SOLVER_NON_FINITE", message: invalidSolvedRadius ? `Curve ${invalidSolvedRadius.id} solved to an invalid radius.` : "Solver produced a non-finite result.", severity: "error" }], conflictingConstraintIds, conflictingDimensionIds };
  if (residual > settings.residualTolerance) return { status: "conflicting", entities: initial, degreesOfFreedom, residual, iterations, diagnostics: [...diagnostics, { code: "SKETCH_CONFLICT", message: "Constraints or driving dimensions conflict.", severity: "error" }], conflictingConstraintIds, conflictingDimensionIds };
  normalizeCoincidentPoints(sketch, entities);
  const status = degreesOfFreedom === 0 ? "fully-constrained" : "under-constrained";
  return { status, entities, degreesOfFreedom, residual, iterations, diagnostics, conflictingConstraintIds, conflictingDimensionIds };
};
