import type { Vec2 } from "../../cad/CadTypes.ts";
import type { SketchArc, SketchCircle, SketchEntity, SketchLine } from "../SketchEntity.ts";
import type { SketchIntersection } from "./SketchOperationTypes.ts";

const EPS = 1e-6;
const sub=(a:Vec2,b:Vec2):Vec2=>({x:a.x-b.x,y:a.y-b.y}); const add=(a:Vec2,b:Vec2):Vec2=>({x:a.x+b.x,y:a.y+b.y}); const mul=(a:Vec2,t:number):Vec2=>({x:a.x*t,y:a.y*t}); const dot=(a:Vec2,b:Vec2)=>a.x*b.x+a.y*b.y; const cross=(a:Vec2,b:Vec2)=>a.x*b.y-a.y*b.x; const norm=(a:Vec2)=>Math.hypot(a.x,a.y);
const angle=(c:Vec2,p:Vec2)=>Math.atan2(p.y-c.y,p.x-c.x);
const onArc=(arc:SketchArc,a:number)=>{const span=((arc.endAngle-arc.startAngle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);const at=((a-arc.startAngle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);return at<=span+EPS;};
const inCurve=(entity:SketchEntity,p:Vec2):number|undefined=>{if(entity.type==="line"){const d=sub(entity.end,entity.start),l=dot(d,d);if(l<EPS)return;const t=dot(sub(p,entity.start),d)/l;return t>=-EPS&&t<=1+EPS?t:undefined;}if(entity.type==="circle")return angle(entity.center,p);if(entity.type==="arc"){const a=angle(entity.center,p);return onArc(entity,a)?a:undefined;}};
const circles=(a:SketchCircle|SketchArc,b:SketchCircle|SketchArc):Vec2[]=>{const delta=sub(b.center,a.center),d=norm(delta);if(d<EPS||d>a.radius+b.radius+EPS||d<Math.abs(a.radius-b.radius)-EPS)return[];const x=(a.radius*a.radius-b.radius*b.radius+d*d)/(2*d),h=Math.sqrt(Math.max(0,a.radius*a.radius-x*x)),u=mul(delta,1/d),base=add(a.center,mul(u,x)),perp={x:-u.y,y:u.x};return h<=EPS?[base]:[add(base,mul(perp,h)),add(base,mul(perp,-h))];};
const lineCircle=(line:SketchLine,curve:SketchCircle|SketchArc):Vec2[]=>{const d=sub(line.end,line.start),f=sub(line.start,curve.center),q=dot(d,d);if(q<EPS)return[];const disc=dot(f,d)**2-q*(dot(f,f)-curve.radius**2);if(disc<-EPS)return[];const root=Math.sqrt(Math.max(0,disc));return [(-dot(f,d)-root)/q,(-dot(f,d)+root)/q].filter((t,i,a)=>i===0||Math.abs(t-a[0])>EPS).map(t=>add(line.start,mul(d,t)));};
/** Exact analytic intersections; values are local sketch mm coordinates. */
export const intersectSketchEntities2D=(a:SketchEntity,b:SketchEntity):SketchIntersection[]=>{let points:Vec2[]=[];if(a.type==="line"&&b.type==="line"){const r=sub(a.end,a.start),s=sub(b.end,b.start),den=cross(r,s);if(Math.abs(den)>EPS){const t=cross(sub(b.start,a.start),s)/den,u=cross(sub(b.start,a.start),r)/den;if(t>=-EPS&&t<=1+EPS&&u>=-EPS&&u<=1+EPS)points=[add(a.start,mul(r,t))];}}else if(a.type==="line"&&(b.type==="circle"||b.type==="arc"))points=lineCircle(a,b);else if(b.type==="line"&&(a.type==="circle"||a.type==="arc"))points=lineCircle(b,a);else if((a.type==="circle"||a.type==="arc")&&(b.type==="circle"||b.type==="arc"))points=circles(a,b);return points.flatMap(point=>{const pa=inCurve(a,point),pb=inCurve(b,point);return pa===undefined||pb===undefined?[]:[{point,entityAParameter:pa,entityBParameter:pb,tangent:points.length===1}];}).filter((item,index,all)=>all.findIndex(other=>norm(sub(item.point,other.point))<=EPS)===index);};
