import type { Vec2 } from "../../cad/CadTypes.ts";
import type { Sketch, } from "../Sketch.ts";
import type { SketchArc, SketchEntity } from "../SketchEntity.ts";
import { intersectSketchEntities2D } from "./Intersection2D.ts";
import { SketchOperationError, type SketchOperationResult } from "./SketchOperationTypes.ts";

const distance=(a:Vec2,b:Vec2)=>Math.hypot(a.x-b.x,a.y-b.y);
const clone=<T,>(v:T):T=>structuredClone(v);
const cleanup=(sketch:Sketch,entities:Record<string,SketchEntity>,removed:string[]):Pick<SketchOperationResult,"orphanConstraintIds"|"orphanDimensionIds">=>({orphanConstraintIds:Object.values(sketch.constraints).filter(c=>c.entityIds.some(id=>removed.includes(id))||c.pointRefs?.some(p=>removed.includes(p.entityId))).map(c=>c.id),orphanDimensionIds:Object.values(sketch.dimensions).filter(d=>d.entityIds.some(id=>removed.includes(id))||d.pointRefs?.some(p=>removed.includes(p.entityId))).map(d=>d.id)});
/** Trim preserves the original id for the piece nearest its original start. */
export const trimSketchEntity=(sketch:Sketch,id:string,click:Vec2):SketchOperationResult=>{const source=sketch.entities[id];if(!source||source.type==="spline"||source.type==="bspline"||source.type==="point"||source.type==="external-line"||source.type==="external-circle"||source.type==="external-arc"||source.type==="external-bspline")throw new SketchOperationError("SKETCH_TRIM_UNSUPPORTED_ENTITY",`Trim does not support ${source?.type??"missing"}.`);const hits=Object.values(sketch.entities).filter(e=>e.id!==id).flatMap(e=>intersectSketchEntities2D(source,e).map(x=>x.entityAParameter)).sort((a,b)=>a-b);if(!hits.length)throw new SketchOperationError("SKETCH_TRIM_NO_INTERSECTION","No exact intersection is available for trim.");const entities=clone(sketch.entities),order=[...sketch.entityOrder],created:string[]=[];if(source.type==="line"){const d={x:source.end.x-source.start.x,y:source.end.y-source.start.y},t=Math.max(0,Math.min(1,((click.x-source.start.x)*d.x+(click.y-source.start.y)*d.y)/(d.x*d.x+d.y*d.y)));const left=hits.filter(x=>x<t),right=hits.filter(x=>x>t),a=left.at(-1),b=right[0];if(a!==undefined&&b!==undefined){const nextId=`${id}-trim-1`;entities[id]={...source,end:{x:source.start.x+d.x*a,y:source.start.y+d.y*a}};entities[nextId]={...source,id:nextId,start:{x:source.start.x+d.x*b,y:source.start.y+d.y*b}};order.splice(order.indexOf(id)+1,0,nextId);created.push(nextId);}else{const cut=a??b!,keepStart=a===undefined;entities[id]=keepStart?{...source,end:{x:source.start.x+d.x*cut,y:source.start.y+d.y*cut}}:{...source,start:{x:source.start.x+d.x*cut,y:source.start.y+d.y*cut}};}}else{const curve=source as SketchArc|Extract<SketchEntity,{type:"circle"}>,a=Math.atan2(click.y-curve.center.y,click.x-curve.center.x),angles=hits.map(t=>typeof t==="number"?t:0);if(source.type==="circle"&&angles.length<2)throw new SketchOperationError("SKETCH_TRIM_NO_INTERSECTION","Circle trim requires two intersections.");const start=angles.reduce((best,v)=>distance({x:Math.cos(best),y:Math.sin(best)},{x:Math.cos(a),y:Math.sin(a)})<distance({x:Math.cos(v),y:Math.sin(v)},{x:Math.cos(a),y:Math.sin(a)})?best:v);const end=angles.find(v=>v!==start)??start;entities[id]={id,type:"arc",center:clone(curve.center),radius:curve.radius,startAngle:end,endAngle:start,construction:curve.construction};}const removed:string[]=[];return{entities,entityOrder:order,removedEntityIds:removed,createdEntityIds:created,...cleanup(sketch,entities,removed)};};
