import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument } from "../core/cad/CadDocument.ts";
import { createCadAssetStore } from "../core/cad/CadAssets.ts";
import { importStepIntoDocument } from "../core/cad/StepImport.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState } from "../core/evaluation/CadRuntimeState.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef } from "../core/topology/TopologyResolver.ts";
import { createAssemblyDocument } from "../core/assembly/AssemblyDocument.ts";
import { addMate, insertComponent } from "../core/assembly/AssemblyOperations.ts";
import { createPartDefinitionFromCadDocument, createPartDefinitionStore, addPartDefinition } from "../core/assembly/PartDefinitions.ts";
import { ExactAssemblyGeometryProvider, PartDefinitionRuntimeCache } from "../core/assembly/AssemblyGeometry.ts";
import { solveAssembly } from "../core/assembly/AssemblySolver.ts";
import { deserializeAssemblyProjectBundle, serializeAssemblyProjectBundle } from "../core/assembly/AssemblyPersistence.ts";

const wasm = new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm", import.meta.url); let kernel;
const close=(a,b,t=1e-5)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);
const rect=(id,w=100,h=60)=>({id,name:id,plane:{type:"XY",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:w,y:0},construction:false},b:{id:"b",type:"line",start:{x:w,y:0},end:{x:w,y:h},construction:false},c:{id:"c",type:"line",start:{x:w,y:h},end:{x:0,y:h},construction:false},d:{id:"d",type:"line",start:{x:0,y:h},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}});
const boxDocument=()=>createCadDocument({id:"box",name:"Box",sketches:{S:rect("S")},features:{E:{id:"E",name:"E",type:"extrude",bodyId:"Body01",sketchId:"S",distance:20,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["E"],bodies:{Body01:{id:"Body01",name:"Box",backend:"brep",visible:true}},activeBodyId:"Body01"});
const cylinderDocument=()=>createCadDocument({id:"cylinder",name:"Cylinder",sketches:{S:{id:"S",name:"S",plane:{type:"XY",offset:0},entities:{circle:{id:"circle",type:"circle",center:{x:0,y:0},radius:10,construction:false}},entityOrder:["circle"],constraints:{},dimensions:{}}},features:{E:{id:"E",name:"E",type:"extrude",bodyId:"Body01",sketchId:"S",distance:100,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["E"],bodies:{Body01:{id:"Body01",name:"Cylinder",backend:"brep",visible:true}},activeBodyId:"Body01"});
const context=(document,runtime,state,assets)=>({document,runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles,assets});
const identity=()=>({translationMm:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0,w:1}});
const component=(id,definitionId,p=identity(),grounded=false)=>({id,name:id,definitionId,nominalPlacement:p,grounded,visible:true});
const placement=(x,y,z)=>({translationMm:{x,y,z},rotation:{x:0,y:0,z:0,w:1}});
const assemblyRef=(instanceId,bodyId,topologyRef)=>({instanceId,bodyId,topologyRef});

before(async()=>{kernel=new OcctKernel({wasm});await kernel.init();}); after(async()=>kernel?.dispose());

const captureBoxRefs=async(cache,definitionId)=>{const entry=await cache.get(definitionId),shape=entry.runtime.bodyShapes.get("Body01"),faces=await kernel.getFaces(shape),top=faces.find((f)=>(f.normal?.z??0)>.999),bottom=faces.find((f)=>(f.normal?.z??0)<-.999);assert.ok(top&&bottom);return{top:await capturePersistentTopologyRef("E",top.topology,entry.runtime,kernel),bottom:await capturePersistentTopologyRef("E",bottom.topology,entry.runtime,kernel)};};
const captureCylinderRef=async(cache,definitionId)=>{const entry=await cache.get(definitionId),shape=entry.runtime.bodyShapes.get("Body01"),face=(await kernel.getFaces(shape)).find((f)=>f.surfaceType==="cylinder");assert.ok(face);assert.ok(face.cylindricalFrame,"Exact OCCT cylinder frame must be exposed through KernelFaceInfo.");close(face.cylindricalFrame.radiusMm,10);return capturePersistentTopologyRef("E",face.topology,entry.runtime,kernel);};

test("P2-M8 exact native planar Coincident uses Part-local persistent refs and reports DOF 3",async()=>{const definition=createPartDefinitionFromCadDocument("BoxDef","Box",boxDocument(),createCadAssetStore()),store=createPartDefinitionStore([definition]);let assembly=createAssemblyDocument({id:"a",name:"A",updatedAt:0});assembly=insertComponent(assembly,component("Base","BoxDef",identity(),true));assembly=insertComponent(assembly,component("Bracket","BoxDef",placement(30,20,100)));const cache=new PartDefinitionRuntimeCache(store,kernel),refs=await captureBoxRefs(cache,"BoxDef");assembly=addMate(assembly,{id:"M",name:"Coincident",type:"coincident",enabled:true,a:assemblyRef("Base","Body01",refs.top),b:assemblyRef("Bracket","Body01",refs.bottom),alignment:"opposite"});const result=await solveAssembly(assembly,new ExactAssemblyGeometryProvider(assembly,cache,kernel));assert.equal(result.success,true);assert.equal(result.dof,3);close(result.placements.get("Bracket").translationMm.z,20);assert.equal(cache.size,1);await cache.dispose();});

test("P2-M8 exact cylindrical Concentric solves axis offset and reports DOF 2",async()=>{const definition=createPartDefinitionFromCadDocument("CylDef","Cylinder",cylinderDocument(),createCadAssetStore()),store=createPartDefinitionStore([definition]);let assembly=createAssemblyDocument({id:"c",name:"C",updatedAt:0});assembly=insertComponent(assembly,component("Shaft","CylDef",identity(),true));assembly=insertComponent(assembly,component("Collar","CylDef",placement(30,20,25)));const cache=new PartDefinitionRuntimeCache(store,kernel),cyl=await captureCylinderRef(cache,"CylDef");assembly=addMate(assembly,{id:"C",name:"Concentric",type:"concentric",enabled:true,a:assemblyRef("Shaft","Body01",cyl),b:assemblyRef("Collar","Body01",cyl)});const result=await solveAssembly(assembly,new ExactAssemblyGeometryProvider(assembly,cache,kernel));assert.equal(result.success,true);assert.equal(result.dof,2);close(result.placements.get("Collar").translationMm.x,0);close(result.placements.get("Collar").translationMm.y,0);close(result.placements.get("Collar").translationMm.z,25);await cache.dispose();});

test("P2-M8 same PartDefinition rebuilds once for multiple Component instances",async()=>{const definition=createPartDefinitionFromCadDocument("BoxDef","Box",boxDocument(),createCadAssetStore()),store=createPartDefinitionStore([definition]),cache=new PartDefinitionRuntimeCache(store,kernel);let assembly=createAssemblyDocument({id:"shared",name:"Shared",updatedAt:0});for(let i=0;i<10;i++)assembly=insertComponent(assembly,component(`I${i}`,"BoxDef",placement(i*120,0,0),i===0));const provider=new ExactAssemblyGeometryProvider(assembly,cache,kernel);const refs=await captureBoxRefs(cache,"BoxDef");await provider.resolve(assemblyRef("I1","Body01",refs.top));await provider.resolve(assemblyRef("I9","Body01",refs.bottom));assert.equal(cache.size,1);const result=await solveAssembly(assembly,provider);assert.equal(result.success,true);assert.equal(result.dof,54);await cache.dispose();});

test("P2-M8 STEP-backed PartDefinition mates to Native Part and survives save/kernel restart",async()=>{const native=boxDocument(),nativeRuntime=createCadRuntimeState();assert.equal((await rebuildDocument(context(native,nativeRuntime,createRebuildRuntimeState()),{full:true})).success,true);const step=await kernel.exportStep([nativeRuntime.bodyShapes.get("Body01")]);const imported=await importStepIntoDocument(createCadDocument({id:"step-part",name:"STEP Part"}),createCadAssetStore(),kernel,"box.step",step);let store=createPartDefinitionStore();store=addPartDefinition(store,createPartDefinitionFromCadDocument("Native","Native Box",native,createCadAssetStore()));store=addPartDefinition(store,createPartDefinitionFromCadDocument("Step","STEP Box",imported.document,imported.assets));let assembly=createAssemblyDocument({id:"step-assembly",name:"STEP Assembly",updatedAt:0});assembly=insertComponent(assembly,component("Base","Native",identity(),true));assembly=insertComponent(assembly,component("Imported","Step",placement(0,0,80)));let cache=new PartDefinitionRuntimeCache(store,kernel);const nativeRefs=await captureBoxRefs(cache,"Native"),stepEntry=await cache.get("Step"),stepShape=stepEntry.runtime.bodyShapes.get("ImportedBody1"),stepBottom=(await kernel.getFaces(stepShape)).find((f)=>(f.normal?.z??0)<-.999);assert.ok(stepBottom);const stepBottomRef=await capturePersistentTopologyRef("ImportedStep1",stepBottom.topology,stepEntry.runtime,kernel);assembly=addMate(assembly,{id:"STEP-Mate",name:"STEP Coincident",type:"coincident",enabled:true,a:assemblyRef("Base","Body01",nativeRefs.top),b:assemblyRef("Imported","ImportedBody1",stepBottomRef),alignment:"opposite"});let result=await solveAssembly(assembly,new ExactAssemblyGeometryProvider(assembly,cache,kernel));assert.equal(result.success,true);close(result.placements.get("Imported").translationMm.z,20);const bundle=serializeAssemblyProjectBundle(assembly,store);assert.equal(JSON.stringify(bundle).includes("runtimeShape"),false);await cache.dispose();await disposeCadRuntimeState(nativeRuntime,kernel);await kernel.dispose();
  const restarted=new OcctKernel({wasm});await restarted.init();try{const loaded=deserializeAssemblyProjectBundle(bundle);cache=new PartDefinitionRuntimeCache(loaded.definitions,restarted);result=await solveAssembly(loaded.assembly,new ExactAssemblyGeometryProvider(loaded.assembly,cache,restarted));assert.equal(result.success,true);assert.equal(result.dof,3);close(result.placements.get("Imported").translationMm.z,20);await cache.dispose();}finally{await restarted.dispose();kernel=new OcctKernel({wasm});await kernel.init();}
});

test("P2-M8 STEP cylindrical Concentric Mate reference survives independent kernel restart",async()=>{const native=cylinderDocument(),sourceRuntime=createCadRuntimeState();assert.equal((await rebuildDocument(context(native,sourceRuntime,createRebuildRuntimeState()),{full:true})).success,true);const imported=await importStepIntoDocument(createCadDocument({id:"step-cylinder",name:"STEP Cylinder"}),createCadAssetStore(),kernel,"cylinder.step",await kernel.exportStep([sourceRuntime.bodyShapes.get("Body01")]));let store=createPartDefinitionStore();store=addPartDefinition(store,createPartDefinitionFromCadDocument("NativeCylinder","Native Cylinder",native,createCadAssetStore()));store=addPartDefinition(store,createPartDefinitionFromCadDocument("StepCylinder","STEP Cylinder",imported.document,imported.assets));let assembly=createAssemblyDocument({id:"cylinder-assembly",name:"Cylinder Assembly",updatedAt:0});assembly=insertComponent(assembly,component("Shaft","NativeCylinder",identity(),true));assembly=insertComponent(assembly,component("Collar","StepCylinder",placement(30,20,25)));const cache=new PartDefinitionRuntimeCache(store,kernel),nativeRef=await captureCylinderRef(cache,"NativeCylinder"),stepEntry=await cache.get("StepCylinder"),stepFace=(await kernel.getFaces(stepEntry.runtime.bodyShapes.get("ImportedBody1"))).find((f)=>f.surfaceType==="cylinder");assert.ok(stepFace?.cylindricalFrame);const stepRef=await capturePersistentTopologyRef("ImportedStep1",stepFace.topology,stepEntry.runtime,kernel);assembly=addMate(assembly,{id:"ConcentricSTEP",name:"ConcentricSTEP",type:"concentric",enabled:true,a:assemblyRef("Shaft","Body01",nativeRef),b:assemblyRef("Collar","ImportedBody1",stepRef)});let result=await solveAssembly(assembly,new ExactAssemblyGeometryProvider(assembly,cache,kernel));assert.equal(result.success,true);assert.equal(result.dof,2);close(result.placements.get("Collar").translationMm.x,0);close(result.placements.get("Collar").translationMm.y,0);const bundle=serializeAssemblyProjectBundle(assembly,store);await cache.dispose();await disposeCadRuntimeState(sourceRuntime,kernel);const isolated=new OcctKernel({wasm});await isolated.init();try{const loaded=deserializeAssemblyProjectBundle(bundle),restartedCache=new PartDefinitionRuntimeCache(loaded.definitions,isolated);result=await solveAssembly(loaded.assembly,new ExactAssemblyGeometryProvider(loaded.assembly,restartedCache,isolated));assert.equal(result.success,true);assert.equal(result.dof,2);close(result.placements.get("Collar").translationMm.x,0);close(result.placements.get("Collar").translationMm.y,0);await restartedCache.dispose();}finally{await isolated.dispose();}});

test("P2-M8 shared-definition instance lifecycle never duplicates owned Part B-Rep shapes",async()=>{
  const definition=createPartDefinitionFromCadDocument("SharedLifecycle","Shared Lifecycle Box",boxDocument(),createCadAssetStore()),store=createPartDefinitionStore([definition]);
  const baseline=kernel.getRuntimeDiagnostics(); const cache=new PartDefinitionRuntimeCache(store,kernel); await cache.get("SharedLifecycle"); const warm=kernel.getRuntimeDiagnostics();
  assert.equal(warm.ownedShapes,baseline.ownedShapes+1);
  let assembly=createAssemblyDocument({id:"lifecycle",name:"Lifecycle",updatedAt:0});
  for(let i=0;i<50;i++) assembly=insertComponent(assembly,component(`Instance${i}`,"SharedLifecycle",placement(i*2,0,0),i===0));
  const result=await solveAssembly(assembly,new ExactAssemblyGeometryProvider(assembly,cache,kernel)); assert.equal(result.success,true); assert.equal(cache.size,1); assert.equal(kernel.getRuntimeDiagnostics().ownedShapes,warm.ownedShapes);
  await cache.dispose(); assert.deepEqual(kernel.getRuntimeDiagnostics(),baseline);
});
