import assert from "node:assert/strict";
import test from "node:test";
import { createCadDocument } from "../core/cad/CadDocument.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState } from "../core/evaluation/CadRuntimeState.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { capturePersistentTopologyRef } from "../core/topology/TopologyResolver.ts";
import { getPlanarFaceFrame, faceLocalToWorld, worldToFaceLocal } from "../core/topology/PlanarFaceFrame.ts";
import { datumPlaneFrame, originDatumAxis } from "../core/reference/DatumGeometry.ts";

const baseSketch={id:"Base",name:"Base",plane:{type:"XY",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:100,y:0},construction:false},b:{id:"b",type:"line",start:{x:100,y:0},end:{x:100,y:60},construction:false},c:{id:"c",type:"line",start:{x:100,y:60},end:{x:0,y:60},construction:false},d:{id:"d",type:"line",start:{x:0,y:60},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}};
const circle=(id,plane,radius=10)=>({id,name:id,plane,entities:{circle:{id:"circle",type:"circle",center:{x:0,y:0},radius,construction:false}},entityOrder:["circle"],constraints:{},dimensions:{}});
const context=(document,kernel,runtime,state)=>({document,kernel,runtime,rebuildRuntime:state,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});
test("face attachment resolves a persistent top face to local mm coordinates for extrude and pocket",async()=>{const kernel=new OcctKernel({wasm:new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm",import.meta.url)}),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();try{await kernel.init();const doc=createCadDocument({id:"F",name:"F",sketches:{Base:baseSketch},features:{BaseExtrude:{id:"BaseExtrude",name:"Base",type:"extrude",sketchId:"Base",distance:20,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["BaseExtrude"]});assert.equal((await rebuildDocument(context(doc,kernel,runtime,state),{full:true})).success,true);const shape=runtime.featureShapes.get("BaseExtrude"),top=(await kernel.getFaces(shape)).find(face=>face.surfaceType==="plane"&&(face.normal?.z??0)>.99);const persistent=await capturePersistentTopologyRef("BaseExtrude",top.topology,runtime,kernel),frame=getPlanarFaceFrame(top),round=worldToFaceLocal(frame,faceLocalToWorld(frame,{x:12,y:-7}));assert.ok(Math.abs(round.x-12)<1e-8&&Math.abs(round.y+7)<1e-8);doc.sketches.FaceCircle=circle("FaceCircle",{type:"face",face:{sourceFeatureId:"BaseExtrude",persistent}});doc.features.FacePocket={id:"FacePocket",name:"FacePocket",type:"pocket",sketchId:"FaceCircle",targetFeatureId:"BaseExtrude",depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["BaseExtrude"]};doc.featureOrder.push("FacePocket");const rebuilt=await rebuildDocument(context(doc,kernel,runtime,state),{full:true});assert.equal(rebuilt.success,true,JSON.stringify(rebuilt.errors));assert.ok((await kernel.getShapeProperties(runtime.featureShapes.get("FacePocket"))).volumeMm3<120000);}finally{await disposeCadRuntimeState(runtime,kernel);await kernel.dispose();}});
test("datum principal offsets and origin axes preserve local sketch coordinates",()=>{const xy=datumPlaneFrame({id:"D",name:"D",base:"XY",offsetMm:50});assert.deepEqual(xy.origin,{x:0,y:0,z:50});const xz=datumPlaneFrame({id:"D",name:"D",base:"XZ",offsetMm:5});assert.deepEqual(xz.normal,{x:0,y:-1,z:0});assert.deepEqual(originDatumAxis("Z","Z").direction,{x:0,y:0,z:1});});
test("right face attachment preserves 2D local geometry and evaluates positive extrude plus inward pocket",async()=>{const kernel=new OcctKernel({wasm:new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm",import.meta.url)}),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();try{await kernel.init();const doc=createCadDocument({id:"R",name:"R",sketches:{Base:baseSketch},features:{BaseExtrude:{id:"BaseExtrude",name:"Base",type:"extrude",sketchId:"Base",distance:20,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["BaseExtrude"]});assert.equal((await rebuildDocument(context(doc,kernel,runtime,state),{full:true})).success,true);const right=(await kernel.getFaces(runtime.featureShapes.get("BaseExtrude"))).find(face=>(face.normal?.x??0)>.99),ref=await capturePersistentTopologyRef("BaseExtrude",right.topology,runtime,kernel),frame=getPlanarFaceFrame(right),world=faceLocalToWorld(frame,{x:0,y:0});assert.ok(Math.abs(world.x-100)<1e-6);doc.sketches.RightRect={id:"RightRect",name:"RightRect",plane:{type:"face",face:{sourceFeatureId:"BaseExtrude",persistent:ref}},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:20,y:0},construction:false},b:{id:"b",type:"line",start:{x:20,y:0},end:{x:20,y:10},construction:false},c:{id:"c",type:"line",start:{x:20,y:10},end:{x:0,y:10},construction:false},d:{id:"d",type:"line",start:{x:0,y:10},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}};doc.features.RightExtrude={id:"RightExtrude",name:"RightExtrude",type:"extrude",sketchId:"RightRect",distance:10,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]};doc.featureOrder.push("RightExtrude");const rightBuild=await rebuildDocument(context(doc,kernel,runtime,state),{full:true});assert.equal(rightBuild.success,true,JSON.stringify(rightBuild.errors));assert.ok(Math.abs((await kernel.getShapeProperties(runtime.featureShapes.get("RightExtrude"))).boundingBox.max.x-110)<1e-5);doc.sketches.RightCircle=circle("RightCircle",{type:"face",face:{sourceFeatureId:"BaseExtrude",persistent:ref}},5);doc.features.RightPocket={id:"RightPocket",name:"RightPocket",type:"pocket",sketchId:"RightCircle",targetFeatureId:"BaseExtrude",depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["BaseExtrude"]};doc.featureOrder.push("RightPocket");const pocketBuild=await rebuildDocument(context(doc,kernel,runtime,state),{full:true});assert.equal(pocketBuild.success,true,JSON.stringify(pocketBuild.errors));assert.ok((await kernel.getShapeProperties(runtime.featureShapes.get("RightPocket"))).volumeMm3<120000);}finally{await disposeCadRuntimeState(runtime,kernel);await kernel.dispose();}});
