import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument, toSerializableCadDocument } from "../core/cad/CadDocument.ts";
import { deserializeCadDocument } from "../core/cad/CadDocumentPersistence.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState, getRuntimeFeatureShape } from "../core/evaluation/CadRuntimeState.ts";
import { countersinkDepthMm } from "../core/evaluation/HoleEvaluator.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef } from "../core/topology/TopologyResolver.ts";
import { canRedoCadHistory, canUndoCadHistory, commitCadHistory, createCadHistory, currentCadDocument, redoCadHistory, undoCadHistory } from "../core/history/CadHistory.ts";
import { commitCadHistoryEdit, redoCadHistoryRebuild, undoCadHistoryRebuild } from "../core/history/CadHistoryRebuild.ts";

const wasm = new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm", import.meta.url); let kernel;
const close = (actual, expected, tolerance = .25) => assert.ok(Math.abs(actual - expected) <= tolerance, `${actual} != ${expected}`);
const rect = (id,w,h) => ({id,name:id,plane:{type:"XY",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:w,y:0},construction:false},b:{id:"b",type:"line",start:{x:w,y:0},end:{x:w,y:h},construction:false},c:{id:"c",type:"line",start:{x:w,y:h},end:{x:0,y:h},construction:false},d:{id:"d",type:"line",start:{x:0,y:h},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}});
const document = (height=20) => createCadDocument({id:"m5",name:"Mechanical",sketches:{Base:rect("Base",100,60)},features:{Base:{id:"Base",name:"Base",type:"extrude",sketchId:"Base",distance:height,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["Base"]});
const ctx=(doc,runtime,state)=>({document:doc,runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});
const rebuild=async(doc,runtime,state,request={full:true})=>{const result=await rebuildDocument(ctx(doc,runtime,state),request);assert.equal(result.success,true,JSON.stringify(result.errors));return result;};
const top=async(shape)=>(await kernel.getFaces(shape)).find(face=>face.normal?.z>.999);

before(async()=>{kernel=new OcctKernel({wasm});await kernel.init();}); after(async()=>kernel?.dispose());

test("P2-M5 exact Counterbore, Countersink and linear pattern retain a simple Hole contract",async()=>{
 const doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const ref=await capturePersistentTopologyRef("Base",(await top(runtime.featureShapes.get("Base"))).topology,runtime,kernel);
 doc.features.Counterbore={id:"Counterbore",name:"Counterbore",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},style:{type:"counterbore",diameterMm:20,depthMm:5},enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Counterbore");await rebuild(doc,runtime,state);close((await kernel.getShapeProperties(runtime.featureShapes.get("Counterbore"))).volumeMm3,120000-875*Math.PI);
 doc.features.Pattern={id:"Pattern",name:"Pattern",type:"linearPattern",targetFeatureId:"Base",seedFeatureIds:["Counterbore"],direction:"X",count:4,spacingMm:20,symmetric:true,enabled:true,state:"clean",dependencies:["Base","Counterbore"]};doc.featureOrder.push("Pattern");await rebuild(doc,runtime,state);close((await kernel.getShapeProperties(runtime.featureShapes.get("Pattern"))).volumeMm3,120000-4*875*Math.PI);
 delete doc.features.Pattern;doc.featureOrder.pop();doc.features.Countersink={...doc.features.Counterbore,id:"Countersink",name:"Countersink",style:{type:"countersink",diameterMm:20,includedAngleDeg:90}};delete doc.features.Counterbore;doc.featureOrder[1]="Countersink";await rebuild(doc,runtime,state);close(countersinkDepthMm(10,20,90),5,.000001);close((await kernel.getShapeProperties(runtime.featureShapes.get("Countersink"))).volumeMm3,120000-2000*Math.PI/3);
 assert.equal(/runtimeShapeId|shape-\d|face-\d/.test(JSON.stringify(toSerializableCadDocument(doc))),false);await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 Counterbore cuts inward from a right planar face and invalid style preserves last good",async()=>{
 const doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const right=(await kernel.getFaces(runtime.featureShapes.get("Base"))).find(face=>face.normal?.x>.999);const ref=await capturePersistentTopologyRef("Base",right.topology,runtime,kernel);
 doc.features.Hole={id:"Hole",name:"Hole",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},style:{type:"counterbore",diameterMm:20,depthMm:5},enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Hole");await rebuild(doc,runtime,state);assert.ok((await kernel.getShapeProperties(runtime.featureShapes.get("Hole"))).volumeMm3<120000);
 doc.features.Hole.style={type:"countersink",diameterMm:9,includedAngleDeg:90};const failed=await rebuildDocument(ctx(doc,runtime,state),{changedFeatureIds:["Hole"]});assert.equal(failed.success,false);assert.ok(runtime.featureShapes.get("Hole"));await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 single-line Rib produces a fused exact solid, parameter rebuild, and downstream Fillet",async()=>{
 const doc=document(10),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);doc.sketches.RibSketch={id:"RibSketch",name:"RibSketch",plane:{type:"XY",offset:10},entities:{line:{id:"line",type:"line",start:{x:20,y:0},end:{x:20,y:60},construction:false}},entityOrder:["line"],constraints:{},dimensions:{}};doc.features.Rib={id:"Rib",name:"Rib",type:"rib",targetFeatureId:"Base",sketchId:"RibSketch",thicknessMm:4,heightMm:20,enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Rib");await rebuild(doc,runtime,state);let p=await kernel.getShapeProperties(runtime.featureShapes.get("Rib"));close(p.volumeMm3,64800);close(p.boundingBox.max.z,30);
 doc.features.Rib={...doc.features.Rib,thicknessMm:6,heightMm:30};await rebuild(doc,runtime,state,{changedFeatureIds:["Rib"]});p=await kernel.getShapeProperties(runtime.featureShapes.get("Rib"));close(p.volumeMm3,70800);close(p.boundingBox.max.z,40);
 const edge=(await kernel.getEdges(runtime.featureShapes.get("Rib"))).find(item=>item.curveType==="line"&&(item.lengthMm??0)>29);const edgeRef=await capturePersistentTopologyRef("Rib",edge.topology,runtime,kernel);doc.features.RibFillet={id:"RibFillet",name:"RibFillet",type:"fillet",targetFeatureId:"Rib",edges:[edgeRef],radiusMm:1,enabled:true,state:"clean",dependencies:["Rib"]};doc.featureOrder.push("RibFillet");await rebuild(doc,runtime,state);assert.equal((await kernel.validate(runtime.featureShapes.get("RibFillet"))).valid,true);await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 Draft verifies top dimensions, reverse, suppression, Fillet, and last-good rollback",async()=>{
 const doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const base=runtime.featureShapes.get("Base");const refs=await Promise.all((await kernel.getFaces(base)).filter(face=>Math.abs(face.normal?.z??0)<.01).map(face=>capturePersistentTopologyRef("Base",face.topology,runtime,kernel)));
 doc.features.Draft={id:"Draft",name:"Draft",type:"draft",targetFeatureId:"Base",faces:refs,pullDirection:{x:0,y:0,z:1},angleDeg:5,enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Draft");await rebuild(doc,runtime,state);const inward=await kernel.getShapeProperties(runtime.featureShapes.get("Draft"));assert.ok(inward.volumeMm3<120000);const lengths=(await kernel.getEdges(runtime.featureShapes.get("Draft"))).filter(edge=>edge.curveType==="line").map(edge=>edge.lengthMm??0);assert.ok(lengths.some(length=>Math.abs(length-96.500454)<.001));assert.ok(lengths.some(length=>Math.abs(length-56.500454)<.001));
 doc.features.Draft={...doc.features.Draft,enabled:false,state:"suppressed"};const suppressed=await rebuild(doc,runtime,state,{changedFeatureIds:["Draft"]});assert.ok(suppressed.suppressedFeatureIds.includes("Draft"));close((await kernel.getShapeProperties(getRuntimeFeatureShape(runtime,"Draft"))).volumeMm3,120000);doc.features.Draft={...doc.features.Draft,enabled:true,state:"clean"};await rebuild(doc,runtime,state,{changedFeatureIds:["Draft"]});
 const draftEdge=(await kernel.getEdges(runtime.featureShapes.get("Draft"))).find(edge=>edge.curveType==="line"&&(edge.lengthMm??0)>19&&(edge.lengthMm??0)<21);const edgeRef=await capturePersistentTopologyRef("Draft",draftEdge.topology,runtime,kernel);doc.features.DraftFillet={id:"DraftFillet",name:"DraftFillet",type:"fillet",targetFeatureId:"Draft",edges:[edgeRef],radiusMm:2,enabled:true,state:"clean",dependencies:["Draft"]};doc.featureOrder.push("DraftFillet");await rebuild(doc,runtime,state);assert.equal((await kernel.validate(runtime.featureShapes.get("DraftFillet"))).valid,true);delete doc.features.DraftFillet;doc.featureOrder.pop();
 doc.features.Draft={...doc.features.Draft,reverse:true};await rebuild(doc,runtime,state,{changedFeatureIds:["Draft"]});assert.ok((await kernel.getShapeProperties(runtime.featureShapes.get("Draft"))).volumeMm3>120000);
 doc.features.Draft={...doc.features.Draft,angleDeg:0};const failed=await rebuildDocument(ctx(doc,runtime,state),{changedFeatureIds:["Draft"]});assert.equal(failed.success,false);assert.ok(runtime.featureShapes.get("Draft"));await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 design-only save/load, topology and legacy simple Hole migration rebuild",async()=>{
 const doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const ref=await capturePersistentTopologyRef("Base",(await top(runtime.featureShapes.get("Base"))).topology,runtime,kernel);doc.features.Hole={id:"Hole",name:"Hole",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},style:{type:"countersink",diameterMm:20,includedAngleDeg:90},enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Hole");await rebuild(doc,runtime,state);const shape=runtime.featureShapes.get("Hole");const [faces,edges,mesh]=await Promise.all([kernel.getFaces(shape),kernel.getEdges(shape),kernel.tessellate(shape,{linearDeflectionMm:1,angularDeflectionDeg:10})]);assert.ok(faces.length&&edges.length&&mesh.indices.length&&mesh.triangleFaceIndices.length===mesh.indices.length/3);
 const saved=toSerializableCadDocument(doc);const restored=deserializeCadDocument(saved);assert.equal(restored.features.Hole.style.type,"countersink");const legacy=deserializeCadDocument({...saved,features:{...saved.features,Hole:{...saved.features.Hole,style:undefined}}});assert.equal(legacy.features.Hole.style.type,"simple");await disposeCadRuntimeState(runtime,kernel);const restoredRuntime=createCadRuntimeState(),restoredState=createRebuildRuntimeState();await rebuild(restored,restoredRuntime,restoredState);close((await kernel.getShapeProperties(restoredRuntime.featureShapes.get("Hole"))).volumeMm3,120000-2000*Math.PI/3);await disposeCadRuntimeState(restoredRuntime,kernel);
});

test("P2-M5 CadHistory snapshots are immutable, canonical, bounded and invalidate redo",()=>{
 const initial=createCadDocument({id:"history",name:"A",bodies:{Body:{id:"Body",name:"Body",backend:"legacy-mesh",visible:true,runtimeShapeId:"runtime-only"}},activeBodyId:"Body"});let history=createCadHistory(initial,2);const a=currentCadDocument(history);assert.equal(a.bodies.Body.runtimeShapeId,undefined);assert.equal(a.activeBodyId,"Body");assert.equal(a.bodies.Body.name,"Body");const b={...a,name:"B"};history=commitCadHistory(history,b);assert.equal(history.past.length,1);b.name="mutated";assert.equal(currentCadDocument(history).name,"B");const duplicate=commitCadHistory(history,currentCadDocument(history));assert.equal(duplicate,history);const undone=undoCadHistory(history);assert.ok(undone);history=undone.history;assert.equal(undone.document.name,"A");assert.equal(undone.document.activeBodyId,"Body");assert.equal(canRedoCadHistory(history),true);history=commitCadHistory(history,{...undone.document,name:"D"});assert.equal(canRedoCadHistory(history),false);assert.equal(canUndoCadHistory(history),true);assert.equal(JSON.stringify(history).match(/runtime-only|shape-|face-|edge-/),null);const redone=redoCadHistory(history);assert.equal(redone,undefined);
});

test("P2-M5 Draft, Rib and advanced Hole history restore design then rebuild runtime",async()=>{
 const historyContext=(runtime,state)=>({runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});
 let doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const draftRefs=await Promise.all((await kernel.getFaces(runtime.featureShapes.get("Base"))).filter(face=>Math.abs(face.normal?.z??0)<.01).map(face=>capturePersistentTopologyRef("Base",face.topology,runtime,kernel)));doc.features.Draft={id:"Draft",name:"Draft",type:"draft",targetFeatureId:"Base",faces:draftRefs,pullDirection:{x:0,y:0,z:1},angleDeg:5,enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Draft");await rebuild(doc,runtime,state);let history=createCadHistory(doc);let candidate=structuredClone(doc);candidate.features.Draft.angleDeg=8;let committed=await commitCadHistoryEdit(history,doc,candidate,historyContext(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;assert.equal(doc.features.Draft.angleDeg,8);let restored=await undoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Draft.angleDeg,5);assert.ok((await kernel.getEdges(runtime.featureShapes.get("Draft"))).some(edge=>Math.abs((edge.lengthMm??0)-96.500453)<.001));restored=await redoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Draft.angleDeg,8);for(let i=0;i<25;i++){const u=await undoCadHistoryRebuild(history,doc,historyContext(runtime,state));history=u.history;doc=u.document;const r=await redoCadHistoryRebuild(history,doc,historyContext(runtime,state));history=r.history;doc=r.document;}assert.equal(runtime.featureShapes.size,2);await disposeCadRuntimeState(runtime,kernel);
 doc=document(10);runtime=createCadRuntimeState();state=createRebuildRuntimeState();await rebuild(doc,runtime,state);doc.sketches.RibSketch={id:"RibSketch",name:"Rib",plane:{type:"XY",offset:10},entities:{line:{id:"line",type:"line",start:{x:20,y:0},end:{x:20,y:60},construction:false}},entityOrder:["line"],constraints:{},dimensions:{}};doc.features.Rib={id:"Rib",name:"Rib",type:"rib",targetFeatureId:"Base",sketchId:"RibSketch",thicknessMm:4,heightMm:20,enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Rib");await rebuild(doc,runtime,state);history=createCadHistory(doc);candidate=structuredClone(doc);candidate.features.Rib.thicknessMm=6;candidate.features.Rib.heightMm=30;committed=await commitCadHistoryEdit(history,doc,candidate,historyContext(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;restored=await undoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Rib.thicknessMm,4);close((await kernel.getShapeProperties(runtime.featureShapes.get("Rib"))).volumeMm3,64800);restored=await redoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Rib.heightMm,30);await disposeCadRuntimeState(runtime,kernel);
 doc=document();runtime=createCadRuntimeState();state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const ref=await capturePersistentTopologyRef("Base",(await top(runtime.featureShapes.get("Base"))).topology,runtime,kernel);doc.features.Hole={id:"Hole",name:"Hole",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},style:{type:"counterbore",diameterMm:20,depthMm:5},enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Hole");await rebuild(doc,runtime,state);history=createCadHistory(doc);candidate=structuredClone(doc);candidate.features.Hole.style.depthMm=8;committed=await commitCadHistoryEdit(history,doc,candidate,historyContext(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;restored=await undoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Hole.style.depthMm,5);close((await kernel.getShapeProperties(runtime.featureShapes.get("Hole"))).volumeMm3,120000-875*Math.PI);await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 Countersink history and feature creation/deletion/suppression restore design order",async()=>{
 const historyContext=(runtime,state)=>({runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});let doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const ref=await capturePersistentTopologyRef("Base",(await top(runtime.featureShapes.get("Base"))).topology,runtime,kernel);doc.features.Hole={id:"Hole",name:"Hole",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},style:{type:"countersink",diameterMm:20,includedAngleDeg:90},enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Hole");await rebuild(doc,runtime,state);let history=createCadHistory(doc);let candidate=structuredClone(doc);candidate.features.Hole.style.includedAngleDeg=100;let committed=await commitCadHistoryEdit(history,doc,candidate,historyContext(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;let restored=await undoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Hole.style.includedAngleDeg,90);restored=await redoCadHistoryRebuild(history,doc,historyContext(runtime,state));assert.equal(restored.success,true);assert.equal(restored.document.features.Hole.style.includedAngleDeg,100);await disposeCadRuntimeState(runtime,kernel);
 const base=document();history=createCadHistory(base);candidate=structuredClone(base);candidate.sketches.RibSketch={id:"RibSketch",name:"Rib",plane:{type:"XY",offset:20},entities:{line:{id:"line",type:"line",start:{x:0,y:0},end:{x:0,y:60},construction:false}},entityOrder:["line"],constraints:{},dimensions:{}};candidate.features.Rib={id:"Rib",name:"Rib",type:"rib",targetFeatureId:"Base",sketchId:"RibSketch",thicknessMm:4,heightMm:20,enabled:true,state:"clean",dependencies:["Base"]};candidate.featureOrder.push("Rib");history=commitCadHistory(history,candidate);let transition=undoCadHistory(history);assert.ok(transition);assert.equal(transition.document.features.Rib,undefined);assert.deepEqual(transition.document.featureOrder,["Base"]);transition=redoCadHistory(transition.history);assert.ok(transition);assert.equal(transition.document.features.Rib.thicknessMm,4);const deleted=structuredClone(transition.document);delete deleted.features.Rib;delete deleted.sketches.RibSketch;deleted.featureOrder.pop();history=commitCadHistory(transition.history,deleted);transition=undoCadHistory(history);assert.ok(transition);assert.equal(transition.document.features.Rib.heightMm,20);const suppressed=structuredClone(transition.document);suppressed.features.Rib.enabled=false;suppressed.features.Rib.state="suppressed";history=commitCadHistory(transition.history,suppressed);transition=undoCadHistory(history);assert.ok(transition);assert.equal(transition.document.features.Rib.enabled,true);assert.deepEqual(transition.document.featureOrder,["Base","Rib"]);
});

test("P2-M5 Draft History performs 50 undo/redo rebuilds without retaining extra shapes",async()=>{
 const context=(runtime,state)=>({runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});let doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const refs=await Promise.all((await kernel.getFaces(runtime.featureShapes.get("Base"))).filter(face=>Math.abs(face.normal?.z??0)<.01).map(face=>capturePersistentTopologyRef("Base",face.topology,runtime,kernel)));doc.features.Draft={id:"Draft",name:"Draft",type:"draft",targetFeatureId:"Base",faces:refs,pullDirection:{x:0,y:0,z:1},angleDeg:5,enabled:true,state:"clean",dependencies:["Base"]};doc.featureOrder.push("Draft");await rebuild(doc,runtime,state);let history=createCadHistory(doc);const edited=structuredClone(doc);edited.features.Draft.angleDeg=8;const committed=await commitCadHistoryEdit(history,doc,edited,context(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;for(let i=0;i<50;i++){const undo=await undoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(undo.success,true);history=undo.history;doc=undo.document;const redo=await redoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(redo.success,true);history=redo.history;doc=redo.document;}assert.equal(runtime.featureShapes.size,2);assert.equal(runtime.featureAliases.size,0);await disposeCadRuntimeState(runtime,kernel);
});

test("P2-M5 Sketch dimension and Pattern count History restore through real rebuild",async()=>{
 const context=(runtime,state)=>({runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});let doc=document(),runtime=createCadRuntimeState(),state=createRebuildRuntimeState();await rebuild(doc,runtime,state);let history=createCadHistory(doc);let candidate=structuredClone(doc);candidate.sketches.Base.entities.a.end.x=150;candidate.sketches.Base.entities.b.start.x=150;candidate.sketches.Base.entities.b.end.x=150;candidate.sketches.Base.entities.c.start.x=150;let committed=await commitCadHistoryEdit(history,doc,candidate,context(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;close((await kernel.getShapeProperties(runtime.featureShapes.get("Base"))).boundingBox.max.x,150);let restored=await undoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;close((await kernel.getShapeProperties(runtime.featureShapes.get("Base"))).boundingBox.max.x,100);restored=await redoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(restored.success,true);await disposeCadRuntimeState(runtime,kernel);
 doc=document();runtime=createCadRuntimeState();state=createRebuildRuntimeState();await rebuild(doc,runtime,state);const ref=await capturePersistentTopologyRef("Base",(await top(runtime.featureShapes.get("Base"))).topology,runtime,kernel);doc.features.Hole={id:"Hole",name:"Hole",type:"hole",targetFeatureId:"Base",targetFace:ref,center:{x:0,y:0},diameterMm:4,depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["Base"]};doc.features.Pattern={id:"Pattern",name:"Pattern",type:"linearPattern",targetFeatureId:"Base",seedFeatureIds:["Hole"],direction:"X",count:5,spacingMm:10,symmetric:true,enabled:true,state:"clean",dependencies:["Base","Hole"]};doc.featureOrder.push("Hole","Pattern");await rebuild(doc,runtime,state);history=createCadHistory(doc);candidate=structuredClone(doc);candidate.features.Pattern.count=7;committed=await commitCadHistoryEdit(history,doc,candidate,context(runtime,state));assert.equal(committed.success,true);history=committed.history;doc=committed.document;assert.equal(doc.features.Pattern.count,7);restored=await undoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(restored.success,true);history=restored.history;doc=restored.document;assert.equal(doc.features.Pattern.count,5);restored=await redoCadHistoryRebuild(history,doc,context(runtime,state));assert.equal(restored.success,true);assert.equal(restored.document.features.Pattern.count,7);await disposeCadRuntimeState(runtime,kernel);
});
