import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument, toSerializableCadDocument } from "../core/cad/CadDocument.ts";
import { canonicalSerializeCadDocument, CadDocumentError, computeCadDocumentFingerprint, deserializeCadDocument } from "../core/cad/CadDocumentPersistence.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState } from "../core/evaluation/CadRuntimeState.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef, resolvePersistentTopologyRef, resolvePersistentTopologyRefV2 } from "../core/topology/TopologyResolver.ts";
import { migratePersistentTopologyRefV1ToV2 } from "../core/topology/PersistentTopologyRef.ts";

const wasm=new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm",import.meta.url);let kernel;
const document=(width=100,height=60,depth=20)=>createCadDocument({id:"v2",name:"V2",sketches:{Sketch01:{id:"Sketch01",name:"Sketch01",plane:{type:"XY",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:width,y:0},construction:false},b:{id:"b",type:"line",start:{x:width,y:0},end:{x:width,y:height},construction:false},c:{id:"c",type:"line",start:{x:width,y:height},end:{x:0,y:height},construction:false},d:{id:"d",type:"line",start:{x:0,y:height},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}}},features:{Extrude01:{id:"Extrude01",name:"Extrude01",type:"extrude",sketchId:"Sketch01",distance:depth,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}},featureOrder:["Extrude01"]});
const context=(doc,runtime,state)=>({document:doc,runtime,rebuildRuntime:state,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});
before(async()=>{kernel=new OcctKernel({wasm});await kernel.init();});after(async()=>kernel?.dispose());

test("M11 V2 captures durable face/edge signatures and survives multi-axis resize",async()=>{const runtime=createCadRuntimeState(),state=createRebuildRuntimeState();try{const first=document();assert.equal((await rebuildDocument(context(first,runtime,state),{full:true})).success,true);const shape=runtime.featureShapes.get("Extrude01"),top=(await kernel.getFaces(shape)).find(face=>face.normal?.z>.999),edge=(await kernel.getEdges(shape)).find(item=>item.curveType==="line"&&Math.abs((item.endMm?.z??0)-(item.startMm?.z??0))>19);const faceRef=await capturePersistentTopologyRef("Extrude01",top.topology,runtime,kernel),edgeRef=await capturePersistentTopologyRef("Extrude01",edge.topology,runtime,kernel);assert.equal(faceRef.version,2);assert.equal(edgeRef.version,2);assert.doesNotMatch(JSON.stringify({faceRef,edgeRef}),/shape-|face-\d|edge-\d|hash|triangle/i);assert.equal((await rebuildDocument(context(document(150,80,30),runtime,state),{changedSketchIds:["Sketch01"]})).success,true);const resolvedFace=await kernel.getFaceInfo(await resolvePersistentTopologyRef(faceRef,runtime,kernel)),resolvedEdge=await kernel.getEdgeInfo(await resolvePersistentTopologyRef(edgeRef,runtime,kernel));assert.ok((resolvedFace.normal?.z??0)>.999);assert.ok(Math.abs((resolvedEdge.endMm?.z??0)-(resolvedEdge.startMm?.z??0))>29);assert.equal(state.lastSuccessfulDocumentFingerprint,state.currentDocumentFingerprint);}finally{await disposeCadRuntimeState(runtime,kernel);}});

test("M11 resolver rejects symmetric ambiguity and is independent of candidate enumeration order",async()=>{const shape={id:"synthetic",revision:1},runtime={featureShapes:new Map([["F",shape]]),featureAliases:new Map(),bodyShapes:new Map(),featureResults:new Map()};const ref={version:2,sourceFeatureId:"F",kind:"face",signature:{kind:"face",surfaceType:"plane",normalizedCenter:{x:.5,y:.5,z:.5}}};const candidate=(localId,center)=>({topology:{shapeId:"synthetic",shapeRevision:1,kind:"face",localId},surfaceType:"plane",centerMm:center,normal:{x:0,y:0,z:1},areaMm2:1});const fake={getShapeProperties:async()=>({boundingBox:{min:{x:0,y:0,z:0},max:{x:1,y:1,z:1}},surfaceAreaMm2:6}),getFaces:async()=>[candidate("b",{x:.5,y:.5,z:.5}),candidate("a",{x:.5,y:.5,z:.5})]};let result=await resolvePersistentTopologyRefV2(ref,runtime,fake);assert.equal(result.status,"ambiguous");fake.getFaces=async()=>[candidate("far",{x:.9,y:.9,z:.9}),candidate("winner",{x:.5,y:.5,z:.5})];result=await resolvePersistentTopologyRefV2(ref,runtime,fake);assert.equal(result.status,"resolved");assert.equal(result.topology.localId,"winner");fake.getFaces=async()=>[candidate("winner",{x:.5,y:.5,z:.5}),candidate("far",{x:.9,y:.9,z:.9})];assert.equal((await resolvePersistentTopologyRefV2(ref,runtime,fake)).topology.localId,"winner");});

test("M11 V1 migration, canonical persistence and validation are deterministic",()=>{const legacy={...toSerializableCadDocument(document()),schemaVersion:1,features:{Extrude01:{...document().features.Extrude01,state:"clean"}}};const legacyRef={version:1,sourceFeatureId:"Extrude01",kind:"face",signature:{kind:"face",surfaceType:"plane",normalizedCenter:{x:.5,y:.5,z:1}}};assert.deepEqual(migratePersistentTopologyRefV1ToV2(legacyRef),migratePersistentTopologyRefV1ToV2(legacyRef));assert.equal(migratePersistentTopologyRefV1ToV2(legacyRef).version,2);const loaded=deserializeCadDocument(legacy);assert.equal(loaded.schemaVersion,2);const a=canonicalSerializeCadDocument(loaded),b=canonicalSerializeCadDocument(deserializeCadDocument(JSON.parse(a)));assert.equal(a,b);assert.equal(computeCadDocumentFingerprint(loaded),computeCadDocumentFingerprint(deserializeCadDocument(JSON.parse(a))));assert.throws(()=>deserializeCadDocument({...legacy,schemaVersion:99}),error=>error instanceof CadDocumentError&&error.code==="CAD_DOCUMENT_VERSION_UNSUPPORTED");assert.throws(()=>deserializeCadDocument({...legacy,featureOrder:["Extrude01","Extrude01"]}),error=>error instanceof CadDocumentError&&error.code==="CAD_DOCUMENT_INVALID");assert.throws(()=>deserializeCadDocument({...legacy,features:{Extrude01:{...legacy.features.Extrude01,sketchId:"missing"}}}),error=>error instanceof CadDocumentError&&error.code==="CAD_DOCUMENT_INVALID");});

test("M11 50 fixed-seed incremental rebuilds retain only the active owned shape",async()=>{const runtime=createCadRuntimeState(),state=createRebuildRuntimeState();try{let current=document();assert.equal((await rebuildDocument(context(current,runtime,state),{full:true})).success,true);for(let index=0;index<50;index++){const width=80+((index*37)%101),height=50+((index*19)%51),depth=15+((index*11)%26);current=document(width,height,depth);const result=await rebuildDocument(context(current,runtime,state),{changedSketchIds:["Sketch01"]});assert.equal(result.success,true,JSON.stringify(result.errors));assert.equal((await kernel.validate(runtime.featureShapes.get("Extrude01"))).valid,true);}assert.equal(runtime.featureShapes.size,1);}finally{await disposeCadRuntimeState(runtime,kernel);}});
