import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument } from "../core/cad/CadDocument.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState } from "../core/evaluation/CadRuntimeState.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { buildFeatureGraph, FeatureGraphError } from "../core/rebuild/FeatureGraph.ts";
import { computeDirtyFeatures } from "../core/rebuild/DirtyPropagation.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef } from "../core/topology/TopologyResolver.ts";

const wasm = new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm", import.meta.url); let kernel;
const document = (width = 100, features = {}) => createCadDocument({ id:"m10", name:"M10", sketches:{ Sketch01:{id:"Sketch01",name:"Sketch01",plane:{type:"XY",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:width,y:0},construction:false},b:{id:"b",type:"line",start:{x:width,y:0},end:{x:width,y:60},construction:false},c:{id:"c",type:"line",start:{x:width,y:60},end:{x:0,y:60},construction:false},d:{id:"d",type:"line",start:{x:0,y:60},end:{x:0,y:0},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}} },features:{Extrude01:{id:"Extrude01",name:"Extrude01",type:"extrude",sketchId:"Sketch01",distance:20,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]},...features},featureOrder:["Extrude01",...Object.keys(features)] });
const context = (doc, runtime, rebuildRuntime) => ({ document:doc, runtime, rebuildRuntime, kernel, tolerance:DEFAULT_CAD_TOLERANCE, buildProfiles:buildSketchProfiles });
before(async()=>{kernel=new OcctKernel({wasm});await kernel.init();}); after(async()=>kernel?.dispose());

test("M10 graph validates deterministically and propagates only affected branches", () => { const doc=document(); const graph=buildFeatureGraph(doc); assert.deepEqual(graph.order,["Extrude01"]); assert.deepEqual([...computeDirtyFeatures(graph,{changedSketchIds:["Sketch01"]})],["Extrude01"]); const bad=document(100,{Bad:{id:"Bad",name:"Bad",type:"fillet",targetFeatureId:"missing",edges:[],radiusMm:2,enabled:true,state:"clean",dependencies:["missing"]}}); assert.throws(()=>buildFeatureGraph(bad),error=>error instanceof FeatureGraphError&&error.code==="FEATURE_DEPENDENCY_MISSING"); });

test("M10-C Shell keeps the original outer box with 2 mm inward intersection walls", async () => { const runtime=createCadRuntimeState(), state=createRebuildRuntimeState(), base=document(); assert.equal((await rebuildDocument(context(base,runtime,state),{full:true})).success,true); const top=(await kernel.getFaces(runtime.featureShapes.get("Extrude01"))).find(face=>face.normal?.z>.999); const persistent=await capturePersistentTopologyRef("Extrude01",top.topology,runtime,kernel); const shelled=document(100,{Shell01:{id:"Shell01",name:"Shell01",type:"shell",targetFeatureId:"Extrude01",removeFaces:[persistent],thicknessMm:2,enabled:true,state:"clean",dependencies:["Extrude01"]}}); const result=await rebuildDocument(context(shelled,runtime,state),{full:true}); assert.equal(result.success,true,JSON.stringify(result.errors)); const shape=runtime.featureShapes.get("Shell01"), props=await kernel.getShapeProperties(shape), faces=await kernel.getFaces(shape); assert.equal((await kernel.validate(shape)).valid,true); assert.deepEqual(props.boundingBox,{min:{x:0,y:0,z:0},max:{x:100,y:60,z:20}}); assert.equal(props.volumeMm3,23232); assert.ok(faces.some(face=>face.centerMm?.x===2)); assert.ok(faces.some(face=>face.centerMm?.z===2)); });

test("M10 staged rebuild updates a Hole chain atomically after sketch resize", async () => { const runtime=createCadRuntimeState(), state=createRebuildRuntimeState(), base=document(); assert.equal((await rebuildDocument(context(base,runtime,state),{full:true})).success,true); const old=runtime.featureShapes.get("Extrude01"); const top=(await kernel.getFaces(old)).find(face=>face.normal?.z>.999); const ref=await capturePersistentTopologyRef("Extrude01",top.topology,runtime,kernel); const chained=document(100,{Hole01:{id:"Hole01",name:"Hole01",type:"hole",targetFeatureId:"Extrude01",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["Extrude01"]}}); assert.equal((await rebuildDocument(context(chained,runtime,state),{full:true})).success,true); const oldHole=runtime.featureShapes.get("Hole01"); const resized=document(150,chained.features.Hole01?{Hole01:chained.features.Hole01}:{}); const result=await rebuildDocument(context(resized,runtime,state),{changedSketchIds:["Sketch01"]}); assert.equal(result.success,true,JSON.stringify(result.errors)); assert.deepEqual(result.evaluatedFeatureIds,["Extrude01","Hole01"]); assert.notEqual(runtime.featureShapes.get("Extrude01").id,old.id); assert.notEqual(runtime.featureShapes.get("Hole01").id,oldHole.id); assert.ok(Math.abs((await kernel.getShapeProperties(runtime.featureShapes.get("Hole01"))).volumeMm3-(150*60*20-500*Math.PI))<.2); });

test("M10 failed staged downstream Feature rolls back and keeps last good runtime", async () => { const runtime=createCadRuntimeState(), state=createRebuildRuntimeState(), base=document(); assert.equal((await rebuildDocument(context(base,runtime,state),{full:true})).success,true); const old=runtime.featureShapes.get("Extrude01"); const top=(await kernel.getFaces(old)).find(face=>face.normal?.z>.999); const ref=await capturePersistentTopologyRef("Extrude01",top.topology,runtime,kernel); const broken=document(150,{Shell01:{id:"Shell01",name:"Shell01",type:"shell",targetFeatureId:"Extrude01",removeFaces:[ref],thicknessMm:0,enabled:true,state:"clean",dependencies:["Extrude01"]}}); const result=await rebuildDocument(context(broken,runtime,state),{full:true}); assert.equal(result.success,false); assert.deepEqual(result.failedFeatureIds,["Shell01"]); assert.equal(runtime.featureShapes.get("Extrude01").id,old.id); });
