import assert from "node:assert/strict";
import test from "node:test";
import { intersectSketchEntities2D } from "../core/sketch/operations/Intersection2D.ts";
import { trimSketchEntity } from "../core/sketch/operations/Trim.ts";
import { extendLineToEntity } from "../core/sketch/operations/Extend.ts";
import { offsetLineChain, offsetSketchEntity } from "../core/sketch/operations/Offset.ts";

const line=(id,start,end)=>({id,type:"line",start,end,construction:false});
const sketch=(entities)=>({id:"S",name:"S",plane:{type:"XY",offset:0},entities:Object.fromEntries(entities.map(x=>[x.id,x])),entityOrder:entities.map(x=>x.id),constraints:{},dimensions:{}});
test("analytic intersections cover line, circle and arc without duplicate tangent points",()=>{const a=line("a",{x:0,y:0},{x:100,y:0}),b=line("b",{x:50,y:-30},{x:50,y:30}),circle={id:"c",type:"circle",center:{x:50,y:0},radius:20,construction:false},arc={id:"arc",type:"arc",center:{x:50,y:0},radius:20,startAngle:0,endAngle:Math.PI,construction:false};assert.equal(intersectSketchEntities2D(a,b).length,1);assert.equal(intersectSketchEntities2D(a,circle).length,2);assert.equal(intersectSketchEntities2D(b,arc).length,1);assert.equal(intersectSketchEntities2D({...circle,id:"c2",center:{x:90,y:0}},circle).length,1);});
test("line trim retains source id and splits exact line-circle intersections",()=>{const a=line("a",{x:0,y:0},{x:100,y:0}),c={id:"c",type:"circle",center:{x:50,y:0},radius:20,construction:true};const result=trimSketchEntity(sketch([a,c]),"a",{x:50,y:0});assert.equal(result.entities.a.end.x,30);assert.equal(result.createdEntityIds.length,1);assert.equal(result.entities[result.createdEntityIds[0]].start.x,70);});
test("circle trim produces an exact Arc and line extend chooses the requested ray",()=>{const c={id:"c",type:"circle",center:{x:0,y:0},radius:10,construction:false},vertical=line("v",{x:-20,y:0},{x:20,y:0});const trimmed=trimSketchEntity(sketch([c,vertical]),"c",{x:0,y:10});assert.equal(trimmed.entities.c.type,"arc");const source=line("s",{x:0,y:0},{x:10,y:0}),target=line("t",{x:30,y:-5},{x:30,y:5});const extended=extendLineToEntity(sketch([source,target]),"s","end","t");assert.equal(extended.entities.s.end.x,30);});
test("line, circle, arc and closed chain offsets stay analytic",()=>{const a=line("a",{x:0,y:0},{x:100,y:0}),b=line("b",{x:100,y:0},{x:100,y:60}),c=line("c",{x:100,y:60},{x:0,y:60}),d=line("d",{x:0,y:60},{x:0,y:0});const source=sketch([a,b,c,d]);const chain=offsetLineChain(source,["a","b","c","d"],10,{x:50,y:30});const xs=Object.values(chain.entities).filter(x=>x.id.endsWith("offset")).flatMap(x=>[x.start.x,x.end.x]),ys=Object.values(chain.entities).filter(x=>x.id.endsWith("offset")).flatMap(x=>[x.start.y,x.end.y]);assert.equal(Math.max(...xs)-Math.min(...xs),80);assert.equal(Math.max(...ys)-Math.min(...ys),40);const circle={id:"o",type:"circle",center:{x:0,y:0},radius:10,construction:false},arc={id:"r",type:"arc",center:{x:0,y:0},radius:10,startAngle:0,endAngle:1,construction:false};assert.equal(offsetSketchEntity(sketch([circle]),"o",5,{x:20,y:0}).entities["o-offset"].radius,15);assert.equal(offsetSketchEntity(sketch([arc]),"r",2,{x:20,y:0}).entities["r-offset"].type,"arc");});
