import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument, toSerializableCadDocument } from "../core/cad/CadDocument.ts";
import { deserializeCadDocument } from "../core/cad/CadDocumentPersistence.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState } from "../core/evaluation/CadRuntimeState.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { rebuildDocument } from "../core/rebuild/RebuildEngine.ts";
import { createRebuildRuntimeState } from "../core/rebuild/RebuildTypes.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef } from "../core/topology/TopologyResolver.ts";

const wasm=new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm",import.meta.url);let kernel;const close=(a,e,t=.35)=>assert.ok(Math.abs(a-e)<=t,`${a} != ${e}`);
const circle=(id,r,z=0)=>({id,name:id,plane:{type:"XY",offset:z},entities:{c:{id:"c",type:"circle",center:{x:0,y:0},radius:r,construction:false}},entityOrder:["c"],constraints:{},dimensions:{}});
const rect=(id,w,h,z=0)=>({id,name:id,plane:{type:"XY",offset:z},entities:{a:{id:"a",type:"line",start:{x:-w/2,y:-h/2},end:{x:w/2,y:-h/2},construction:false},b:{id:"b",type:"line",start:{x:w/2,y:-h/2},end:{x:w/2,y:h/2},construction:false},c:{id:"c",type:"line",start:{x:w/2,y:h/2},end:{x:-w/2,y:h/2},construction:false},d:{id:"d",type:"line",start:{x:-w/2,y:h/2},end:{x:-w/2,y:-h/2},construction:false}},entityOrder:["a","b","c","d"],constraints:{},dimensions:{}});
const straight=(length=100)=>({id:"Path",name:"Path",plane:{type:"XZ",offset:0},entities:{p:{id:"p",type:"line",start:{x:0,y:0},end:{x:0,y:length},construction:false}},entityOrder:["p"],constraints:{},dimensions:{}});
const ctx=(document,runtime,rebuildRuntime)=>({document,runtime,rebuildRuntime,kernel,tolerance:DEFAULT_CAD_TOLERANCE,buildProfiles:buildSketchProfiles});const run=async(d,r,s,q={full:true})=>{const x=await rebuildDocument(ctx(d,r,s),q);assert.equal(x.success,true,JSON.stringify(x.errors));return x;};
const sweepDoc=(profile=circle("Profile",5),path=straight())=>createCadDocument({id:"sweep",name:"Sweep",sketches:{Profile:profile,Path:path},features:{Sweep01:{id:"Sweep01",name:"Sweep01",type:"sweep",profileSketchId:"Profile",pathSketchId:"Path",operation:"new",orientation:"followPath",enabled:true,state:"clean",dependencies:[]}},featureOrder:["Sweep01"]});
const loftDoc=(sections)=>createCadDocument({id:"loft",name:"Loft",sketches:Object.fromEntries(sections.map(x=>[x.id,x])),features:{Loft01:{id:"Loft01",name:"Loft01",type:"loft",sectionSketchIds:sections.map(x=>x.id),solid:true,ruled:true,enabled:true,state:"clean",dependencies:[]}},featureOrder:["Loft01"]});
before(async()=>{kernel=new OcctKernel({wasm});await kernel.init();});after(async()=>kernel?.dispose());

test("P2-M4 exact straight Circle/Rectangle Sweeps rebuild",async()=>{const d=sweepDoc(),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);close((await kernel.getShapeProperties(r.featureShapes.get("Sweep01"))).volumeMm3,2500*Math.PI,.05);d.sketches.Profile.entities.c.radius=8;assert.deepEqual((await run(d,r,s,{changedSketchIds:["Profile"]})).evaluatedFeatureIds,["Sweep01"]);d.sketches.Path.entities.p.end.y=150;assert.deepEqual((await run(d,r,s,{changedSketchIds:["Path"]})).evaluatedFeatureIds,["Sweep01"]);close((await kernel.getShapeProperties(r.featureShapes.get("Sweep01"))).volumeMm3,9600*Math.PI,.15);await disposeCadRuntimeState(r,kernel);const rd=sweepDoc(rect("Profile",20,10),straight()),rr=createCadRuntimeState(),rs=createRebuildRuntimeState();await run(rd,rr,rs);close((await kernel.getShapeProperties(rr.featureShapes.get("Sweep01"))).volumeMm3,20000,.05);await disposeCadRuntimeState(rr,kernel);});

test("P2-M4 arc and mixed exact Sweep paths map topology",async()=>{const arc={id:"Path",name:"Path",plane:{type:"XZ",offset:0},entities:{a:{id:"a",type:"arc",center:{x:50,y:0},radius:50,startAngle:Math.PI,endAngle:Math.PI*1.5,construction:false}},entityOrder:["a"],constraints:{},dimensions:{}};const d=sweepDoc(circle("Profile",5),arc),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);const shape=r.featureShapes.get("Sweep01");close((await kernel.getShapeProperties(shape)).volumeMm3,625*Math.PI*Math.PI,.7);const mesh=await kernel.tessellate(shape,{linearDeflectionMm:.5,angularDeflectionDeg:5});assert.ok([...mesh.triangleFaceIndices].every(i=>i<mesh.faces.length));await disposeCadRuntimeState(r,kernel);const mixed={id:"Path",name:"Path",plane:{type:"XZ",offset:0},entities:{a:{id:"a",type:"line",start:{x:0,y:0},end:{x:50,y:0},construction:false},b:{id:"b",type:"arc",center:{x:50,y:50},radius:50,startAngle:-Math.PI/2,endAngle:0,construction:false},c:{id:"c",type:"line",start:{x:100,y:50},end:{x:100,y:100},construction:false}},entityOrder:["a","b","c"],constraints:{},dimensions:{}};const md=sweepDoc(rect("Profile",20,10),mixed),mr=createCadRuntimeState(),ms=createRebuildRuntimeState();await run(md,mr,ms);assert.equal((await kernel.validate(mr.featureShapes.get("Sweep01"))).valid,true);await disposeCadRuntimeState(mr,kernel);});

test("P2-M4 solid Sweep follows an editable smooth B-Spline path",async()=>{const path={id:"Path",name:"Smooth Path",plane:{type:"XZ",offset:0},entities:{p:{id:"p",type:"bspline",fitPoints:[{x:0,y:0},{x:35,y:28},{x:70,y:18},{x:110,y:55}],closed:false,startTangent:{x:30,y:18},endTangent:{x:35,y:25},construction:false}},entityOrder:["p"],constraints:{},dimensions:{}};const d=sweepDoc(circle("Profile",4),path),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);const shape=r.featureShapes.get("Sweep01");assert.ok(shape);assert.equal((await kernel.validate(shape)).valid,true);const properties=await kernel.getShapeProperties(shape);assert.ok((properties.volumeMm3??0)>5000);path.entities.p.fitPoints[2].y=34;assert.deepEqual((await run(d,r,s,{changedSketchIds:["Path"]})).evaluatedFeatureIds,["Sweep01"]);assert.equal((await kernel.validate(r.featureShapes.get("Sweep01"))).valid,true);await disposeCadRuntimeState(r,kernel);});

test("P2-M4 invalid Sweep rolls back to last-good geometry",async()=>{const d=sweepDoc(),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);const good=r.featureShapes.get("Sweep01");d.sketches.Path.entities.q={id:"q",type:"line",start:{x:20,y:20},end:{x:20,y:40},construction:false};d.sketches.Path.entityOrder.push("q");const x=await rebuildDocument(ctx(d,r,s),{changedSketchIds:["Path"]});assert.equal(x.success,false);assert.equal(x.errors[0].code,"SWEEP_PATH_NOT_CONTINUOUS");assert.equal(r.featureShapes.get("Sweep01").id,good.id);await disposeCadRuntimeState(r,kernel);});

test("P2-M4 rectangular, circular, three/five-section Lofts rebuild as B-Reps",async()=>{const d=loftDoc([rect("A",40,20),rect("B",20,10,50)]),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);close((await kernel.getShapeProperties(r.featureShapes.get("Loft01"))).volumeMm3,23333.333333,.5);const mesh=await kernel.tessellate(r.featureShapes.get("Loft01"),{linearDeflectionMm:.5,angularDeflectionDeg:5});assert.ok([...mesh.triangleFaceIndices].every(i=>i<mesh.faces.length));d.sketches.B.entities.a.start={x:-15,y:-7.5};d.sketches.B.entities.a.end={x:15,y:-7.5};d.sketches.B.entities.b.start={x:15,y:-7.5};d.sketches.B.entities.b.end={x:15,y:7.5};d.sketches.B.entities.c.start={x:15,y:7.5};d.sketches.B.entities.c.end={x:-15,y:7.5};d.sketches.B.entities.d.start={x:-15,y:7.5};d.sketches.B.entities.d.end={x:-15,y:-7.5};assert.deepEqual((await run(d,r,s,{changedSketchIds:["B"]})).evaluatedFeatureIds,["Loft01"]);const edge=(await kernel.getEdges(r.featureShapes.get("Loft01"))).find(x=>x.curveType==="line");const ref=await capturePersistentTopologyRef("Loft01",edge.topology,r,kernel);d.features.Fillet01={id:"Fillet01",name:"Fillet01",type:"fillet",targetFeatureId:"Loft01",edges:[ref],radiusMm:2,enabled:true,state:"clean",dependencies:["Loft01"]};d.featureOrder.push("Fillet01");await run(d,r,s,{full:true});assert.equal((await kernel.validate(r.featureShapes.get("Fillet01"))).valid,true);await disposeCadRuntimeState(r,kernel);const cd=loftDoc([circle("A",20),circle("B",10,50)]),cr=createCadRuntimeState(),cs=createRebuildRuntimeState();await run(cd,cr,cs);close((await kernel.getShapeProperties(cr.featureShapes.get("Loft01"))).volumeMm3,35000*Math.PI/3,.5);await disposeCadRuntimeState(cr,kernel);const many=loftDoc([rect("A",40,20),rect("B",50,30,30),rect("C",20,10,70),rect("D",35,15,90),rect("E",15,8,120)]),mr=createCadRuntimeState(),mst=createRebuildRuntimeState();await run(many,mr,mst);assert.equal((await kernel.validate(mr.featureShapes.get("Loft01"))).valid,true);await disposeCadRuntimeState(mr,kernel);});

test("P2-M4 saves design-only data and retains one active Sweep result through 20 rebuilds",async()=>{const d=sweepDoc();assert.equal(deserializeCadDocument(toSerializableCadDocument(d)).features.Sweep01.type,"sweep");const l=loftDoc([rect("A",40,20),rect("B",20,10,50)]);assert.equal(deserializeCadDocument(toSerializableCadDocument(l)).features.Loft01.type,"loft");const r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);for(let i=0;i<20;i+=1){d.sketches.Profile.entities.c.radius=i%2?5:8;await run(d,r,s,{changedSketchIds:["Profile"]});}assert.equal(r.featureShapes.size,1);await disposeCadRuntimeState(r,kernel);});

test("P2-M4 Loft rolls back invalid sections, reloads design snapshots, and retains one active shape through 20 updates",async()=>{let d=loftDoc([rect("A",40,20),rect("B",20,10,50)]),r=createCadRuntimeState(),s=createRebuildRuntimeState();await run(d,r,s);const good=r.featureShapes.get("Loft01"),saved=JSON.parse(JSON.stringify(toSerializableCadDocument(d)));d.sketches.B.entityOrder.pop();const failed=await rebuildDocument(ctx(d,r,s),{changedSketchIds:["B"]});assert.equal(failed.success,false);assert.equal(r.featureShapes.get("Loft01").id,good.id);d=deserializeCadDocument(saved);await run(d,r,s,{full:true});for(let i=0;i<20;i+=1){d.sketches.B.plane.offset=i%2?50:80;await run(d,r,s,{changedSketchIds:["B"]});assert.equal(r.featureShapes.size,1);}assert.equal((await kernel.validate(r.featureShapes.get("Loft01"))).valid,true);await disposeCadRuntimeState(r,kernel);});
