import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { createCadDocument, toSerializableCadDocument } from "../core/cad/CadDocument.ts";
import { DEFAULT_CAD_TOLERANCE } from "../core/cad/Tolerance.ts";
import { createCadRuntimeState, disposeCadRuntimeState, recordFeatureEvaluationResult, replaceFeatureShape } from "../core/evaluation/CadRuntimeState.ts";
import { evaluateFeature } from "../core/evaluation/FeatureEvaluation.ts";
import { OcctKernel } from "../core/kernel/OcctKernel.ts";
import { buildSketchProfiles } from "../core/sketch/SketchProfile.ts";
import { capturePersistentTopologyRef, resolvePersistentTopologyRef, TopologyResolutionError } from "../core/topology/TopologyResolver.ts";
import { getPlanarFaceFrame, PlanarFaceFrameError } from "../core/topology/PlanarFaceFrame.ts";

const wasm = new URL("../node_modules/occt-wasm/dist/occt-wasm.wasm", import.meta.url); let kernel;
const close = (actual, expected, tolerance = 1e-3) => assert.ok(Math.abs(actual - expected) <= tolerance, `${actual} != ${expected}`);
const makeDocument = (width = 100, extra = {}) => createCadDocument({ id: "m9", name: "M9", sketches: { Sketch01: { id: "Sketch01", name: "Sketch01", plane: { type: "XY", offset: 0 }, entities: { a:{id:"a",type:"line",start:{x:0,y:0},end:{x:width,y:0},construction:false}, b:{id:"b",type:"line",start:{x:width,y:0},end:{x:width,y:60},construction:false}, c:{id:"c",type:"line",start:{x:width,y:60},end:{x:0,y:60},construction:false}, d:{id:"d",type:"line",start:{x:0,y:60},end:{x:0,y:0},construction:false} }, entityOrder:["a","b","c","d"],constraints:{},dimensions:{} } }, features: { Extrude01:{id:"Extrude01",name:"Extrude01",type:"extrude",sketchId:"Sketch01",distance:20,direction:"positive",operation:"new",enabled:true,state:"clean",dependencies:[]}, ...extra }, featureOrder:["Extrude01",...Object.keys(extra)], });
const context = (document, runtime) => ({ document, runtime, kernel, tolerance: DEFAULT_CAD_TOLERANCE, buildProfiles: buildSketchProfiles });
const run = async (id, document, runtime) => { const result = await evaluateFeature(id, context(document, runtime)); assert.equal(result.status, "success", result.status === "failed" ? result.error.message : ""); recordFeatureEvaluationResult(runtime, result); await replaceFeatureShape(runtime, kernel, id, result.shape); return result; };
const topFace = async (shape) => (await kernel.getFaces(shape)).find((face) => face.normal?.z > .999);
const verticalEdge = async (shape) => (await kernel.getEdges(shape)).find((edge) => edge.curveType === "line" && Math.abs((edge.endMm?.z ?? 0) - (edge.startMm?.z ?? 0)) > 19);

before(async () => { kernel = new OcctKernel({ wasm }); await kernel.init(); }); after(async () => kernel?.dispose());

test("M9 planar frames are deterministic, right-handed, and reject non-planar Faces", async () => { const shape=await kernel.extrude({profile:{id:"p",outer:[{type:"line",start:[0,0],end:[100,0]},{type:"line",start:[100,0],end:[100,60]},{type:"line",start:[100,60],end:[0,60]},{type:"line",start:[0,60],end:[0,0]}],holes:[]},plane:{origin:{x:0,y:0,z:0},xAxis:{x:1,y:0,z:0},yAxis:{x:0,y:1,z:0},normal:{x:0,y:0,z:1}}},{distanceMm:20,direction:"positive"}); const faces=await kernel.getFaces(shape); const top=faces.find(f=>f.normal?.z>.999); const bottom=faces.find(f=>f.normal?.z<-.999); const frame=getPlanarFaceFrame(top); close(frame.origin.z,20); close(frame.normal.z,1); close(frame.xAxis.x*frame.yAxis.y-frame.xAxis.y*frame.yAxis.x,1); assert.ok(bottom); assert.throws(()=>getPlanarFaceFrame({ ...top, surfaceType:"torus" }), PlanarFaceFrameError); await kernel.disposeShape(shape); });

test("M9 persistent face and edge refs survive resize without runtime IDs in JSON", async () => { const runtime=createCadRuntimeState(); const first=makeDocument(); const extrude=await run("Extrude01",first,runtime); const face=await topFace(extrude.shape); const edge=await verticalEdge(extrude.shape); const faceRef=await capturePersistentTopologyRef("Extrude01",face.topology,runtime,kernel); const edgeRef=await capturePersistentTopologyRef("Extrude01",edge.topology,runtime,kernel); const serialized=JSON.stringify({faceRef,edgeRef,document:toSerializableCadDocument(first)}); assert.equal(/shape-|face-\d|edge-\d|shapeRevision|triangle/i.test(serialized),false); const second=makeDocument(150); await run("Extrude01",second,runtime); const resolvedFace=await resolvePersistentTopologyRef(faceRef,runtime,kernel); const resolvedEdge=await resolvePersistentTopologyRef(edgeRef,runtime,kernel); assert.ok((await kernel.getFaceInfo(resolvedFace)).normal.z>.999); assert.ok(Math.abs((await kernel.getEdgeInfo(resolvedEdge)).endMm.z-(await kernel.getEdgeInfo(resolvedEdge)).startMm.z)>19); await disposeCadRuntimeState(runtime,kernel); });

test("M9 Hole evaluates exact through-all and blind B-Rep cuts", async () => { const runtime=createCadRuntimeState(); let document=makeDocument(); const base=await run("Extrude01",document,runtime); const ref=await capturePersistentTopologyRef("Extrude01",(await topFace(base.shape)).topology,runtime,kernel); document=makeDocument(100,{Hole01:{id:"Hole01",name:"Hole01",type:"hole",targetFeatureId:"Extrude01",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["Extrude01"]}}); const through=await run("Hole01",document,runtime); close((await kernel.getShapeProperties(through.shape)).volumeMm3,120000-500*Math.PI,.1); document.features.Hole01.depth={type:"blind",valueMm:10}; const blind=await run("Hole01",document,runtime); close((await kernel.getShapeProperties(blind.shape)).volumeMm3,120000-250*Math.PI,.1); await disposeCadRuntimeState(runtime,kernel); });

test("M9 Fillet and Chamfer run against persisted vertical edges", async () => { const runtime=createCadRuntimeState(); const document=makeDocument(); const base=await run("Extrude01",document,runtime); const ref=await capturePersistentTopologyRef("Extrude01",(await verticalEdge(base.shape)).topology,runtime,kernel); document.features.Fillet01={id:"Fillet01",name:"Fillet01",type:"fillet",targetFeatureId:"Extrude01",edges:[ref],radiusMm:5,enabled:true,state:"clean",dependencies:["Extrude01"]}; const fillet=await run("Fillet01",document,runtime); close((await kernel.getShapeProperties(fillet.shape)).volumeMm3,120000-20*25*(1-Math.PI/4),.2); document.features.Chamfer01={id:"Chamfer01",name:"Chamfer01",type:"chamfer",targetFeatureId:"Extrude01",edges:[ref],distanceMm:5,enabled:true,state:"clean",dependencies:["Extrude01"]}; const chamfer=await run("Chamfer01",document,runtime); close((await kernel.getShapeProperties(chamfer.shape)).volumeMm3,119750,.2); await disposeCadRuntimeState(runtime,kernel); });

test("M9 topology resolver handles loss and multi-edge treatments safely", async () => { const runtime=createCadRuntimeState(); const document=makeDocument(); const base=await run("Extrude01",document,runtime); const vertical=(await kernel.getEdges(base.shape)).filter(edge=>edge.curveType==="line"&&Math.abs((edge.endMm?.z??0)-(edge.startMm?.z??0))>19).slice(0,2); const refs=await Promise.all(vertical.map(edge=>capturePersistentTopologyRef("Extrude01",edge.topology,runtime,kernel))); document.features.Fillet01={id:"Fillet01",name:"Fillet01",type:"fillet",targetFeatureId:"Extrude01",edges:refs,radiusMm:3,enabled:true,state:"clean",dependencies:["Extrude01"]}; const fillet=await run("Fillet01",document,runtime); assert.equal((await kernel.validate(fillet.shape)).valid,true); document.features.Chamfer01={id:"Chamfer01",name:"Chamfer01",type:"chamfer",targetFeatureId:"Extrude01",edges:refs,distanceMm:3,enabled:true,state:"clean",dependencies:["Extrude01"]}; const chamfer=await run("Chamfer01",document,runtime); assert.equal((await kernel.validate(chamfer.shape)).valid,true); await assert.rejects(()=>resolvePersistentTopologyRef({...refs[0],sourceFeatureId:"missing"},runtime,kernel),error=>error instanceof TopologyResolutionError&&error.code==="TOPOLOGY_REFERENCE_LOST"); await disposeCadRuntimeState(runtime,kernel); });

test("M9 serialized Hole data rebuilds without runtime topology identifiers", async () => { const firstRuntime=createCadRuntimeState(); const source=makeDocument(); const base=await run("Extrude01",source,firstRuntime); const ref=await capturePersistentTopologyRef("Extrude01",(await topFace(base.shape)).topology,firstRuntime,kernel); const withHole=makeDocument(100,{Hole01:{id:"Hole01",name:"Hole01",type:"hole",targetFeatureId:"Extrude01",targetFace:ref,center:{x:0,y:0},diameterMm:10,depth:{type:"throughAll"},enabled:true,state:"clean",dependencies:["Extrude01"]}}); const saved=JSON.stringify(toSerializableCadDocument(withHole)); assert.equal(/shape-|face-\d|edge-\d|shapeRevision|triangle/i.test(saved),false); await disposeCadRuntimeState(firstRuntime,kernel); const restored=JSON.parse(saved); const restoredRuntime=createCadRuntimeState(); await run("Extrude01",restored,restoredRuntime); const hole=await run("Hole01",restored,restoredRuntime); close((await kernel.getShapeProperties(hole.shape)).volumeMm3,120000-500*Math.PI,.1); await disposeCadRuntimeState(restoredRuntime,kernel); });
