CREATE TABLE cloud_asset_twin (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    project_id CHAR(36) NULL,
    twin_id CHAR(36) NOT NULL,
    factory_object_id VARCHAR(160) NULL,
    external_asset_id VARCHAR(160) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    note VARCHAR(500) NULL,
    created_by CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_asset_twin_target (workspace_id, twin_id, project_id, factory_object_id),
    KEY idx_cloud_asset_twin_workspace (workspace_id, status, updated_at),
    CONSTRAINT fk_cloud_asset_twin_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_asset_twin_project FOREIGN KEY (project_id) REFERENCES cloud_project (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_asset_twin_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_asset_twin_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cloud_tag_mapping (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    connector_id CHAR(36) NOT NULL,
    data_point_id CHAR(36) NULL,
    twin_id CHAR(36) NULL,
    source_tag VARCHAR(240) NOT NULL,
    semantic_key VARCHAR(160) NOT NULL,
    unit VARCHAR(32) NULL,
    transform_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    created_by CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_tag_mapping_source (connector_id, source_tag),
    KEY idx_cloud_tag_mapping_workspace (workspace_id, status, updated_at),
    CONSTRAINT fk_cloud_tag_mapping_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_tag_mapping_connector FOREIGN KEY (connector_id) REFERENCES cloud_connector (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_tag_mapping_point FOREIGN KEY (data_point_id) REFERENCES cloud_data_point (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_tag_mapping_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_tag_mapping_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cloud_connector_sync_run (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    connector_id CHAR(36) NOT NULL,
    mode VARCHAR(24) NOT NULL DEFAULT 'replay',
    status VARCHAR(24) NOT NULL DEFAULT 'queued',
    cursor_before BIGINT NOT NULL DEFAULT 0,
    cursor_after BIGINT NOT NULL DEFAULT 0,
    events_read INT NOT NULL DEFAULT 0,
    values_written INT NOT NULL DEFAULT 0,
    skipped_values INT NOT NULL DEFAULT 0,
    error_text VARCHAR(2000) NULL,
    client_mutation_id VARCHAR(120) NULL,
    requested_by CHAR(36) NOT NULL,
    requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_connector_sync_mutation (connector_id, requested_by, client_mutation_id),
    KEY idx_cloud_connector_sync_workspace (workspace_id, requested_at),
    KEY idx_cloud_connector_sync_connector (connector_id, requested_at),
    CONSTRAINT fk_cloud_connector_sync_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_connector_sync_connector FOREIGN KEY (connector_id) REFERENCES cloud_connector (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_connector_sync_requester FOREIGN KEY (requested_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
