-- ForgeCloud software runtime facts, telemetry windows, work orders,
-- quality outcomes and maintenance records.

ALTER TABLE cloud_runtime_event
    ADD COLUMN source_system VARCHAR(48) NOT NULL DEFAULT 'cloud' AFTER connector_id,
    ADD COLUMN external_event_id VARCHAR(160) NULL AFTER source_system,
    ADD COLUMN dedupe_key VARCHAR(220) NULL AFTER external_event_id,
    ADD COLUMN device_id CHAR(36) NULL AFTER dedupe_key,
    ADD COLUMN twin_id CHAR(36) NULL AFTER device_id,
    ADD COLUMN point_id CHAR(36) NULL AFTER twin_id,
    ADD COLUMN unit VARCHAR(32) NULL AFTER point_id,
    ADD COLUMN isolation_status VARCHAR(24) NOT NULL DEFAULT 'accepted' AFTER unit,
    ADD COLUMN isolation_reason VARCHAR(500) NULL AFTER isolation_status,
    ADD COLUMN received_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) AFTER created_at,
    ADD KEY idx_cloud_runtime_event_dedupe (workspace_id, dedupe_key),
    ADD KEY idx_cloud_runtime_event_twin_time (twin_id, occurred_at),
    ADD CONSTRAINT fk_cloud_runtime_event_device FOREIGN KEY (device_id) REFERENCES cloud_device (id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_cloud_runtime_event_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_cloud_runtime_event_point FOREIGN KEY (point_id) REFERENCES cloud_data_point (id) ON DELETE SET NULL;

CREATE TABLE cloud_telemetry_window (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    twin_id CHAR(36) NULL,
    data_point_id CHAR(36) NULL,
    metric VARCHAR(96) NOT NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    unit VARCHAR(32) NULL,
    min_value DECIMAL(30,8) NULL,
    max_value DECIMAL(30,8) NULL,
    avg_value DECIMAL(30,8) NULL,
    sample_count INT NOT NULL DEFAULT 0,
    valid_count INT NOT NULL DEFAULT 0,
    invalid_count INT NOT NULL DEFAULT 0,
    aggregation_version INT NOT NULL DEFAULT 1,
    source_system VARCHAR(48) NOT NULL DEFAULT 'forgecloud',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_telemetry_window_scope (workspace_id, data_point_id, twin_id, metric, window_start, window_end),
    KEY idx_cloud_telemetry_window_point_time (data_point_id, window_start),
    KEY idx_cloud_telemetry_window_twin_time (twin_id, window_start),
    CONSTRAINT fk_cloud_telemetry_window_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_telemetry_window_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_telemetry_window_point FOREIGN KEY (data_point_id) REFERENCES cloud_data_point (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cloud_work_order (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    project_id CHAR(36) NULL,
    twin_id CHAR(36) NULL,
    external_id VARCHAR(160) NULL,
    order_type VARCHAR(48) NOT NULL DEFAULT 'maintenance',
    title VARCHAR(180) NOT NULL,
    detail VARCHAR(2000) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'open',
    priority VARCHAR(16) NOT NULL DEFAULT 'normal',
    client_mutation_id VARCHAR(120) NULL,
    planned_at DATETIME(6) NULL,
    due_at DATETIME(6) NULL,
    actual_at DATETIME(6) NULL,
    source_system VARCHAR(48) NOT NULL DEFAULT 'forgecloud',
    assigned_to CHAR(36) NULL,
    created_by CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_work_order_external (workspace_id, external_id),
    UNIQUE KEY uq_cloud_work_order_mutation (workspace_id, created_by, client_mutation_id),
    KEY idx_cloud_work_order_workspace (workspace_id, status, priority, updated_at),
    KEY idx_cloud_work_order_twin (twin_id, status),
    CONSTRAINT fk_cloud_work_order_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_work_order_project FOREIGN KEY (project_id) REFERENCES cloud_project (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_work_order_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_work_order_assignee FOREIGN KEY (assigned_to) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_work_order_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cloud_quality_result (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    project_id CHAR(36) NULL,
    twin_id CHAR(36) NULL,
    work_order_id CHAR(36) NULL,
    lot_id VARCHAR(160) NULL,
    inspection_type VARCHAR(64) NOT NULL DEFAULT 'manual',
    result VARCHAR(24) NOT NULL DEFAULT 'unknown',
    score DECIMAL(12,6) NULL,
    evidence_ref VARCHAR(500) NULL,
    detail VARCHAR(2000) NULL,
    occurred_at DATETIME(6) NOT NULL,
    client_mutation_id VARCHAR(120) NULL,
    created_by CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_quality_mutation (workspace_id, created_by, client_mutation_id),
    KEY idx_cloud_quality_workspace_time (workspace_id, occurred_at),
    KEY idx_cloud_quality_lot (workspace_id, lot_id, occurred_at),
    KEY idx_cloud_quality_twin (twin_id, occurred_at),
    CONSTRAINT fk_cloud_quality_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_quality_project FOREIGN KEY (project_id) REFERENCES cloud_project (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_quality_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_quality_work_order FOREIGN KEY (work_order_id) REFERENCES cloud_work_order (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_quality_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cloud_maintenance_record (
    id CHAR(36) NOT NULL,
    workspace_id CHAR(36) NOT NULL,
    project_id CHAR(36) NULL,
    twin_id CHAR(36) NULL,
    work_order_id CHAR(36) NULL,
    fault_code VARCHAR(96) NULL,
    action VARCHAR(500) NOT NULL,
    result VARCHAR(24) NOT NULL DEFAULT 'reported',
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    downtime_seconds BIGINT NULL,
    detail VARCHAR(2000) NULL,
    client_mutation_id VARCHAR(120) NULL,
    created_by CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_cloud_maintenance_mutation (workspace_id, created_by, client_mutation_id),
    KEY idx_cloud_maintenance_workspace (workspace_id, result, created_at),
    KEY idx_cloud_maintenance_twin (twin_id, created_at),
    CONSTRAINT fk_cloud_maintenance_workspace FOREIGN KEY (workspace_id) REFERENCES cloud_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_cloud_maintenance_project FOREIGN KEY (project_id) REFERENCES cloud_project (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_maintenance_twin FOREIGN KEY (twin_id) REFERENCES cloud_twin (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_maintenance_work_order FOREIGN KEY (work_order_id) REFERENCES cloud_work_order (id) ON DELETE SET NULL,
    CONSTRAINT fk_cloud_maintenance_creator FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
