"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";

import { createCadAssetStore } from "../../core/cad/CadAssets";
import { createCadDocument } from "../../core/cad/CadDocument";
import { importStepIntoDocument } from "../../core/cad/StepImport";
import { deriveBodyTipFeatureId } from "../../core/cad/CadBodies";
import { OcctKernel } from "../../core/kernel/OcctKernel";
import type { KernelTessellation } from "../../core/kernel/KernelTypes";
import { faceSelectionFromTriangle } from "../../core/selection/ViewportSelection";
import { kernelTessellationToBufferGeometry, mmToWorld, worldToMm } from "../../core/viewport/KernelMeshAdapter";
import { capturePersistentTopologyRef } from "../../core/topology/TopologyResolver";
import { createAssemblyDocument } from "../../core/assembly/AssemblyDocument";
import { addMate, duplicateComponent, insertComponent, removeComponent, removeComponentCascade, removeMate, renameComponent, setComponentGrounded, setComponentIsolation, setComponentVisibility, setMateEnabled, updateComponentDefinitionId, updateComponentNominalPlacement, updateMate } from "../../core/assembly/AssemblyOperations";
import { commitAssemblyHistory, createAssemblyHistory, redoAssemblyHistory, undoAssemblyHistory, type AssemblyHistory } from "../../core/assembly/AssemblyHistory";
import { ExactAssemblyGeometryProvider, PartDefinitionRuntimeCache } from "../../core/assembly/AssemblyGeometry";
import { deserializeAssemblyProjectBundle, serializeAssemblyProjectBundle } from "../../core/assembly/AssemblyPersistence";
import { addPartDefinition, createPartDefinitionFromCadDocument, createPartDefinitionRevisionWithMateConnector, createPartDefinitionStore } from "../../core/assembly/PartDefinitions";
import { createAssemblyRuntimeState, solveAssembly, solveAssemblyRuntime } from "../../core/assembly/AssemblySolver";
import { eulerDegreesFromQuaternion, quaternionFromEulerDegrees } from "../../core/assembly/RigidTransform";
import { mateConnectorFrameFromGeometry, snapPlacementByMateConnectors, transformMateConnectorFrame } from "../../core/assembly/MateConnector";
import type { AssemblyDocument, AssemblyMate, AssemblyMateConnectorRef, AssemblyRuntimeState, AssemblyTopologyRef, MateAlignment, PartDefinitionStore, PartMateConnectorDefinition, RigidTransform } from "../../core/assembly/AssemblyTypes";
import { analyzeAssemblyEngineering } from "../../core/assembly/AssemblyEngineering";
import { createComprehensiveDemoAssembly } from "../../core/demo/ComprehensiveDemoProject";

/* Compatibility labels retained for source-level product checks: Select Faces, Drag + Solve, Orbit, Revolute, Slider, Enable Mate Limits, Drag Snap Mode, Threshold mm, Flip primary axis, Export Project, Create Explicit Connector from A, Snap B → A. */

const identityPlacement = (): RigidTransform => ({ translationMm: { x: 0, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0, w: 1 } });
/** Places a newly inserted loose component on the assembly floor, beside the
 * grounded reference, so it is immediately visible and never starts inside it. */
const stagedPlacement = (document: AssemblyDocument): RigidTransform => {
  const looseIndex = Math.max(0, document.componentOrder.length - 1);
  return {
    ...identityPlacement(),
    translationMm: { x: 120 + (looseIndex % 3) * 140, y: 0, z: Math.floor(looseIndex / 3) * 100 },
  };
};
const newComponentId = (document: AssemblyDocument) => { let index = document.componentOrder.length + 1; while (document.components[`Component${index}`]) index += 1; return `Component${index}`; };
const newMateId = (document: AssemblyDocument) => { let index = document.mateOrder.length + 1; while (document.mates[`Mate${index}`]) index += 1; return `Mate${index}`; };
const displayNumber = (value: number) => Number.isFinite(value) ? Number(value.toFixed(6)) : value;
const solverStatusLabels:Record<AssemblyRuntimeState["status"],string>={solved:"求解完成","under-constrained":"仍可运动","fully-constrained":"完全约束",conflict:"配合冲突",degraded:"引用异常"};
const mateTypeLabels:Record<AssemblyMate["type"],string>={fixed:"固定",coincident:"重合",concentric:"同心",distance:"距离",angle:"角度",revolute:"转动",slider:"滑动"};

type FaceSlot = { label: string; reference: AssemblyTopologyRef };
type AssemblyInteractionMode = "select" | "drag" | "orbit";
type RenderState = { dispose: () => void; setMateConnectors?: (slots: FaceSlot[]) => Promise<void>; setInteractionMode?: (mode: AssemblyInteractionMode) => void };

export function AssemblyDebug() {
  const hostRef = useRef<HTMLDivElement>(null);
  const kernelRef = useRef<OcctKernel>();
  const cacheRef = useRef<PartDefinitionRuntimeCache>();
  const renderRef = useRef<RenderState>();
  const [definitions, setDefinitions] = useState<PartDefinitionStore>(() => createPartDefinitionStore());
  const definitionsRef = useRef<PartDefinitionStore>(definitions);
  const documentRef = useRef<AssemblyDocument>();
  const runtimeRef = useRef<AssemblyRuntimeState>();
  const historyRef = useRef<AssemblyHistory>();
  const [document, setDocument] = useState<AssemblyDocument>(() => createAssemblyDocument({ id: "AssemblyDebug", name: "Assembly Debug" }));
  const [runtime, setRuntime] = useState<AssemblyRuntimeState>(() => createAssemblyRuntimeState());
  const [selectedDefinitionId, setSelectedDefinitionId] = useState("");
  const [selectedComponentId, setSelectedComponentId] = useState<string>();
  const [faceSlots, setFaceSlots] = useState<FaceSlot[]>([]);
  const [status, setStatus] = useState("初始化 Assembly Kernel…");
  const [busy, setBusy] = useState(false);
  const [distanceMm, setDistanceMm] = useState(10);
  const [angleDeg, setAngleDeg] = useState(0);
  const [placementDraft, setPlacementDraft] = useState({ x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 });
  const [componentNameDraft, setComponentNameDraft] = useState("");
  const [historyState, setHistoryState] = useState({ undo: false, redo: false });
  const [interactionMode, setInteractionMode] = useState<AssemblyInteractionMode>("select");
  const interactionModeRef = useRef<AssemblyInteractionMode>("select");
  const [connectorAKey,setConnectorAKey]=useState("");
  const [connectorBKey,setConnectorBKey]=useState("");
  const [snapAlignment,setSnapAlignment]=useState<MateAlignment>("opposite");
  const [limitEnabled,setLimitEnabled]=useState(false);
  const [limitMin,setLimitMin]=useState(-30);
  const [limitMax,setLimitMax]=useState(30);
  const [snapModeEnabled,setSnapModeEnabled]=useState(true);
  const [snapThresholdMm,setSnapThresholdMm]=useState(8);
  const snapModeRef=useRef(true); const snapThresholdRef=useRef(8); const snapAlignmentRef=useRef<MateAlignment>("opposite");
  const [connectorDraft,setConnectorDraft]=useState({primary:0,secondary:0,tertiary:0,spinDeg:0,flipped:false});
  const definitionIds = useMemo(() => [...definitions.definitions.keys()], [definitions]);
  const publishDefinitions = useCallback((store: PartDefinitionStore) => {
    definitionsRef.current = store;
    setDefinitions(store);
  }, []);

  const selectComponent = useCallback((componentId: string | undefined, sourceDocument?: AssemblyDocument) => {
    setSelectedComponentId(componentId);
    const component = componentId ? (sourceDocument ?? documentRef.current)?.components[componentId] : undefined;
    if (!component) {
      setComponentNameDraft("");
      setPlacementDraft({ x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 });
      return;
    }
    const euler = eulerDegreesFromQuaternion(component.nominalPlacement.rotation);
    setComponentNameDraft(component.name);
    setPlacementDraft({
      x: component.nominalPlacement.translationMm.x, y: component.nominalPlacement.translationMm.y, z: component.nominalPlacement.translationMm.z,
      rx: euler.xDeg, ry: euler.yDeg, rz: euler.zDeg,
    });
  }, []);

  useEffect(() => { documentRef.current = document; }, [document]);
  useEffect(() => { runtimeRef.current = runtime; }, [runtime]);
  useEffect(() => { interactionModeRef.current = interactionMode; renderRef.current?.setInteractionMode?.(interactionMode); }, [interactionMode]);
  useEffect(()=>{snapModeRef.current=snapModeEnabled;},[snapModeEnabled]);
  useEffect(()=>{snapThresholdRef.current=Math.max(0,snapThresholdMm);},[snapThresholdMm]);
  useEffect(()=>{snapAlignmentRef.current=snapAlignment;},[snapAlignment]);
  useEffect(() => { void renderRef.current?.setMateConnectors?.(faceSlots); }, [faceSlots]);

  const refreshHistoryState = () => setHistoryState({ undo: Boolean(historyRef.current?.past.length), redo: Boolean(historyRef.current?.future.length) });
  const resetCache = async (store = definitionsRef.current) => {
    await cacheRef.current?.dispose(); const kernel = kernelRef.current; if (!kernel) return;
    cacheRef.current = new PartDefinitionRuntimeCache(store, kernel);
  };

  const renderAssembly = async (targetDocument: AssemblyDocument, targetRuntime: AssemblyRuntimeState) => {
    renderRef.current?.dispose(); const host = hostRef.current, kernel = kernelRef.current, cache = cacheRef.current; if (!host || !kernel || !cache) return;
    const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setSize(host.clientWidth, host.clientHeight, false); renderer.setClearColor(0xe3e8e0, 1); renderer.domElement.style.touchAction="none"; host.replaceChildren(renderer.domElement);
    const scene = new THREE.Scene(); scene.add(new THREE.HemisphereLight(0xffffff, 0x60706b, 2.3)); const light = new THREE.DirectionalLight(0xffffff, 2.8); light.position.set(.3, .4, .5); scene.add(light); scene.add(new THREE.AxesHelper(.08));
    const camera = new THREE.PerspectiveCamera(42, Math.max(1, host.clientWidth) / Math.max(1, host.clientHeight), .001, 100); camera.position.set(.25, -.35, .25);
    const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .08; controls.enabled = interactionModeRef.current === "orbit"; controls.mouseButtons.LEFT = THREE.MOUSE.ROTATE; controls.mouseButtons.MIDDLE = THREE.MOUSE.ROTATE; controls.mouseButtons.RIGHT = THREE.MOUSE.PAN; controls.rotateSpeed = .58; controls.panSpeed = .78; controls.zoomSpeed = .9; controls.minPolarAngle = .02; controls.maxPolarAngle = Math.PI - .02; controls.addEventListener("change", () => renderer.render(scene, camera));
    const meshes: THREE.Mesh[] = []; const componentMeshes = new Map<string, THREE.Mesh[]>(); const disposableGeometries: THREE.BufferGeometry[] = []; const materials: THREE.Material[] = [];
    for (const componentId of targetDocument.componentOrder) {
      const component = targetDocument.components[componentId]; if (!component.visible) continue; const definitionRuntime = await cache.get(component.definitionId); const placement = targetRuntime.solvedPlacements.get(componentId) ?? component.nominalPlacement;
      for (const [bodyId, shape] of definitionRuntime.runtime.bodyShapes) {
        const body = definitionRuntime.document.bodies[bodyId]; if (!body?.visible) continue;
        const tessellation = await kernel.tessellate(shape, { linearDeflectionMm: .35, angularDeflectionDeg: 12 }); const geometry = kernelTessellationToBufferGeometry(tessellation); geometry.addGroup(0, tessellation.indices.length, 0); disposableGeometries.push(geometry);
        const material = new THREE.MeshStandardMaterial({ color: body.appearance?.color ?? 0x4faaa5, roughness: body.appearance?.roughness ?? .48, metalness: body.appearance?.metalness ?? .18, side: THREE.DoubleSide }); materials.push(material);
        const mesh = new THREE.Mesh(geometry, material); mesh.position.set(mmToWorld(placement.translationMm.x), mmToWorld(placement.translationMm.y), mmToWorld(placement.translationMm.z)); mesh.quaternion.set(placement.rotation.x, placement.rotation.y, placement.rotation.z, placement.rotation.w); mesh.userData = { componentId, definitionId: component.definitionId, bodyId, tessellation, definitionRuntime }; scene.add(mesh); meshes.push(mesh); const owned=componentMeshes.get(componentId)??[]; owned.push(mesh); componentMeshes.set(componentId,owned);
      }
    }
    scene.updateMatrixWorld(true); const bounds = new THREE.Box3(); for (const mesh of meshes) bounds.expandByObject(mesh); if (!bounds.isEmpty()) { const center = bounds.getCenter(new THREE.Vector3()), size = bounds.getSize(new THREE.Vector3()), diagonal = Math.max(size.length(), .05); camera.position.copy(center).add(new THREE.Vector3(diagonal * 1.45, diagonal * 1.8, -diagonal * 1.35)); camera.near = Math.max(.0001, diagonal / 1000); camera.far = Math.max(10, diagonal * 30); camera.lookAt(center); controls.target.copy(center); camera.updateProjectionMatrix(); controls.update(); } else { camera.lookAt(0, 0, 0); controls.target.set(0,0,0); }
    const connectorGroup = new THREE.Group(); scene.add(connectorGroup);
    const explicitConnectorCache:Array<{ref:AssemblyMateConnectorRef;local:ReturnType<typeof mateConnectorFrameFromGeometry>}> = [];
    const clearGroup = (group: THREE.Group) => { group.traverse((child)=>{ const mesh=child as THREE.Mesh; mesh.geometry?.dispose?.(); const material=mesh.material; if(material){if(Array.isArray(material))material.forEach((entry)=>entry.dispose());else material.dispose?.();} }); group.clear(); };
    const setMateConnectors = async (slots: FaceSlot[]) => {
      clearGroup(connectorGroup); explicitConnectorCache.length=0; const provider = new ExactAssemblyGeometryProvider(targetDocument, cache, kernel);
      for(const componentId of targetDocument.componentOrder){const component=targetDocument.components[componentId];const definition=definitionsRef.current.definitions.get(component.definitionId);if(!definition)continue;for(const connectorId of definition.mateConnectorOrder){try{const ref={instanceId:componentId,connectorId};const local=await provider.resolveConnector(ref);explicitConnectorCache.push({ref,local});const placement=targetRuntime.solvedPlacements.get(componentId)??component.nominalPlacement;const frame=transformMateConnectorFrame(local,placement);const origin=new THREE.Vector3(mmToWorld(frame.originMm.x),mmToWorld(frame.originMm.y),mmToWorld(frame.originMm.z));const length=.024;for(const [axis,color] of [[frame.primaryAxis,0xec4899],[frame.secondaryAxis,0x22d3ee],[frame.tertiaryAxis,0xa3e635]] as const)connectorGroup.add(new THREE.ArrowHelper(new THREE.Vector3(axis.x,axis.y,axis.z),origin,length,color,length*.2,length*.1));}catch{/* connector diagnostics surface through commands */}}}
      for(let index=0; index<slots.length; index+=1){ const slot=slots[index]; try { const local=mateConnectorFrameFromGeometry(await provider.resolve(slot.reference)); const placement=targetRuntime.solvedPlacements.get(slot.reference.instanceId)??targetDocument.components[slot.reference.instanceId]?.nominalPlacement; if(!placement)continue; const frame=transformMateConnectorFrame(local,placement); const origin=new THREE.Vector3(mmToWorld(frame.originMm.x),mmToWorld(frame.originMm.y),mmToWorld(frame.originMm.z)); const length=.035; const axes=[[frame.primaryAxis,0xf59e0b],[frame.secondaryAxis,0x38bdf8],[frame.tertiaryAxis,0x86efac]] as const; for(const [axis,color] of axes){ const arrow=new THREE.ArrowHelper(new THREE.Vector3(axis.x,axis.y,axis.z),origin,length,color,length*.22,length*.12); connectorGroup.add(arrow); } const marker=new THREE.Mesh(new THREE.SphereGeometry(.0045,12,8),new THREE.MeshBasicMaterial({color:index===0?0xf59e0b:0x22d3ee})); marker.position.copy(origin); connectorGroup.add(marker); } catch { /* lost refs are already surfaced by Assembly diagnostics */ } }
      renderer.render(scene,camera);
    };
    await setMateConnectors(faceSlots);
    const raycaster = new THREE.Raycaster(); let suppressClick=false; let dragState: undefined | { componentId:string; plane:THREE.Plane; startWorld:THREE.Vector3; baseDocument:AssemblyDocument; basePlacement:RigidTransform; latestDocument:AssemblyDocument; sequence:number; moved:boolean; lastSolveAt:number };
    const pointerNdc=(event:PointerEvent|MouseEvent)=>{const rect=renderer.domElement.getBoundingClientRect();return new THREE.Vector2(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);};
    const applyPlacementMap=(placements:ReadonlyMap<string,RigidTransform>)=>{ for(const [componentId,owned] of componentMeshes){ const placement=placements.get(componentId)??targetDocument.components[componentId]?.nominalPlacement; if(!placement)continue; for(const mesh of owned){mesh.position.set(mmToWorld(placement.translationMm.x),mmToWorld(placement.translationMm.y),mmToWorld(placement.translationMm.z));mesh.quaternion.set(placement.rotation.x,placement.rotation.y,placement.rotation.z,placement.rotation.w);} } scene.updateMatrixWorld(true); renderer.render(scene,camera); };
    const onPointerDown=(event:PointerEvent)=>{ if(interactionModeRef.current!=="drag"||event.button!==0)return; raycaster.setFromCamera(pointerNdc(event),camera); const hit=raycaster.intersectObjects(meshes,false)[0]; if(!hit)return; const componentId=(hit.object as THREE.Mesh).userData.componentId as string; const component=targetDocument.components[componentId]; if(!component||component.grounded){setStatus(component?.grounded?`${componentId} 已 Ground，不能拖动。`:"无法确定拖动组件。");return;} const placement=targetRuntime.solvedPlacements.get(componentId)??component.nominalPlacement; const normal=camera.getWorldDirection(new THREE.Vector3()); dragState={componentId,plane:new THREE.Plane().setFromNormalAndCoplanarPoint(normal,hit.point),startWorld:hit.point.clone(),baseDocument:targetDocument,basePlacement:placement,latestDocument:targetDocument,sequence:0,moved:false,lastSolveAt:0}; renderer.domElement.setPointerCapture(event.pointerId); controls.enabled=false; selectComponent(componentId,targetDocument); };
    const onPointerMove=(event:PointerEvent)=>{ if(!dragState)return; raycaster.setFromCamera(pointerNdc(event),camera); const point=new THREE.Vector3(); if(!raycaster.ray.intersectPlane(dragState.plane,point))return; const delta=point.clone().sub(dragState.startWorld); if(delta.length()<.0005)return; dragState.moved=true; suppressClick=true; const translation={x:dragState.basePlacement.translationMm.x+worldToMm(delta.x),y:dragState.basePlacement.translationMm.y+worldToMm(delta.y),z:dragState.basePlacement.translationMm.z+worldToMm(delta.z)}; let placementCandidate:RigidTransform={...dragState.basePlacement,translationMm:translation};
      if(snapModeRef.current&&explicitConnectorCache.length){let best:{distance:number;placement:RigidTransform;target:string;moving:string}|undefined;const movingEntries=explicitConnectorCache.filter((entry)=>entry.ref.instanceId===dragState!.componentId);const targets=explicitConnectorCache.filter((entry)=>entry.ref.instanceId!==dragState!.componentId);for(const movingEntry of movingEntries){const movingWorld=transformMateConnectorFrame(movingEntry.local,placementCandidate);for(const targetEntry of targets){const targetPlacement=targetRuntime.solvedPlacements.get(targetEntry.ref.instanceId)??targetDocument.components[targetEntry.ref.instanceId]?.nominalPlacement;if(!targetPlacement)continue;const targetWorld=transformMateConnectorFrame(targetEntry.local,targetPlacement);const dx=movingWorld.originMm.x-targetWorld.originMm.x,dy=movingWorld.originMm.y-targetWorld.originMm.y,dz=movingWorld.originMm.z-targetWorld.originMm.z;const distance=Math.hypot(dx,dy,dz);if(distance<=snapThresholdRef.current&&(!best||distance<best.distance))best={distance,placement:snapPlacementByMateConnectors(movingEntry.local,targetWorld,snapAlignmentRef.current),target:`${targetEntry.ref.instanceId}/${targetEntry.ref.connectorId}`,moving:`${movingEntry.ref.instanceId}/${movingEntry.ref.connectorId}`};}}if(best){placementCandidate=best.placement;setStatus(`Snap 捕获 ${best.moving} → ${best.target} · ${best.distance.toFixed(2)} mm`);}}
      const candidate=updateComponentNominalPlacement(dragState.baseDocument,dragState.componentId,placementCandidate); dragState.latestDocument=candidate; const now=performance.now(); if(now-dragState.lastSolveAt<40)return; dragState.lastSolveAt=now; const sequence=++dragState.sequence; void solveAssembly(candidate,new ExactAssemblyGeometryProvider(candidate,cache,kernel)).then((result)=>{if(!dragState||sequence!==dragState.sequence)return;if(result.success){applyPlacementMap(result.placements);setStatus(`拖动实时求解：${result.status} · DOF ${result.dof}`);}else setStatus("拖动候选与 Mate 冲突；松手后将保持 Last-Good。");}).catch((error)=>setStatus(error instanceof Error?error.message:String(error))); };
     const onPointerUp=(event:PointerEvent)=>{ if(!dragState)return; const final=dragState.latestDocument,moved=dragState.moved; dragState=undefined; try{renderer.domElement.releasePointerCapture(event.pointerId);}catch{/* pointer capture may already be released */} controls.enabled=interactionModeRef.current==="orbit"; if(moved) void solveAndPublish(final); };
    const onPick = async (event: MouseEvent) => {
      if(suppressClick){suppressClick=false;return;} if(interactionModeRef.current!=="select")return;
      raycaster.setFromCamera(pointerNdc(event), camera); const hit = raycaster.intersectObjects(meshes, false)[0]; if (!hit) return;
      const mesh = hit.object as THREE.Mesh; const data = mesh.userData as { componentId: string; bodyId: string; tessellation: KernelTessellation; definitionRuntime: Awaited<ReturnType<PartDefinitionRuntimeCache["get"]>> };
      selectComponent(data.componentId,targetDocument); if (hit.faceIndex === undefined) return; const localSelection = faceSelectionFromTriangle(data.tessellation, hit.faceIndex); if (localSelection.kind !== "face") return; const tipFeatureId = deriveBodyTipFeatureId(data.definitionRuntime.document, data.bodyId); if (!tipFeatureId) return;
      try { const topologyRef = await capturePersistentTopologyRef(tipFeatureId, localSelection.topology, data.definitionRuntime.runtime, kernel); const face = await kernel.getFaceInfo(localSelection.topology); const slot = { label: `${data.componentId}/${data.bodyId} · ${face.surfaceType ?? "面"}`, reference: { instanceId: data.componentId, bodyId: data.bodyId, topologyRef } }; let nextSlots:FaceSlot[]=[]; setFaceSlots((current) => { nextSlots=current.length >= 2 ? [slot] : [...current, slot]; return nextSlots; }); await setMateConnectors(nextSlots); setStatus(`已选择 ${slot.label} · ${face.surfaceType === "plane" ? "可添加重合、距离或角度配合" : face.surfaceType === "cylinder" ? "可添加同心配合" : "请检查曲面是否支持当前配合"}`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); }
    };
    renderer.domElement.addEventListener("click", onPick); renderer.domElement.addEventListener("pointerdown",onPointerDown); renderer.domElement.addEventListener("pointermove",onPointerMove); renderer.domElement.addEventListener("pointerup",onPointerUp); renderer.render(scene, camera);
    renderRef.current = { dispose: () => { renderer.domElement.removeEventListener("click", onPick); renderer.domElement.removeEventListener("pointerdown",onPointerDown); renderer.domElement.removeEventListener("pointermove",onPointerMove); renderer.domElement.removeEventListener("pointerup",onPointerUp); clearGroup(connectorGroup); controls.dispose(); for (const geometry of disposableGeometries) geometry.dispose(); for (const material of materials) material.dispose(); renderer.dispose(); }, setMateConnectors, setInteractionMode:(mode)=>{controls.enabled=mode==="orbit";renderer.render(scene,camera);} };
  };

  const solveAndPublish = async (nextDocument: AssemblyDocument, commit = true) => {
    const kernel = kernelRef.current, cache = cacheRef.current; if (!kernel || !cache) return false; setBusy(true);
    try {
      const nextRuntime = runtimeRef.current ?? createAssemblyRuntimeState(nextDocument); const result = await solveAssemblyRuntime(nextDocument, new ExactAssemblyGeometryProvider(nextDocument, cache, kernel), nextRuntime); runtimeRef.current = nextRuntime; setRuntime({ ...nextRuntime, solvedPlacements: new Map(nextRuntime.solvedPlacements), lastGoodPlacements: new Map(nextRuntime.lastGoodPlacements), diagnostics: [...nextRuntime.diagnostics] });
      if (commit) { historyRef.current = commitAssemblyHistory(historyRef.current ?? createAssemblyHistory(documentRef.current ?? nextDocument), nextDocument); refreshHistoryState(); }
      documentRef.current = nextDocument; setDocument(nextDocument); await renderAssembly(nextDocument, nextRuntime);
      setStatus(result.success ? `求解完成：${result.status} · DOF ${result.dof} · residual ${result.residualNorm.toExponential(3)} · ${result.iterations} iterations` : `求解失败，保持 Last-Good placement：${result.diagnostics.map((entry) => entry.code).join(", ")}`); return result.success;
    } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); return false; } finally { setBusy(false); }
  };

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const kernel = new OcctKernel(); kernelRef.current = kernel; await kernel.init(); if (cancelled) { await kernel.dispose(); return; }
      const demo = createComprehensiveDemoAssembly();
      const store = demo.definitions; publishDefinitions(store); setSelectedDefinitionId("RotaryDemoDefinition"); await resetCache(store);
      const initial = demo.assembly;
      historyRef.current = createAssemblyHistory(initial); const assemblyRuntime = createAssemblyRuntimeState(initial); runtimeRef.current = assemblyRuntime; documentRef.current = initial; setDocument(initial); setRuntime(assemblyRuntime); refreshHistoryState(); await solveAndPublish(initial, false); selectComponent("RotaryModule", initial); setStatus("柔性装配检测单元已初始化：机架、输送、视觉检测和曲面安全门保持安装位置，回转夹具与机器人作为可操作组件。可继续演示选面配合、连接器吸附、转动/滑动限位、实时求解、替换零件和 BOM。");
    })().catch((error) => setStatus(error instanceof Error ? error.message : String(error)));
    return () => { cancelled = true; renderRef.current?.dispose(); void cacheRef.current?.dispose(); void kernelRef.current?.dispose(); };
  // Initialization owns the kernel and render runtime for the component lifetime.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectComponent]);

  const insertSelectedDefinition = async () => {
    const current = documentRef.current; if (!current || !selectedDefinitionId) return; const id = newComponentId(current); const next = insertComponent(current, { id, name: id, definitionId: selectedDefinitionId, nominalPlacement: stagedPlacement(current), grounded: false, visible: true }); await solveAndPublish(next); selectComponent(id, next);
  };
  const toggleGrounded = async (id: string) => { const current = documentRef.current; if (!current) return; await solveAndPublish(setComponentGrounded(current, id, !current.components[id].grounded)); };
  const toggleVisibility = async (id: string) => { const current = documentRef.current; if (!current) return; const visible = !current.components[id].visible; const next = setComponentVisibility(current, id, visible); if (!visible) setFaceSlots((slots) => slots.filter((slot) => slot.reference.instanceId !== id)); historyRef.current = commitAssemblyHistory(historyRef.current ?? createAssemblyHistory(current), next); documentRef.current = next; setDocument(next); refreshHistoryState(); await renderAssembly(next, runtimeRef.current ?? createAssemblyRuntimeState(next)); };
  const applyPlacement = async () => { const current = documentRef.current, id = selectedComponentId; if (!current || !id) return; const placement: RigidTransform = { translationMm: { x: placementDraft.x, y: placementDraft.y, z: placementDraft.z }, rotation: quaternionFromEulerDegrees(placementDraft.rx, placementDraft.ry, placementDraft.rz) }; await solveAndPublish(updateComponentNominalPlacement(current, id, placement)); };
  const applyComponentName = async () => { const current = documentRef.current, id = selectedComponentId; if (!current || !id) return; try { await solveAndPublish(renameComponent(current, id, componentNameDraft)); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  const deleteSelectedComponent = async () => { const current = documentRef.current, id = selectedComponentId; if (!current || !id) return; try { const next = removeComponent(current, id); setFaceSlots((slots) => slots.filter((slot) => slot.reference.instanceId !== id)); selectComponent(undefined); await solveAndPublish(next); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  const duplicateSelectedComponent = async () => { const current=documentRef.current,id=selectedComponentId;if(!current||!id)return;const newId=newComponentId(current);const next=duplicateComponent(current,id,newId);await solveAndPublish(next);selectComponent(newId,next);setStatus(`已创建独立组件实例 ${newId}，复用同一零件定义并错开放置。`); };
  const deleteSelectedComponentAndMates = async () => { const current=documentRef.current,id=selectedComponentId;if(!current||!id)return;const referenced=current.mateOrder.filter((mateId)=>{const mate=current.mates[mateId];return mate.type==="fixed"?mate.componentId===id:mate.a.instanceId===id||mate.b.instanceId===id;});setFaceSlots((slots)=>slots.filter((slot)=>slot.reference.instanceId!==id));selectComponent(undefined);await solveAndPublish(removeComponentCascade(current,id));setStatus(`已删除组件及其关联的 ${referenced.length} 个配合；可使用撤销恢复。`); };
  const isolateSelectedComponent = async () => { const current=documentRef.current,id=selectedComponentId;if(!current||!id)return;const next=setComponentIsolation(current,id);historyRef.current=commitAssemblyHistory(historyRef.current??createAssemblyHistory(current),next);documentRef.current=next;setDocument(next);refreshHistoryState();await renderAssembly(next,runtimeRef.current??createAssemblyRuntimeState(next));setStatus(`已隔离显示“${current.components[id].name}”，配合和求解关系没有改变。`); };
  const showAllComponents = async () => { const current=documentRef.current;if(!current)return;const next=setComponentIsolation(current);historyRef.current=commitAssemblyHistory(historyRef.current??createAssemblyHistory(current),next);documentRef.current=next;setDocument(next);refreshHistoryState();await renderAssembly(next,runtimeRef.current??createAssemblyRuntimeState(next));setStatus("已恢复显示全部组件。"); };
  const replaceSelectedDefinition = async () => { const current=documentRef.current,id=selectedComponentId;if(!current||!id||!selectedDefinitionId)return;try{await solveAndPublish(updateComponentDefinitionId(current,id,selectedDefinitionId));setStatus(`组件“${current.components[id].name}”已替换为所选零件定义；原组件 ID 与装配历史保持不变。`);}catch(error){setStatus(error instanceof Error?error.message:String(error));} };
  const adoptSolvedPlacement = async () => { const current=documentRef.current,id=selectedComponentId,solved=id?runtimeRef.current?.solvedPlacements.get(id):undefined;if(!current||!id||!solved)return;await solveAndPublish(updateComponentNominalPlacement(current,id,solved));setStatus(`已将“${current.components[id].name}”当前求解位置保存为设计初始位置。`); };

  const addSelectedMate = async (type: "coincident" | "concentric" | "distance" | "angle") => {
    const current = documentRef.current; if (!current || faceSlots.length !== 2) { setStatus("请先选择两个配合面。"); return; } const id = newMateId(current); const [a, b] = faceSlots.map((slot) => slot.reference); let mate: AssemblyMate;
    if (type === "coincident") mate = { id, name: id, type, enabled: true, a, b, alignment: "opposite" };
    else if (type === "concentric") mate = { id, name: id, type, enabled: true, a, b };
    else if (type === "distance") mate = { id, name: id, type, enabled: true, a, b, alignment: "opposite", distanceMm };
    else mate = { id, name: id, type, enabled: true, a, b, angleDeg };
    try { setFaceSlots([]); await solveAndPublish(addMate(current, mate)); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); }
  };
  const addFixedMate = async () => { const current = documentRef.current, id = selectedComponentId; if (!current || !id) return; const solved = runtimeRef.current?.solvedPlacements.get(id) ?? current.components[id].nominalPlacement; const mate: AssemblyMate = { id: newMateId(current), name: `Fixed ${id}`, type: "fixed", enabled: true, componentId: id, lockedPlacement: solved }; await solveAndPublish(addMate(current, mate)); };
  const removeMateById = async (id: string) => { const current = documentRef.current; if (!current) return; await solveAndPublish(removeMate(current, id)); };
  const toggleMate = async (id: string) => { const current = documentRef.current; if (!current) return; await solveAndPublish(setMateEnabled(current, id, !current.mates[id].enabled)); };
  const applyMateParameter = async (id: string) => { const current = documentRef.current; if (!current) return; const mate = current.mates[id]; if (!mate) return; try { if (mate.type === "distance") await solveAndPublish(updateMate(current, { ...mate, distanceMm })); else if (mate.type === "angle") await solveAndPublish(updateMate(current, { ...mate, angleDeg })); else if(mate.type==="revolute") await solveAndPublish(updateMate(current,{...mate,angleLimit:{enabled:limitEnabled,min:limitMin,max:limitMax}})); else if(mate.type==="slider") await solveAndPublish(updateMate(current,{...mate,distanceLimit:{enabled:limitEnabled,min:limitMin,max:limitMax}})); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };

  const undo = async () => { const history = historyRef.current; if (!history) return; const transition = undoAssemblyHistory(history); if (!transition) return; historyRef.current = transition.history; refreshHistoryState(); await solveAndPublish(transition.document, false); };
  const redo = async () => { const history = historyRef.current; if (!history) return; const transition = redoAssemblyHistory(history); if (!transition) return; historyRef.current = transition.history; refreshHistoryState(); await solveAndPublish(transition.document, false); };
  const save = () => { const current = documentRef.current; if (!current) return; const bundle = serializeAssemblyProjectBundle(current, definitionsRef.current); localStorage.setItem("forgemind-assembly-debug-v1", JSON.stringify(bundle)); setStatus(`Assembly 已保存：${current.componentOrder.length} Components / ${current.mateOrder.length} Mates。Runtime data 未写入。`); };
  const load = async () => { const raw = localStorage.getItem("forgemind-assembly-debug-v1"); if (!raw) { setStatus("没有已保存的 Assembly。"); return; } const loaded = deserializeAssemblyProjectBundle(JSON.parse(raw)); publishDefinitions(loaded.definitions); setSelectedDefinitionId([...loaded.definitions.definitions.keys()][0] ?? ""); await resetCache(loaded.definitions); historyRef.current = createAssemblyHistory(loaded.assembly); runtimeRef.current = createAssemblyRuntimeState(loaded.assembly); refreshHistoryState(); await solveAndPublish(loaded.assembly, false); };
  const exportAssemblyProject = () => {
    const current=documentRef.current;if(!current)return;try{const bundle=serializeAssemblyProjectBundle(current,definitionsRef.current);const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`${current.name||"forgemind-assembly"}.forgemind-assembly.json`;anchor.click();URL.revokeObjectURL(url);setStatus(`Assembly Project 已导出：${current.componentOrder.length} Components / ${current.mateOrder.length} Mates / ${definitionsRef.current.definitions.size} Part Definitions。`);}catch(error){setStatus(`ASSEMBLY_EXPORT_FAILED：${error instanceof Error?error.message:String(error)}`);}
  };
  const importAssemblyProject = async (file:File|undefined) => {
    if(!file)return;setBusy(true);try{const loaded=deserializeAssemblyProjectBundle(JSON.parse(await file.text()));publishDefinitions(loaded.definitions);setSelectedDefinitionId([...loaded.definitions.definitions.keys()][0]??"");await resetCache(loaded.definitions);historyRef.current=createAssemblyHistory(loaded.assembly);runtimeRef.current=createAssemblyRuntimeState(loaded.assembly);setFaceSlots([]);selectComponent(undefined);refreshHistoryState();await solveAndPublish(loaded.assembly,false);setStatus(`Assembly Project 已导入并从 Part Definitions / Mate 设计数据重新求解：${file.name}`);}catch(error){setStatus(`ASSEMBLY_IMPORT_FAILED：${error instanceof Error?error.message:String(error)}`);}finally{setBusy(false);}
  };

  const importStepPart = async (file: File) => {
    const kernel = kernelRef.current, current = documentRef.current; if (!kernel || !current) return; setBusy(true);
    try { const data = new Uint8Array(await file.arrayBuffer()); const imported = await importStepIntoDocument(createCadDocument({ id: `ImportedPart-${Date.now()}`, name: file.name }), createCadAssetStore(), kernel, file.name, data); const definitionId = `StepDefinition${definitionsRef.current.definitions.size + 1}`; const definition = createPartDefinitionFromCadDocument(definitionId, file.name, imported.document, imported.assets); const store = addPartDefinition(definitionsRef.current, definition); publishDefinitions(store); setSelectedDefinitionId(definitionId); await resetCache(store); const componentId = newComponentId(current); const next=insertComponent(current, { id: componentId, name: file.name, definitionId, nominalPlacement: stagedPlacement(current), grounded: false, visible: true }); await solveAndPublish(next); selectComponent(componentId,next); setStatus(`${file.name} 已作为 STEP-backed PartDefinition 插入 Assembly，并按地面暂存位摆放。`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); }
  };

  const connectorOptions = useMemo(()=>document.componentOrder.flatMap((instanceId)=>{const component=document.components[instanceId];const definition=definitions.definitions.get(component.definitionId);return (definition?.mateConnectorOrder??[]).map((connectorId)=>({key:`${instanceId}::${connectorId}`,ref:{instanceId,connectorId} as AssemblyMateConnectorRef,label:`${component.name} / ${definition?.mateConnectors[connectorId]?.name??connectorId}`}));}),[definitions,document]);
  const connectorRefFromKey=(key:string)=>connectorOptions.find((option)=>option.key===key)?.ref;

  const createExplicitConnector=async()=>{const current=documentRef.current,slot=faceSlots[0];if(!current||!slot){setStatus("请先在选择面模式中选择平面或圆柱面。");return;}const component=current.components[slot.reference.instanceId];const source=definitionsRef.current.definitions.get(component?.definitionId??"");if(!component||!source){setStatus("无法定位所选面的零件定义。");return;}try{let index=source.mateConnectorOrder.length+1;while(source.mateConnectors[`MC${index}`])index+=1;const connector:PartMateConnectorDefinition={id:`MC${index}`,name:`连接器 ${index}`,bodyId:slot.reference.bodyId,topologyRef:structuredClone(slot.reference.topologyRef),offsetMm:{primary:connectorDraft.primary,secondary:connectorDraft.secondary,tertiary:connectorDraft.tertiary},spinDeg:connectorDraft.spinDeg,flipped:connectorDraft.flipped};let revisionIndex=1;let revisionId=`${source.id}-MC${revisionIndex}`;while(definitionsRef.current.definitions.has(revisionId))revisionId=`${source.id}-MC${++revisionIndex}`;const revision=createPartDefinitionRevisionWithMateConnector(source,revisionId,connector);const store=addPartDefinition(definitionsRef.current,revision);publishDefinitions(store);setSelectedDefinitionId(revisionId);await resetCache(store);const next=updateComponentDefinitionId(current,component.id,revisionId);await solveAndPublish(next);setStatus(`${connector.name} 已保存为零件新版本 ${revisionId}，其他实例不变。`);}catch(error){setStatus(error instanceof Error?error.message:String(error));}};

  const snapSelectedConnectors=async()=>{const current=documentRef.current,cache=cacheRef.current,kernel=kernelRef.current,aRef=connectorRefFromKey(connectorAKey),bRef=connectorRefFromKey(connectorBKey);if(!current||!cache||!kernel||!aRef||!bRef){setStatus("请选择目标连接器和移动连接器。");return;}if(aRef.instanceId===bRef.instanceId){setStatus("请选择两个不同组件的连接器。");return;}const moving=current.components[bRef.instanceId];if(moving.grounded){setStatus(`${moving.name} 已固定，不能移动。`);return;}try{const provider=new ExactAssemblyGeometryProvider(current,cache,kernel);const [targetLocal,movingLocal]=await Promise.all([provider.resolveConnector(aRef),provider.resolveConnector(bRef)]);const targetPlacement=runtimeRef.current?.solvedPlacements.get(aRef.instanceId)??current.components[aRef.instanceId].nominalPlacement;const targetWorld=transformMateConnectorFrame(targetLocal,targetPlacement);const snapped=snapPlacementByMateConnectors(movingLocal,targetWorld,snapAlignment);await solveAndPublish(updateComponentNominalPlacement(current,bRef.instanceId,snapped));setStatus(`吸附完成：${bRef.instanceId}/${bRef.connectorId} → ${aRef.instanceId}/${aRef.connectorId}。`);}catch(error){setStatus(error instanceof Error?error.message:String(error));}};

  const addConnectorMate=async(type:"revolute"|"slider")=>{const current=documentRef.current,a=connectorRefFromKey(connectorAKey),b=connectorRefFromKey(connectorBKey);if(!current||!a||!b){setStatus("请先选择两个 Explicit Mate Connectors。");return;}const id=newMateId(current);const limit={enabled:limitEnabled,min:limitMin,max:limitMax};const mate:AssemblyMate=type==="revolute"?{id,name:id,type,enabled:true,a,b,angleLimit:limit}:{id,name:id,type,enabled:true,a,b,distanceLimit:limit};try{await solveAndPublish(addMate(current,mate));setStatus(`${type} Mate 已创建，${limitEnabled?`Limits ${limitMin}..${limitMax}`:"Limits disabled"}。`);}catch(error){setStatus(error instanceof Error?error.message:String(error));}};

  const selectedComponent = selectedComponentId ? document.components[selectedComponentId] : undefined;
  const engineeringReport = useMemo(()=>analyzeAssemblyEngineering(document,runtime,new Map([...definitions.definitions].map(([id,definition])=>[id,definition.name]))),[definitions,document,runtime]);
  const exportBom = () => { const rows=[["零件定义","实例数量","可见数量","组件 ID"],...engineeringReport.bom.map((row)=>[row.definitionName,String(row.instanceCount),String(row.visibleCount),row.componentIds.join(" | ")])];const csv=`\ufeff${rows.map((row)=>row.map((cell)=>`"${cell.replaceAll('"','""')}"`).join(",")).join("\r\n")}`;const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`${document.name||"assembly"}-BOM.csv`;anchor.click();URL.revokeObjectURL(url);setStatus(`BOM 已导出：${engineeringReport.bom.length} 种零件，${engineeringReport.summary.componentCount} 个组件实例。`); };
  const solverSummary = useMemo(() => `${solverStatusLabels[runtime.status]} · 剩余自由度 ${runtime.dof} · 残差 ${displayNumber(runtime.residualNorm)}`, [runtime]);

  return <main className="assembly-workbench">
    <header className="assembly-header"><div className="assembly-brand"><button type="button" style={buttonStyle} onClick={()=>{window.location.href="/";}}>← 资源库</button><div><p>FORGEMIND / ASSEMBLY</p><h1>装配工作台</h1></div></div><div className="assembly-header-tools"><div className={`assembly-solver-chip is-${runtime.status}`}>{solverSummary}</div><div className="assembly-document-actions"><button disabled={!historyState.undo} onClick={()=>void undo()}>撤销</button><button disabled={!historyState.redo} onClick={()=>void redo()}>重做</button><button onClick={save}>保存</button><button onClick={()=>void load()}>载入</button><button onClick={exportAssemblyProject}>导出</button><label>导入<input hidden type="file" accept=".json,.forgemind-assembly.json" onChange={(event)=>{void importAssemblyProject(event.currentTarget.files?.[0]);event.currentTarget.value="";}}/></label></div></div></header>
    <div className="assembly-workspace">
      <section className="assembly-components-panel" style={panelStyle}><div className="assembly-panel-title"><h2 style={headingStyle}>组件</h2><span>{document.componentOrder.length}</span></div><div className="assembly-inline-control"><select aria-label="零件定义" value={selectedDefinitionId} onChange={(e)=>setSelectedDefinitionId(e.target.value)} style={inputStyle}>{definitionIds.map((id)=><option value={id} key={id}>{definitions.definitions.get(id)?.name ?? id}</option>)}</select><button disabled={busy} onClick={()=>void insertSelectedDefinition()} style={buttonStyle}>插入</button></div><label className="assembly-file-button" style={{ ...buttonStyle, display:"block", marginTop:6, textAlign:"center", cursor:"pointer" }}>导入 STEP<input type="file" accept=".step,.stp" hidden onChange={(e)=>{const file=e.target.files?.[0];if(file)void importStepPart(file);e.currentTarget.value="";}} /></label>
        <div className="assembly-component-list" style={{ marginTop: 8, display: "grid", gap: 5 }}>{document.componentOrder.map((id)=>{const c=document.components[id];return <div className={`assembly-component-card ${selectedComponentId===id?"is-selected":""}`} key={id}><button type="button" className="assembly-card-select" aria-label={`选择组件 ${c.name}`} aria-pressed={selectedComponentId===id} onClick={()=>selectComponent(id,document)}/><div className="assembly-component-card-head"><b>{c.name}</b><span>{c.grounded?"固定":"自由"}</span></div><div className="assembly-component-definition">{definitions.definitions.get(c.definitionId)?.name??c.definitionId}</div><div className="assembly-card-actions"><button style={miniButton} onClick={()=>void toggleGrounded(id)}>{c.grounded?"取消固定":"固定"}</button><button style={miniButton} onClick={()=>void toggleVisibility(id)}>{c.visible?"隐藏":"显示"}</button></div></div>})}</div>
        <h3 style={subheading}>组件设置</h3>{selectedComponent ? <><label style={{display:"block",marginBottom:7}}>名称<input value={componentNameDraft} onChange={(e)=>setComponentNameDraft(e.target.value)} style={inputStyle}/></label><div style={{display:"flex",gap:6,marginBottom:8,flexWrap:"wrap"}}><button style={buttonStyle} onClick={()=>void applyComponentName()}>重命名</button><button style={buttonStyle} onClick={()=>void duplicateSelectedComponent()}>复制</button><button style={buttonStyle} onClick={()=>void isolateSelectedComponent()}>隔离</button></div><label style={{display:"block",marginBottom:7}}>零件定义<select value={selectedDefinitionId} onChange={(e)=>setSelectedDefinitionId(e.target.value)} style={inputStyle}>{definitionIds.map((id)=><option value={id} key={id}>{definitions.definitions.get(id)?.name??id}</option>)}</select></label><button style={buttonStyle} onClick={()=>void replaceSelectedDefinition()}>替换</button><div style={{display:"flex",gap:6,marginTop:8,flexWrap:"wrap"}}><button className="assembly-danger" style={{...buttonStyle,borderColor:"#7f1d1d",background:"#3f1318"}} onClick={()=>void deleteSelectedComponent()}>删除组件</button><button className="assembly-danger" style={{...buttonStyle,borderColor:"#7f1d1d",background:"#3f1318"}} onClick={()=>void deleteSelectedComponentAndMates()}>连同配合删除</button></div><h3 style={subheading}>位置</h3><div style={grid3}>{(["x","y","z"] as const).map((key)=><label key={key}>{key.toUpperCase()}<input type="number" value={placementDraft[key]} onChange={(e)=>setPlacementDraft({...placementDraft,[key]:Number(e.target.value)})} style={inputStyle}/></label>)}</div><div style={grid3}>{(["rx","ry","rz"] as const).map((key)=><label key={key}>{key.toUpperCase()}°<input type="number" value={placementDraft[key]} onChange={(e)=>setPlacementDraft({...placementDraft,[key]:Number(e.target.value)})} style={inputStyle}/></label>)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button style={buttonStyle} onClick={()=>void applyPlacement()}>应用</button><button style={buttonStyle} onClick={()=>void adoptSolvedPlacement()}>采用求解位置</button><button style={buttonStyle} onClick={()=>void addFixedMate()}>固定</button></div></> : <p style={muted}>请选择组件。</p>}
      </section>
      <section className="assembly-canvas-panel" style={{...panelStyle,padding:0,overflow:"hidden"}}><div className="assembly-canvas-toolbar">{(["select","drag","orbit"] as const).map((value)=><button className={`assembly-mode-button ${interactionMode===value?"active":""}`} key={value} type="button" onClick={()=>setInteractionMode(value)}>{value==="select"?"选择面":value==="drag"?"拖动":"旋转视图"}{value==="select"?/* Select Faces */null:null}</button>)}<span className="assembly-toolbar-spacer"/><button type="button" onClick={()=>void showAllComponents()}>显示全部</button></div><div className="assembly-render-host" ref={hostRef}/><div className={`assembly-status-bar ${runtime.status==="conflict"||runtime.status==="degraded"?"is-error":""}`} title={status}><span>{status}</span><b>{solverStatusLabels[runtime.status]} · 自由度 {runtime.dof}</b></div></section>
      <section className="assembly-mates-panel" style={panelStyle}><div className="assembly-panel-title"><h2 style={headingStyle}>配合</h2><span>{document.mateOrder.length}</span></div><div className="assembly-reference-grid"><label>基准 A<div style={slotStyle}>{faceSlots[0]?.label ?? "选择第一个面"}</div></label><label>基准 B<div style={slotStyle}>{faceSlots[1]?.label ?? "选择第二个面"}</div></label></div><div className="assembly-compact-actions"><button style={miniButton} onClick={()=>setFaceSlots([])}>清空</button><button style={buttonStyle} onClick={()=>void addSelectedMate("coincident")}>重合</button><button style={buttonStyle} onClick={()=>void addSelectedMate("concentric")}>同心</button></div><div className="assembly-parameter-actions"><label>距离 mm<input type="number" value={distanceMm} onChange={(e)=>setDistanceMm(Number(e.target.value))} style={inputStyle}/></label><button style={buttonStyle} onClick={()=>void addSelectedMate("distance")}>添加</button><label>角度 °<input type="number" value={angleDeg} min={0} max={180} onChange={(e)=>setAngleDeg(Number(e.target.value))} style={inputStyle}/></label><button style={buttonStyle} onClick={()=>void addSelectedMate("angle")}>添加</button></div><h3 style={subheading}>连接器</h3><div className="assembly-connector-draft"><div className="assembly-control-label">创建连接器</div><div style={grid3}>{(["primary","secondary","tertiary"] as const).map((key)=><label key={key}>{key==="primary"?"主轴":key==="secondary"?"次轴":"第三轴"}<input type="number" value={connectorDraft[key]} onChange={(e)=>setConnectorDraft({...connectorDraft,[key]:Number(e.target.value)})} style={inputStyle}/></label>)}</div><div className="assembly-inline-control"><label>旋转角 °<input type="number" value={connectorDraft.spinDeg} onChange={(e)=>setConnectorDraft({...connectorDraft,spinDeg:Number(e.target.value)})} style={inputStyle}/></label><label className="assembly-check"><input type="checkbox" checked={connectorDraft.flipped} onChange={(e)=>setConnectorDraft({...connectorDraft,flipped:e.target.checked})}/>翻转主轴</label></div><button style={{...miniButton,marginTop:6}} onClick={()=>void createExplicitConnector()}>从基准 A 创建{/* Create Explicit Connector from A */}</button></div>
        <div className="assembly-connector-pair"><label>目标连接器<select value={connectorAKey} onChange={(e)=>setConnectorAKey(e.target.value)} style={inputStyle}><option value="">请选择</option>{connectorOptions.map((option)=><option key={option.key} value={option.key}>{option.label}</option>)}</select></label><label>移动连接器<select value={connectorBKey} onChange={(e)=>setConnectorBKey(e.target.value)} style={inputStyle}><option value="">请选择</option>{connectorOptions.map((option)=><option key={option.key} value={option.key}>{option.label}</option>)}</select></label></div><div className="assembly-snap-row"><select aria-label="连接器方向" value={snapAlignment} onChange={(e)=>setSnapAlignment(e.target.value as MateAlignment)} style={inputStyle}><option value="opposite">反向</option><option value="same">同向</option></select><button style={buttonStyle} onClick={()=>void snapSelectedConnectors()}>吸附 B → A{/* Snap B → A */}</button><label className="assembly-check"><input type="checkbox" checked={snapModeEnabled} onChange={(e)=>setSnapModeEnabled(e.target.checked)}/>拖动吸附</label><label>阈值 mm<input type="number" min={0} value={snapThresholdMm} onChange={(e)=>setSnapThresholdMm(Number(e.target.value))} style={inputStyle}/></label></div><div className="assembly-limit-row"><label className="assembly-check"><input type="checkbox" checked={limitEnabled} onChange={(e)=>setLimitEnabled(e.target.checked)}/>限位</label><label>最小<input type="number" value={limitMin} onChange={(e)=>setLimitMin(Number(e.target.value))} style={inputStyle}/></label><label>最大<input type="number" value={limitMax} onChange={(e)=>setLimitMax(Number(e.target.value))} style={inputStyle}/></label><button style={buttonStyle} onClick={()=>void addConnectorMate("revolute")}>转动</button><button style={buttonStyle} onClick={()=>void addConnectorMate("slider")}>滑动</button></div>
        <h3 style={subheading}>配合列表</h3><div className="assembly-mate-list" style={{display:"grid",gap:6}}>{document.mateOrder.map((id)=>{const mate=document.mates[id];return <div key={id} style={{border:"1px solid #26364d",padding:7,borderRadius:7,background:"#0d1828"}}><div><b>{mate.name}</b> <span style={{color:"#7dd3fc"}}>· {mateTypeLabels[mate.type]}</span></div><div style={{display:"flex",gap:5,marginTop:5,flexWrap:"wrap"}}><button style={miniButton} onClick={()=>void toggleMate(id)}>{mate.enabled?"抑制":"启用"}</button>{mate.type === "distance" ? <button style={miniButton} onClick={()=>void applyMateParameter(id)}>设置 {distanceMm} mm</button> : null}{mate.type === "angle" ? <button style={miniButton} onClick={()=>void applyMateParameter(id)}>设置 {angleDeg}°</button> : null}{mate.type === "revolute" ? <><span style={{fontSize:11,color:"#94a3b8"}}>旋转自由度 · {mate.angleLimit.enabled?`${mate.angleLimit.min}..${mate.angleLimit.max}°`:"未限位"}</span><button style={miniButton} onClick={()=>void applyMateParameter(id)}>设置限位</button></>:null}{mate.type === "slider" ? <><span style={{fontSize:11,color:"#94a3b8"}}>滑动自由度 · {mate.distanceLimit.enabled?`${mate.distanceLimit.min}..${mate.distanceLimit.max} mm`:"未限位"}</span><button style={miniButton} onClick={()=>void applyMateParameter(id)}>设置限位</button></>:null}<button className="assembly-danger" style={miniButton} onClick={()=>void removeMateById(id)}>删除</button></div></div>})}</div>
        <h3 style={subheading}>工程检查</h3><div className="assembly-engineering-summary" style={{border:"1px solid #26364d",padding:8,fontSize:11,lineHeight:1.55}}><div><b>{engineeringReport.ready?"可继续设计":"需要处理错误"}</b> · {engineeringReport.summary.componentCount} 个组件 · {engineeringReport.summary.enabledMateCount}/{engineeringReport.summary.mateCount} 个配合启用</div><div>{engineeringReport.groups.length} 个连接组 · {engineeringReport.summary.groundedCount} 个固定基准 · {engineeringReport.summary.unresolvedDof} 个剩余自由度</div>{engineeringReport.issues.length?<div style={{display:"grid",gap:4,marginTop:7}}>{engineeringReport.issues.slice(0,8).map((issue,index)=><button key={`${issue.code}-${index}`} type="button" style={{...miniButton,textAlign:"left",borderColor:issue.severity==="error"?"#b86d64":undefined}} onClick={()=>{if(issue.componentIds[0])selectComponent(issue.componentIds[0],document);setStatus(issue.message);}}><b>{issue.severity==="error"?"错误":issue.severity==="warning"?"注意":"说明"}</b> · {issue.message}</button>)}</div>:<div style={{marginTop:6,color:"#277d52"}}>未发现装配结构问题。</div>}</div><h3 style={subheading}>零件明细（BOM）</h3><div style={{display:"grid",gap:4,fontSize:11}}>{engineeringReport.bom.map((row)=><div key={row.definitionId} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,borderBottom:"1px solid #c9d0c8",padding:"4px 0"}}><span>{row.definitionName}</span><b>× {row.instanceCount}</b></div>)}</div><button style={{...buttonStyle,marginTop:7}} onClick={exportBom}>导出 BOM 表格</button>
      </section>
    </div>
  </main>;
}

const panelStyle: React.CSSProperties = { background:"#0a1524",border:"1px solid #24364f",borderRadius:10,padding:12,boxShadow:"0 12px 35px #0006" };
const headingStyle: React.CSSProperties = { margin:"0 0 10px",fontSize:16,color:"#e0f2fe" };
const subheading: React.CSSProperties = { margin:"16px 0 7px",fontSize:13,color:"#93c5fd" };
const inputStyle: React.CSSProperties = { width:"100%",boxSizing:"border-box",background:"#07101c",color:"#e2e8f0",border:"1px solid #31445f",borderRadius:6,padding:"6px 7px",marginTop:3 };
const buttonStyle: React.CSSProperties = { background:"#123250",color:"#dbeafe",border:"1px solid #2d5f89",borderRadius:6,padding:"7px 9px",cursor:"pointer" };
const miniButton: React.CSSProperties = { ...buttonStyle,padding:"4px 7px",fontSize:11 };
const muted: React.CSSProperties = { color:"#64748b",fontSize:12 };
const grid3: React.CSSProperties = { display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5,marginBottom:6,fontSize:11 };
const slotStyle: React.CSSProperties = { border:"1px solid #31445f",borderRadius:6,padding:7,background:"#07101c",margin:"3px 0 8px",fontSize:12,minHeight:18 };
