package com.forgemind.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.forgemind.model.FactoryProject;
import com.forgemind.repository.AgentRuntimeRepository;
import com.forgemind.repository.FactoryProjectDbStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;

@Service
public class AgentRuntimeService {
    public static final String[] TOOLS={"get_factory_snapshot","get_factory_graph","get_simulation_metrics","query_event_timeline","inspect_inventory","inspect_machine","inspect_recipe_chain","inspect_conveyors","inspect_logistics","calculate_capacity","inspect_bottlenecks","explain_constraint"};
    private final AgentRuntimeRepository agents; private final FactoryProjectDbStore projects; private final ObjectMapper json;
    private final boolean llmConfigured; private final String provider;

    public AgentRuntimeService(AgentRuntimeRepository agents,FactoryProjectDbStore projects,ObjectMapper json,
       @Value("${forgemind.agent.provider:${AGENT_LLM_PROVIDER:deterministic}}")String provider,
       @Value("${forgemind.agent.api-key:${OPENAI_API_KEY:}}")String apiKey){this.agents=agents;this.projects=projects;this.json=json;this.llmConfigured=apiKey!=null&&!apiKey.isBlank()&&!"deterministic".equalsIgnoreCase(provider);this.provider=llmConfigured?provider:"deterministic";}

    public ObjectNode create(String owner,String factory,String objective,String mode,JsonNode context){if(objective==null||objective.isBlank())throw new IllegalArgumentException("诊断目标不能为空");if(!"read_only".equals(mode)&&!"plan_design".equals(mode))throw new IllegalArgumentException("Agent 模式非法");FactoryProject project=projects.loadForUser(owner,factory);JsonNode snapshot=context!=null&&context.isObject()?context.deepCopy():project.save().deepCopy();String base=fingerprint(project.save());ObjectNode goal=goal(objective,base,mode);String id=agents.createRun(owner,factory,objective.trim(),mode,base,snapshot,goal,provider,llmConfigured);return agents.run(owner,id);}

    @Transactional
    public ObjectNode analyze(String owner,String runId,JsonNode suppliedResult,JsonNode suppliedPatch){ObjectNode run=agents.run(owner,runId);if(run.path("result").isObject())return run;agents.begin(owner,runId);JsonNode result=suppliedResult!=null&&suppliedResult.isObject()?suppliedResult:fallbackResult(run);for(String tool:TOOLS){ObjectNode output=json.createObjectNode().put("ok",true).put("source","deterministic");if("get_factory_snapshot".equals(tool))output.set("snapshot",result.path("snapshot"));else if("get_factory_graph".equals(tool))output.set("graph_summary",result.path("graph_summary"));else if("get_simulation_metrics".equals(tool))output.set("metrics",result.path("metrics"));else output.put("records",run.path("context_snapshot").path("objects").size());agents.tool(runId,tool,output,1);}String summary=result.path("assessment").asText(result.path("headline").asText("工厂诊断完成"));String status="plan_design".equals(run.path("mode").asText())?"awaiting_approval":"completed";agents.complete(owner,runId,result,summary,status);if("plan_design".equals(run.path("mode").asText()))createPatch(owner,run,suppliedPatch);return agents.run(owner,runId);}

    public ObjectNode get(String owner,String id){return agents.run(owner,id);} public ArrayNode list(String owner,String factory){projects.loadForUser(owner,factory);return agents.runs(owner,factory);} public ObjectNode cancel(String owner,String id){agents.cancel(owner,id);return agents.run(owner,id);} public ArrayNode patches(String owner,String run){return agents.patches(owner,run);} public ObjectNode patch(String owner,String id){return agents.patch(owner,id);} public ObjectNode approve(String owner,String id,String note){agents.decide(owner,id,"approved",note);return agents.patch(owner,id);} public ObjectNode reject(String owner,String id,String note){agents.decide(owner,id,"rejected",note);return agents.patch(owner,id);}
    public ObjectNode appendEvent(String owner,String runId,String name,JsonNode data){agents.run(owner,runId);return agents.event(runId,name,data==null?json.createObjectNode():data);}

    public ObjectNode replan(String owner,String patchId,String reason){if(reason==null||reason.isBlank())throw new IllegalArgumentException("重新规划原因不能为空");ObjectNode patch=agents.patch(owner,patchId);agents.decide(owner,patchId,"rejected",reason);ObjectNode old=agents.run(owner,patch.path("run_id").asText());ObjectNode next=create(owner,patch.path("factory_id").asText(),old.path("objective").asText()+"\n补充约束："+reason,"plan_design",old.path("context_snapshot"));return next;}

    @Transactional
    public ObjectNode apply(String owner,String patchId){ObjectNode patch=agents.patch(owner,patchId);if("applied".equals(patch.path("status").asText()))return patch;if(!"approved".equals(patch.path("status").asText()))throw new IllegalArgumentException("Patch 必须先批准才能应用");FactoryProject project=projects.loadForUser(owner,patch.path("factory_id").asText());if(!fingerprint(project.save()).equals(patch.path("base_version").asText()))throw new IllegalArgumentException("工厂已发生新修改，Patch 基线版本冲突，请重新分析");ObjectNode run=agents.run(owner,patch.path("run_id").asText());JsonNode before=project.save().deepCopy();JsonNode after=applyOperations(run.path("context_snapshot"),patch.path("operations"));projects.updateForUser(owner,patch.path("factory_id").asText(),project.project().name(),after);agents.applied(owner,patchId,before,after);return agents.patch(owner,patchId);}

    @Transactional
    public ObjectNode rollback(String owner,String patchId){ObjectNode patch=agents.patch(owner,patchId);if("rolled_back".equals(patch.path("status").asText()))return patch;if(!"applied".equals(patch.path("status").asText()))throw new IllegalArgumentException("只有已应用的 Patch 可以回滚");JsonNode backup=patch.path("backup_save");if(!backup.isObject())throw new IllegalArgumentException("Patch 缺少回滚快照");FactoryProject project=projects.loadForUser(owner,patch.path("factory_id").asText());projects.updateForUser(owner,patch.path("factory_id").asText(),project.project().name(),backup);agents.rolledBack(owner,patchId);return agents.patch(owner,patchId);}

    private void createPatch(String owner,ObjectNode run,JsonNode supplied){JsonNode ops=supplied!=null&&supplied.path("operations").isArray()?supplied.path("operations"):json.createArrayNode();JsonNode inverse=supplied!=null&&supplied.path("inverse_operations").isArray()?supplied.path("inverse_operations"):json.createArrayNode();String risk=supplied==null?"low":supplied.path("risk_level").asText("low");ObjectNode validation=json.createObjectNode().put("ok",ops.size()>0);validation.putArray("errors");validation.putArray("warnings");ObjectNode diff=json.createObjectNode().put("operation_count",ops.size());diff.set("operations",ops.deepCopy());agents.createPatch(owner,run.path("id").asText(),run.path("factory_id").asText(),run.path("base_factory_updated_at").asText(),ops,inverse,validation,diff,risk);}

    private ObjectNode goal(String objective,String base,String mode){ObjectNode g=json.createObjectNode().put("goal_schema_version",1).put("compiler","forgecore-adapter-v1").put("objective",objective).put("intent","plan_design".equals(mode)?"optimize":"diagnose").put("status","ready").put("baseline_version",base).put("time_horizon_sec",3600);g.putArray("metrics");g.putArray("hard_constraints");g.putArray("soft_constraints");g.putArray("allowed_actions").add("inspect").add("move_object").add("update_config").add("add_object").add("remove_object").add("adjust_inventory");g.putArray("assumptions").add("确定性 ForgeMind 引擎负责数值、碰撞、库存、寻路和仿真");g.putArray("missing_constraints");g.putArray("conflicts");return g;}
    private ObjectNode fallbackResult(ObjectNode run){JsonNode save=run.path("context_snapshot");int objects=save.path("objects").size(),items=save.path("items").size(),recipes=save.path("recipes").size();ObjectNode r=json.createObjectNode().put("headline","工厂结构诊断完成").put("assessment","已完成当前存档的确定性结构分析。").put("confidence",objects>0?.9:.55);ObjectNode s=r.putObject("snapshot");s.put("factory_id",run.path("factory_id").asText()).put("factory_name",save.path("name").asText()).put("factory_version",run.path("base_factory_updated_at").asText()).put("floor_count",save.path("floorCount").asInt(1)).put("object_count",objects).put("item_count",items).put("recipe_count",recipes).put("enabled_recipe_count",recipes).put("inventory_record_count",0).put("simulation_status","snapshot").put("elapsed_sim_sec",0);s.putObject("dimensions_m").put("width",48).put("length",48);s.putObject("object_counts");ObjectNode g=r.putObject("graph_summary");g.put("node_count",objects+items+recipes).put("edge_count",0).put("invalid_reference_count",0);g.putObject("node_counts");g.putObject("edge_counts");r.putObject("metrics").put("throughput_per_min",0).put("work_in_progress",0).put("finished_goods",0).put("elapsed_sim_sec",0).put("sample_count",1);ObjectNode f=r.putArray("findings").addObject().put("id","structure").put("category","graph").put("severity","info").put("title","结构快照已建立").put("detail","对象、物品与工艺已进入证据链。").put("recommendation","结合实时仿真指标继续诊断。");f.putArray("evidence").addObject().put("label","对象").put("value",String.valueOf(objects));f.putArray("object_ids");return r;}

    private JsonNode applyOperations(JsonNode source,JsonNode operations){if(!source.isObject())throw new IllegalArgumentException("Agent 运行缺少工厂快照");ObjectNode save=(ObjectNode)source.deepCopy();ArrayNode objects=(ArrayNode)save.withArray("objects");for(JsonNode op:operations){String kind=op.path("kind").asText(),id=op.path("object_id").asText();JsonNode p=op.path("params");if("remove_object".equals(kind)){for(int i=objects.size()-1;i>=0;i--)if(objects.get(i).path("id").asText().equals(id))objects.remove(i);}else if("add_object".equals(kind)){JsonNode value=p.path("object").isObject()?p.path("object"):p;if(value.isObject())objects.add(value.deepCopy());}else for(JsonNode entry:objects)if(entry.isObject()&&entry.path("id").asText().equals(id)){ObjectNode object=(ObjectNode)entry;if("move_object".equals(kind)){ObjectNode pos=object.with("pos");if(p.has("x"))pos.put("x",p.path("x").asDouble());if(p.has("z"))pos.put("z",p.path("z").asDouble());if(p.has("floor_id"))object.put("floorId",p.path("floor_id").asInt());}else if("update_config".equals(kind)){String path=p.path("path").asText();JsonNode value=p.get("value");if(!path.isBlank()){if(value==null||value.isNull())object.remove(path);else object.set(path,value);}if(p.path("config_patch").isObject())p.path("config_patch").fields().forEachRemaining(e->object.set(e.getKey(),e.getValue()));}else if("adjust_inventory".equals(kind))object.put("agentInventoryAdjustment",p.path("quantity").asDouble());}}return save;}
    private String fingerprint(JsonNode n){try{return "save-"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsString(n).getBytes(StandardCharsets.UTF_8))).substring(0,24);}catch(Exception e){throw new IllegalStateException("无法计算存档版本",e);}}
}
