package com.forgemind.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.forgemind.model.FactoryProject;
import com.forgemind.repository.AgentRuntimeRepository;
import com.forgemind.repository.FactoryProjectDbStore;
import com.forgemind.repository.ImportedResourceDbStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.List;
import java.util.Set;

@Service
public class AgentRuntimeService {
    public static final String[] TOOLS={"get_factory_snapshot","get_factory_graph","get_simulation_metrics","query_event_timeline","inspect_inventory","inspect_machine","inspect_recipe_chain","inspect_conveyors","inspect_logistics","calculate_capacity","inspect_bottlenecks","explain_constraint"};
    private final AgentRuntimeRepository agents; private final FactoryProjectDbStore projects; private final ImportedResourceDbStore resources; private final ObjectMapper json; private final AgentPatchValidator patchValidator;
    private final boolean llmConfigured; private final String provider;

    public AgentRuntimeService(AgentRuntimeRepository agents,FactoryProjectDbStore projects,ImportedResourceDbStore resources,ObjectMapper json,AgentPatchValidator patchValidator,
       @Value("${forgemind.agent.provider:${AGENT_LLM_PROVIDER:deterministic}}")String provider,
       @Value("${forgemind.agent.api-key:${OPENAI_API_KEY:}}")String apiKey){this.agents=agents;this.projects=projects;this.resources=resources;this.json=json;this.patchValidator=patchValidator;this.llmConfigured=apiKey!=null&&!apiKey.isBlank()&&!"deterministic".equalsIgnoreCase(provider);this.provider=llmConfigured?provider:"deterministic";}

    public ObjectNode create(String owner,String factory,String objective,String mode,JsonNode context){if(objective==null||objective.isBlank())throw new IllegalArgumentException("诊断目标不能为空");if(objective.trim().length()>2000)throw new IllegalArgumentException("诊断目标不能超过 2000 个字符");if(!"read_only".equals(mode)&&!"plan_design".equals(mode))throw new IllegalArgumentException("Agent 模式非法");FactoryProject project=projects.loadForUser(owner,factory);JsonNode authoritative=project.save().deepCopy();if(context!=null&&context.isObject()&&!sameSave(context,authoritative))throw new IllegalArgumentException("Agent 上下文与当前工厂存档不一致，请刷新工厂后重试");String base=fingerprint(authoritative);ObjectNode goal=goal(objective.trim(),base,mode);String id=agents.createRun(owner,factory,objective.trim(),mode,base,authoritative,goal,provider,llmConfigured);return agents.run(owner,id);}

    @Transactional
    public ObjectNode analyze(String owner,String runId,JsonNode suppliedResult,JsonNode suppliedPatch){ObjectNode run=agents.run(owner,runId);if(run.path("result").isObject())return run;if(List.of("cancelled","completed","rejected").contains(run.path("status").asText()))throw new IllegalArgumentException("当前 Agent 运行已结束，不能重复分析");FactoryProject project=projects.loadForUser(owner,run.path("factory_id").asText());JsonNode authoritative=project.save().deepCopy();if(!fingerprint(authoritative).equals(run.path("base_factory_updated_at").asText()))throw new IllegalArgumentException("工厂已发生新修改，请重新创建 Agent 运行");List<String> resourceErrors=validateResourceOwnership(owner,authoritative);if(!resourceErrors.isEmpty())throw new IllegalArgumentException("当前工厂资源归属校验失败："+String.join("；",resourceErrors));agents.begin(owner,runId);ObjectNode result=suppliedResult!=null&&suppliedResult.isObject()?(ObjectNode)suppliedResult.deepCopy():fallbackResult(run);result.putObject("server_verification").put("verified_context",true).put("factory_version",fingerprint(authoritative)).put("findings_source","browser_deterministic_evidence").put("structural_tools_source","server_authoritative_save");int budget=Math.max(1,run.path("tool_call_budget").asInt(TOOLS.length));for(int index=0;index<Math.min(TOOLS.length,budget);index++){String tool=TOOLS[index];agents.tool(runId,tool,authoritativeTool(tool,authoritative),1);}boolean plan="plan_design".equals(run.path("mode").asText());boolean hasPatch=suppliedPatch!=null&&suppliedPatch.path("operations").isArray()&&!suppliedPatch.path("operations").isEmpty();if(plan&&hasPatch)createPatch(owner,run,suppliedPatch,authoritative);String summary=result.path("assessment").asText(result.path("headline").asText("工厂诊断完成"));agents.complete(owner,runId,result,summary,plan&&hasPatch?"awaiting_approval":"completed");return agents.run(owner,runId);}

    public ObjectNode get(String owner,String id){return agents.run(owner,id);} public ArrayNode list(String owner,String factory){projects.loadForUser(owner,factory);return agents.runs(owner,factory);} public ObjectNode cancel(String owner,String id){ObjectNode run=agents.run(owner,id);if(List.of("completed","cancelled","rejected").contains(run.path("status").asText()))return run;agents.cancel(owner,id);return agents.run(owner,id);} public ArrayNode patches(String owner,String run){return agents.patches(owner,run);} public ObjectNode patch(String owner,String id){return agents.patch(owner,id);} public ObjectNode approve(String owner,String id,String note){agents.decide(owner,id,"approved",note);return agents.patch(owner,id);} public ObjectNode reject(String owner,String id,String note){agents.decide(owner,id,"rejected",note);return agents.patch(owner,id);}
    public ObjectNode appendEvent(String owner,String runId,String name,JsonNode data){agents.run(owner,runId);return agents.event(runId,name,data==null?json.createObjectNode():data);}

    public ObjectNode replan(String owner,String patchId,String reason){if(reason==null||reason.isBlank())throw new IllegalArgumentException("重新规划原因不能为空");ObjectNode patch=agents.patch(owner,patchId);agents.decide(owner,patchId,"rejected",reason);ObjectNode old=agents.run(owner,patch.path("run_id").asText());return create(owner,patch.path("factory_id").asText(),old.path("objective").asText()+"\n补充约束："+reason,"plan_design",null);}

    @Transactional
    public ObjectNode apply(String owner,String patchId){ObjectNode patch=agents.patch(owner,patchId);if("applied".equals(patch.path("status").asText()))return patch;if(!"approved".equals(patch.path("status").asText()))throw new IllegalArgumentException("Patch 必须先批准才能应用");FactoryProject project=projects.loadForUserForUpdate(owner,patch.path("factory_id").asText());JsonNode before=project.save().deepCopy();if(!fingerprint(before).equals(patch.path("base_version").asText()))throw new IllegalArgumentException("工厂已发生新修改，Patch 基线版本冲突，请重新分析");List<String> errors=patchValidator.validate(before,patch.path("operations"));errors.addAll(validateResourceOwnership(owner,before));errors.addAll(validateResourceOwnership(owner,patch.path("operations")));if(!errors.isEmpty())throw new IllegalArgumentException("服务端 Patch 校验失败："+String.join("；",errors));JsonNode after=applyOperations(before,patch.path("operations"));projects.updateForUser(owner,patch.path("factory_id").asText(),project.project().name(),after);agents.applied(owner,patchId,before,after);return agents.patch(owner,patchId);}

    @Transactional
    public ObjectNode rollback(String owner,String patchId){ObjectNode patch=agents.patch(owner,patchId);if("rolled_back".equals(patch.path("status").asText()))return patch;if(!"applied".equals(patch.path("status").asText()))throw new IllegalArgumentException("只有已应用的 Patch 可以回滚");JsonNode backup=patch.path("backup_save"),applied=patch.path("applied_save");if(!backup.isObject()||!applied.isObject())throw new IllegalArgumentException("Patch 缺少回滚快照");FactoryProject project=projects.loadForUserForUpdate(owner,patch.path("factory_id").asText());JsonNode current=project.save();if(!fingerprint(current).equals(fingerprint(applied)))throw new IllegalArgumentException("工厂在 Patch 应用后已有新修改，不能覆盖当前存档，请先创建新版本");List<String> resourceErrors=validateResourceOwnership(owner,backup);if(!resourceErrors.isEmpty())throw new IllegalArgumentException("回滚资源归属校验失败："+String.join("；",resourceErrors));projects.updateForUser(owner,patch.path("factory_id").asText(),project.project().name(),backup);agents.rolledBack(owner,patchId);return agents.patch(owner,patchId);}

    private void createPatch(String owner,ObjectNode run,JsonNode supplied,JsonNode authoritative){JsonNode ops=supplied!=null&&supplied.path("operations").isArray()?supplied.path("operations"):json.createArrayNode();JsonNode inverse=supplied!=null&&supplied.path("inverse_operations").isArray()?supplied.path("inverse_operations"):json.createArrayNode();List<String> errors=patchValidator.validate(authoritative,ops);errors.addAll(validateResourceOwnership(owner,ops));if(!errors.isEmpty())throw new IllegalArgumentException("服务端 Patch 校验失败："+String.join("；",errors));String risk=supplied==null?"low":supplied.path("risk_level").asText("low");if(!List.of("low","medium","high").contains(risk))throw new IllegalArgumentException("Patch 风险等级非法");ObjectNode validation=json.createObjectNode().put("ok",true);validation.putArray("errors");validation.putArray("warnings");ObjectNode diff=json.createObjectNode().put("operation_count",ops.size());diff.set("operations",ops.deepCopy());agents.createPatch(owner,run.path("id").asText(),run.path("factory_id").asText(),run.path("base_factory_updated_at").asText(),ops,inverse,validation,diff,risk);}

    private ObjectNode goal(String objective,String base,String mode){ObjectNode g=json.createObjectNode().put("goal_schema_version",1).put("compiler","forgecore-adapter-v2").put("objective",objective).put("intent","plan_design".equals(mode)?"optimize":"diagnose").put("status","ready").put("baseline_version",base).put("time_horizon_sec",parseHorizon(objective));ArrayNode metrics=g.putArray("metrics");java.util.regex.Matcher throughput=java.util.regex.Pattern.compile("(?:每小时|per\\s*hour|/\\s*h)[^0-9]*(\\d+(?:\\.\\d+)?)",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective);if(throughput.find())metrics.addObject().put("name","target_throughput_per_hour").put("value",Double.parseDouble(throughput.group(1)));ArrayNode hard=g.putArray("hard_constraints");addConstraint(hard,objective,"maxChanges","(?:最多|不超过|max(?:imum)?|上限)[^0-9]*(\\d+)\\s*(?:项|个)?\\s*(?:修改|变更|操作|changes?)");addConstraint(hard,objective,"maxEnergyKw","(?:能耗|功率|energy|power)[^0-9]*(?:不超过|最多|上限|<=|≤)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:kw|千瓦)");java.util.regex.Matcher floor=java.util.regex.Pattern.compile("(?:仅限|限定|目标|在)\\s*(?:楼层|floor)\\s*l?(\\d+)",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective);if(floor.find())hard.addObject().put("name","floorId").put("value",Integer.parseInt(floor.group(1)));if(java.util.regex.Pattern.compile("保留|不删除|不得删除|不能删除|禁止删除|preserve",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective).find())hard.addObject().put("name","preserveExistingAssets").put("value",true);ArrayNode soft=g.putArray("soft_constraints");if(java.util.regex.Pattern.compile("能耗|energy|电费",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective).find())soft.add("minimize_energy");if(java.util.regex.Pattern.compile("少改|最小调整|least\\s+change",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective).find())soft.add("minimize_changes");if(soft.isEmpty())soft.add("minimize_changes");g.putArray("allowed_actions").add("inspect").add("move_object").add("update_config").add("add_object").add("remove_object").add("adjust_inventory");g.putArray("assumptions").add("确定性 ForgeMind 引擎负责数值、碰撞、库存、寻路和仿真");g.putArray("missing_constraints");if("plan_design".equals(mode)&&!throughput.find(0))g.withArray("missing_constraints").add("target_throughput_per_hour");g.putArray("conflicts");return g;}
    private void addConstraint(ArrayNode target,String objective,String name,String expression){java.util.regex.Matcher match=java.util.regex.Pattern.compile(expression,java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective);if(match.find())target.addObject().put("name",name).put("value",Double.parseDouble(match.group(1)));}
    private int parseHorizon(String objective){java.util.regex.Matcher match=java.util.regex.Pattern.compile("(?:窗口|horizon|采样)[^0-9]*(\\d+(?:\\.\\d+)?)\\s*(秒|s|min|分钟)",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(objective);if(!match.find())return 3600;double value=Double.parseDouble(match.group(1));return (int)Math.round(value*(match.group(2).matches("(?i)min|分钟")?60:1));}
    private ObjectNode authoritativeTool(String tool,JsonNode save){ObjectNode out=json.createObjectNode().put("ok",true).put("source","server");int objects=save.path("objects").size(),items=save.path("items").size(),recipes=save.path("recipes").size();switch(tool){case "get_factory_snapshot"->out.putObject("snapshot").put("object_count",objects).put("item_count",items).put("recipe_count",recipes).put("floor_count",save.path("floorCount").asInt(1));case "get_factory_graph"->out.putObject("graph_summary").put("node_count",objects+items+recipes).put("object_count",objects);case "get_simulation_metrics"->out.putObject("metrics").put("source","server_save").put("sample_count",0).put("note","服务端当前只验证结构存档，运行指标由浏览器确定性仿真证据提供");case "inspect_inventory"->out.put("storage_objects",countTypes(save,"oreMiner")+countTypes(save,"storage")+countTypes(save,"inboundWarehouse")+countTypes(save,"outboundWarehouse"));case "inspect_machine"->out.put("machine_objects",machineCount(save));case "inspect_recipe_chain"->out.put("recipes",recipes);case "inspect_conveyors"->out.put("conveyors",countTypes(save,"conveyor")+countTypes(save,"splitter")+countTypes(save,"merger"));case "inspect_logistics"->out.put("vehicles",countTypes(save,"agv")+countTypes(save,"drone"));case "calculate_capacity"->out.put("machine_count",machineCount(save)).put("capacity_source","configured_machine_definitions");case "inspect_bottlenecks"->out.put("status","requires_runtime_evidence");case "query_event_timeline"->out.put("status","no_runtime_events_persisted");case "explain_constraint"->out.put("status","deterministic_constraints_only");default->out.put("status","unknown_tool");}return out;}
    private int countTypes(JsonNode save,String type){int count=0;for(JsonNode object:save.path("objects"))if(type.equals(object.path("type").asText()))count++;return count;}
    private int machineCount(JsonNode save){int count=0;for(JsonNode object:save.path("objects")){String type=object.path("type").asText();if(Set.of("machine","smelter","press","assembler","inspection","washing","imported").contains(type))count++;}return count;}
    private ObjectNode fallbackResult(ObjectNode run){JsonNode save=run.path("context_snapshot");int objects=save.path("objects").size(),items=save.path("items").size(),recipes=save.path("recipes").size();ObjectNode r=json.createObjectNode().put("headline","工厂结构诊断完成").put("assessment","已完成当前存档的确定性结构分析。").put("confidence",objects>0?.9:.55);ObjectNode s=r.putObject("snapshot");s.put("factory_id",run.path("factory_id").asText()).put("factory_name",save.path("name").asText()).put("factory_version",run.path("base_factory_updated_at").asText()).put("floor_count",save.path("floorCount").asInt(1)).put("object_count",objects).put("item_count",items).put("recipe_count",recipes).put("enabled_recipe_count",recipes).put("inventory_record_count",0).put("simulation_status","snapshot").put("elapsed_sim_sec",0);s.putObject("dimensions_m").put("width",48).put("length",48);s.putObject("object_counts");ObjectNode g=r.putObject("graph_summary");g.put("node_count",objects+items+recipes).put("edge_count",0).put("invalid_reference_count",0);g.putObject("node_counts");g.putObject("edge_counts");r.putObject("metrics").put("throughput_per_min",0).put("work_in_progress",0).put("finished_goods",0).put("elapsed_sim_sec",0).put("sample_count",1);ObjectNode f=r.putArray("findings").addObject().put("id","structure").put("category","graph").put("severity","info").put("title","结构快照已建立").put("detail","对象、物品与工艺已进入证据链。").put("recommendation","结合实时仿真指标继续诊断。");f.putArray("evidence").addObject().put("label","对象").put("value",String.valueOf(objects));f.putArray("object_ids");return r;}

    private JsonNode applyOperations(JsonNode source,JsonNode operations){if(!source.isObject())throw new IllegalArgumentException("Agent 运行缺少工厂存档");ObjectNode save=(ObjectNode)source.deepCopy();ArrayNode objects=(ArrayNode)save.withArray("objects");for(JsonNode op:operations){String kind=op.path("kind").asText(),id=op.path("object_id").asText();JsonNode p=op.path("params");if("remove_object".equals(kind)){for(int i=objects.size()-1;i>=0;i--)if(objects.get(i).path("id").asText().equals(id))objects.remove(i);}else if("add_object".equals(kind)){JsonNode value=p.path("object").isObject()?p.path("object"):p;if(value.isObject())objects.add(value.deepCopy());}else for(JsonNode entry:objects)if(entry.isObject()&&entry.path("id").asText().equals(id)){ObjectNode object=(ObjectNode)entry;if("move_object".equals(kind)){ObjectNode pos=object.with("pos");if(p.has("x"))pos.put("x",p.path("x").asInt());if(p.has("z"))pos.put("z",p.path("z").asInt());if(p.has("floor_id"))object.put("floorId",p.path("floor_id").asInt());}else if("update_config".equals(kind)){String path=p.path("path").asText();JsonNode value=p.get("value");if(!path.isBlank()){if(value==null||value.isNull())object.remove(path);else object.set(path,value);}}else if("adjust_inventory".equals(kind)){ObjectNode storage=object.with("storageConfig");String item=p.path("item_id").asText();double next=storage.with("initialInventory").path(item).asDouble(0)+p.path("quantity").asDouble();if(next<0)throw new IllegalArgumentException("库存调整后不能为负数："+id);storage.with("initialInventory").put(item,next);}}}return save;}
    private List<String> validateResourceOwnership(String owner,JsonNode value){
        List<String> errors=new java.util.ArrayList<>();
        if(value==null)return errors;
        if(value.isArray()){
            for(JsonNode entry:value){
                validateResourceEntry(owner,entry,errors);
                if("add_object".equals(entry.path("kind").asText()))validateResourceEntry(owner,entry.path("params").path("object"),errors);
            }
        }else if(value.isObject()){
            if(value.has("objects"))for(JsonNode entry:value.path("objects"))validateResourceEntry(owner,entry,errors);
            if(value.has("machineDefinitions")&&value.path("machineDefinitions").isArray())for(JsonNode definition:value.path("machineDefinitions"))validateMachineDefinitionResource(owner,definition,errors);
        }
        return errors;
    }
    private void validateResourceEntry(String owner,JsonNode object,List<String> errors){
        if(!object.isObject())return;
        String type=object.path("type").asText("").trim();
        String resourceId=object.path("resourceId").asText("").trim();
        if("imported".equals(type)){
            if(resourceId.isBlank())errors.add("导入对象缺少资源 ID");
            else if(!resources.belongsToUser(owner,resourceId))errors.add("资源不属于当前用户："+resourceId);
        }else if(!resourceId.isBlank()&&"machine".equals(type)){
            // A custom machine's resourceId is a machine-definition ID, not an imported-resource ID.
            // Its imported asset is checked from machineDefinitions below.
        }
    }
    private void validateMachineDefinitionResource(String owner,JsonNode definition,List<String> errors){
        if(!definition.isObject())return;
        if("imported".equals(definition.path("modelType").asText(""))){
            String resourceId=definition.path("importedResourceId").asText("").trim();
            if(resourceId.isBlank())errors.add("导入机器定义缺少资源 ID："+definition.path("id").asText(""));
            else if(!resources.belongsToUser(owner,resourceId))errors.add("资源不属于当前用户："+resourceId);
        }
    }
    private boolean sameSave(JsonNode left,JsonNode right){return canonical(left).equals(canonical(right));}
    private JsonNode canonical(JsonNode value){JsonNode copy=value.deepCopy();if(copy.isObject()){((ObjectNode)copy).remove("savedAt");((ObjectNode)copy).remove("saved_at");}return copy;}
    private String fingerprint(JsonNode n){try{return "save-"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsString(n).getBytes(StandardCharsets.UTF_8))).substring(0,24);}catch(Exception e){throw new IllegalStateException("无法计算存档版本",e);}}
}
