import type { Vec3 } from "../cad/CadTypes.ts";

/**
 * Exact rational B-spline data for one direction of a section-loft surface.
 * The selected direction uses the authored degree, knots, multiplicities and
 * weights. The transverse direction is generated by OCCT's smooth loft.
 */
export interface RationalBSplineSectionDefinition {
  direction: "u" | "v";
  degree: number;
  knots: number[];
  multiplicities: number[];
  /** Rectangular weights indexed exactly like the feature control net. */
  weights: number[][];
}

export interface RationalBSplineSectionValidation {
  valid: boolean;
  issues: string[];
}

const sectionPoleCount = (controlNet: Vec3[][], direction: "u" | "v"): number =>
  direction === "u" ? (controlNet[0]?.length ?? 0) : controlNet.length;

export const createUnitWeightGrid = (rows: number, cols: number): number[][] =>
  Array.from({ length: rows }, () => Array.from({ length: cols }, () => 1));

/** Standard open/clamped, uniformly spaced unique knot sequence. */
export const createClampedUniformBSplineDefinition = (poleCount: number, preferredDegree = 3): Pick<RationalBSplineSectionDefinition, "degree" | "knots" | "multiplicities"> => {
  if (!Number.isInteger(poleCount) || poleCount < 2) throw new Error("B-Spline 截面至少需要 2 个控制点。");
  const requestedDegree = Number.isFinite(preferredDegree) ? Math.trunc(preferredDegree) : 3;
  const degree = Math.max(1, Math.min(25, requestedDegree, poleCount - 1));
  const interiorCount = poleCount - degree - 1;
  const knots = Array.from({ length: interiorCount + 2 }, (_, index) => index / (interiorCount + 1));
  const multiplicities = knots.map((_, index) => index === 0 || index === knots.length - 1 ? degree + 1 : 1);
  return { degree, knots, multiplicities };
};

export const createDefaultRationalBSplineSections = (controlNet: Vec3[][], direction: "u" | "v" = "u", preferredDegree = 3): RationalBSplineSectionDefinition => ({
  direction,
  ...createClampedUniformBSplineDefinition(sectionPoleCount(controlNet, direction), preferredDegree),
  weights: createUnitWeightGrid(controlNet.length, controlNet[0]?.length ?? 0),
});

const resampleWeights = (source: number[], targetCount: number): number[] => {
  if (source.length === targetCount) return [...source];
  if (targetCount <= 1) return [source[0] ?? 1];
  if (source.length <= 1) return Array.from({ length: targetCount }, () => source[0] ?? 1);
  return Array.from({ length: targetCount }, (_, index) => {
    const position = index * (source.length - 1) / (targetCount - 1);
    const left = Math.floor(position), right = Math.min(source.length - 1, left + 1), fraction = position - left;
    return source[left] * (1 - fraction) + source[right] * fraction;
  });
};

/** Keeps a saved weight profile usable when a live boundary relation changes net density. */
export const reconcileRationalBSplineSections = (controlNet: Vec3[][], definition: RationalBSplineSectionDefinition): RationalBSplineSectionDefinition => {
  const generated = createDefaultRationalBSplineSections(controlNet, definition.direction, definition.degree);
  const sourceProfile = definition.direction === "u" ? (definition.weights[0] ?? []) : definition.weights.map((row) => row[0]);
  const profile = resampleWeights(sourceProfile, sectionPoleCount(controlNet, definition.direction));
  generated.weights = generated.weights.map((row, rowIndex) => row.map((_, colIndex) => generated.direction === "u" ? profile[colIndex] : profile[rowIndex]));
  const authored = { ...generated, degree: definition.degree, knots: [...definition.knots], multiplicities: [...definition.multiplicities] };
  return validateRationalBSplineSections(controlNet, authored).valid ? authored : generated;
};

/** U/V weight profiles do not describe the same poles, so changing direction resets only the ambiguous weights. */
export const changeRationalBSplineSectionDirection = (controlNet: Vec3[][], definition: RationalBSplineSectionDefinition, direction: "u" | "v"): RationalBSplineSectionDefinition =>
  direction === definition.direction ? reconcileRationalBSplineSections(controlNet, definition) : createDefaultRationalBSplineSections(controlNet, direction, definition.degree);

export const validateRationalBSplineSections = (controlNet: Vec3[][], definition: RationalBSplineSectionDefinition): RationalBSplineSectionValidation => {
  const issues: string[] = [];
  const rows = controlNet.length, cols = controlNet[0]?.length ?? 0;
  const poleCount = sectionPoleCount(controlNet, definition.direction);
  if (definition.direction !== "u" && definition.direction !== "v") issues.push("截面方向必须是 U 或 V。");
  if (!Number.isInteger(definition.degree) || definition.degree < 1 || definition.degree > 25 || definition.degree >= poleCount) issues.push(`次数必须是 1～${Math.max(1, poleCount - 1)} 的整数。`);
  if (!Array.isArray(definition.knots) || definition.knots.length < 2 || definition.knots.some((value) => !Number.isFinite(value))) issues.push("节点必须包含至少两个有限数值。");
  else if (definition.knots.some((value, index) => index > 0 && value <= definition.knots[index - 1])) issues.push("节点值必须严格递增。");
  if (!Array.isArray(definition.multiplicities) || definition.multiplicities.length !== definition.knots.length || definition.multiplicities.some((value) => !Number.isInteger(value) || value < 1)) issues.push("节点与重数必须一一对应，且重数为正整数。");
  else if (Number.isInteger(definition.degree) && definition.multiplicities.some((value) => value > definition.degree + 1)) issues.push("节点重数不能大于次数加一。");
  if (Number.isInteger(definition.degree) && definition.multiplicities.reduce((sum, value) => sum + value, 0) !== poleCount + definition.degree + 1) issues.push("节点重数总和与控制点数量、次数不匹配。");
  if (!Array.isArray(definition.weights) || definition.weights.length !== rows || definition.weights.some((row) => !Array.isArray(row) || row.length !== cols || row.some((value) => !Number.isFinite(value) || value <= 0))) issues.push("权重网格必须与控制网同尺寸，且所有权重大于 0。");
  else {
    const profiles = definition.direction === "u"
      ? definition.weights
      : Array.from({ length: cols }, (_, col) => definition.weights.map((row) => row[col]));
    const reference = profiles[0] ?? [];
    if (profiles.some((profile) => profile.some((value, index) => Math.abs(value - reference[index]) > 1e-12))) issues.push("平滑截面放样要求各截面使用相同的权重分布。");
  }
  return { valid: issues.length === 0, issues };
};

export const rationalBSplineSections = (controlNet: Vec3[][], definition: RationalBSplineSectionDefinition): Array<{ poles: number[]; weights: number[] }> => {
  const validation = validateRationalBSplineSections(controlNet, definition);
  if (!validation.valid) throw new Error(validation.issues.join(" "));
  if (definition.direction === "u") return controlNet.map((row, rowIndex) => ({
    poles: row.flatMap((point) => [point.x, point.y, point.z]),
    weights: [...definition.weights[rowIndex]],
  }));
  return Array.from({ length: controlNet[0].length }, (_, colIndex) => ({
    poles: controlNet.flatMap((row) => [row[colIndex].x, row[colIndex].y, row[colIndex].z]),
    weights: controlNet.map((_, rowIndex) => definition.weights[rowIndex][colIndex]),
  }));
};
